### ISSUE TITLE
Add --set option to engine, target

### ISSUE THREAD

**Issue by theory** [sqitchers/sqitch#275]
This will add a `variables` section to the specific engine or target, complementing the variables that can be set by the `deploy` command. Don't think we need `--set` for init.

**Comment by nugget** [comment]
This would be a really powerful addition.  Is this still on the roadmap?

**Comment by theory** [comment]
Yep, but I don't have much time to hack on Sqitch these days. Want to take a stab at it?

**Comment by nugget** [comment]
I'd love to, but my Perl is weak and I can't even get Dist:Zilla to install.  Seems unapproachable to me, sorry.

**Comment by kwakwaversal** [comment]
I'll take a look at doing this. How do you envisage the `variables` section to look in the `sqitch.conf`?

```ini
[core]
        engine = pg
[engine "pg"]
        target = db:pg:
        [variables]
                ON_ERROR_STOP = 1
                foo = baz
[target "dev"]
        uri = db:pg://username:password@localhost/somedatabase
        [variables]
                ON_ERROR_STOP = 1
                foo = baz
```

I'm just guessing here. I've not checked the code for parsing the config to see if it supports multi-dimensional config.

**Comment by nugget** [comment]
In my googling earlier today I found references to a syntax like `set        = foo=bar` ([ref](http://search.cpan.org/~dwheeler/App-Sqitch-0.992/lib/sqitch-config.pod)) from older versions of Sqitch. 

Is that approach deprecated now in favor of the `[verify "variables"]` style blocks (which aren't directly usable as @kwakwaversal points out above?

Both the nested section and the `set = foo= bar` seem ungainly, but I'm not coming up with a better approach.

**Comment by theory** [comment]
Engine and Target already have `--target`, `--registry`, `--client` options and the like. These are just set under the target or engine. The `engine` command pulls them together [here](/theory/sqitch/blob/master/lib/App/Sqitch/Command/engine.pm#L115) and sets them [here](/theory/sqitch/blob/master/lib/App/Sqitch/Command/engine.pm#L124). All you have to do is add a `--set` option, probably in [App::Sqitch::Role::TargetConfigCommand](/theory/sqitch/blob/master/lib/App/Sqitch/Role/TargetConfigCommand.pm#L32) to affect both the engine and target commands, validate them in [`configure()`](/theory/sqitch/blob/master/lib/App/Sqitch/Role/TargetConfigCommand.pm#L44) and merge them into the config, like [deploy does](/theory/sqitch/blob/master/lib/App/Sqitch/Command/deploy.pm#L90), something like

```
    if ( my $vars = $opt->{set} ) {
        $props{variables} = {
            %{ $config->get_section( section => "$key.variables" ) || {} },
            %{ $vars },
        };
    }
```

Then update all the docs, especially [sqitch-configuration](/theory/sqitch/blob/master/lib/sqitch-configuration.pod), add them to the output of [`show()`](/theory/sqitch/blob/master/lib/App/Sqitch/Command/engine.pm#L268), etc. That will get the into the file.

Then, to get them to be available for the commands that need them, change the behavior of Engine's [`variables` attribute](/theory/sqitch/blob/master/lib/App/Sqitch/Engine.pm#L92) to read them from Target and let any args passed to the attribute override whatever's read from the Target. You'll need to add a `variables` method to Sqitch::Target for this, probably something like:

```
has variables => (
    is  => 'ro',
    isa => Hash,
    lazy => 1,
    default => sub {
        shift->_fetch('variables') || {}
    },
);
```

Relying on `_fetch` to look for them in the proper order. Or, no, probably have to read variables from all of them and merge the results, something like:

```
has variables => (
    is  => 'ro',
    isa => Hash,
    lazy => 1,
    default => sub {
        my $self = shift;
    my $config = $sqitch->config;
    return {
        %{ $config->get( key => "target." . $self->name . '.variables' ) || {} },
        %{ $self->_engine_var($config, scalar $self->engine_key, 'variables') || {} },
        %{ $config->get( key => "core.variables") || {} },
    };
);
```

Okay, I think that about covers it! LMK if you have questions!

**Comment by theory** [comment]
Turns out it was a bit more work than I spaced out above. Figures. Review of #417 would be appreciated.
