### ISSUE TITLE
"What's this registry and why is it at version 0.0?"

### ISSUE THREAD

**Issue by Relequestual** [sqitchers/sqitch#276]
Today, I was using a newer version of Sqitch than I had previously.
As I ran the update deploy action, I see the numbers 0.0 to 1.0 and shudder...

"Did it somehow loose update history? is it now applying all my updates again?" _cancles_

After some investigation, I understand what it is, and why it's doing what it's doing. That's fine. But as an end user, it was somewhat scary. Maybe there could be a prompt with a small message along the lines of "The table structures we used to store database schema versions has changed, and needs updating. This does not effect your regular schema changes. This is required. [Yes]"

**Comment by theory** [comment]
Not sure why we'd prompt, but I could see that it might be useful to have a more detailed status message.
