### ISSUE TITLE
Use Travis CI to create and publish packages to GitHub and/or upstream/private repositories

### ISSUE THREAD

**Issue by jmealo** [sqitchers/sqitch#283]
Have you considered creating packages using Travis as part of the build process?

I tried to do some of the legwork/research and document it in this ticket. It might be worth just firing off an email to each distributions mailing list to see if someone is willing to sponsor sqitch or even create/maintain the sqitch package for you.
#### Where to submit packages for inclusion in upstream package managers:
- [Debian/Ubuntu](https://wiki.ubuntu.com/MOTU/Packages/REVU)
- [SmartOS/NetBSD/Minix](http://pkgsrc.org/wip/)
- [Arch Linux](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)
- [Fedora](https://fedoraproject.org/wiki/Package_Review_Process)
- [Redhat/Fedora (unofficial)](http://rpmfusion.org/Contributors#Submitting_a_new_package)
- [Gentoo](https://wiki.gentoo.org/wiki/Submitting_ebuilds) _see note on not submitting CPAN builds_
#### Where to host packages unofficially:
- **Ubuntu:** I've seen a fair number of PPAs hosted on [launchpad](https://help.launchpad.net/Packaging/PPA).
- **[SmartOS/NetBSD/Minix](https://pkgsrc.joyent.com/docs/creating/)** _(they recommend niche packages be hosted on GitHub, so if you cannot find a sponsor, GitHub releases are an option)_

**Relevant links:**
- [GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases)
- [Effing package management! Build packages for multiple platforms (deb, rpm, etc) with great ease and sanity.](https://github.com/jordansissel/fpm)
- [How to package for Debian](https://wiki.debian.org/HowToPackageForDebian)
- [Ubuntu packaging guide](http://packaging.ubuntu.com/html/)

**I haven't used FPM personally, but its goals are noble and it claims to do something that should speed things up:**
The [FPM](https://github.com/jordansissel/fpm) documentation doesn't say that it supports CPAN as a source, however, if you view the [tests](https://github.com/jordansissel/fpm/blob/master/spec/fpm/package/cpan_spec.rb) and [issues](https://github.com/jordansissel/fpm/issues?utf8=%E2%9C%93&q=cpan) there appears to be support in some form or another.

If you don't want to tie the Travis CI and release uploads to however you manage Git, it'd still be pretty easy just to push the packages into S3 or something comparable without using the official workflow.

**Comment by theory** [comment]
In this vein, there is now a [Docker image](https://hub.docker.com/r/sqitch/sqitch/). See the [docker-sqitch](/sqitchers/docker-sqitch) project for the implementation.

**Comment by jmealo** [comment]
@theory I can't tell if we should be happy or sad that it's easier to make a docker container than an OS package. Thank you for the update.

**Comment by theory** [comment]
I don't know if it was any easier, but I was motivated. 🤷‍♂️
