### ISSUE TITLE
OSX Homebrew sqitch_pg: Installing Time::HiRes failed

### ISSUE THREAD

**Issue by kpyorala** [sqitchers/sqitch#319]
Trying to install `sqitch_pg` to OSX 10.11.6 with Homebrew 1.0.9:

```
cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9995' --notest Time::HiRes

--> Working on Time::HiRes
Fetching http://www.cpan.org/authors/id/J/JH/JHI/Time-HiRes-1.9740.tar.gz ... OK
Configuring Time-HiRes-1.9740 ... OK
Building Time-HiRes-1.9740 ... ! Installing Time::HiRes failed. See /private/tmp/sqitch_dependencies-20161030-30772-1w22fuf/.brew_home/.cpanm/work/1477861800.44717/build.log for details. Retry with --force to force install it.
FAIL

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/theory/homebrew-sqitch/issues
```

Log file mentioned in error message doesn't exists.

**Comment by perezperret** [comment]
I am having exactly the same problem, running `cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9995' --notest Time::HiRes` by itself works fine

**Comment by perezperret** [comment]
I'll share my workaround, I'm no expert though, so do read up the docs on the commands I'm suggesting so you have an idea of what you're doing:

- Remove previous install if needed `brew rm sqitch_pg && brew rm sqitch_dependencies`
- Run `brew edit sqitch_dependencies`, this allows you to modify the formula
- In the open editor replace `line 24` (`next if pkg == 'perl'`) with `next if pkg == 'perl' || pkg == 'Time::HiRes'`, and save, this will skip the perl package installation raising the error.
- Run `brew install sqitch_dependencies`, to install the modified formula.
- Run `cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9995' --notest Time::HiRes` to manually install the package.
- Run `brew link sqitch_dependencies` to link the homebrew library.
- Running `brew install sqitch_pg` should now work.

**Comment by theory** [comment]
What's in the build log (`/private/tmp/sqitch_dependencies-20161030-30772-1w22fuf/.brew_home/.cpanm/work/1477861800.44717/build.log`)? Would be good to see what the issue is with Time::HiRes.

**Comment by theory** [comment]
FWIW, I'm creating a brand new Sqitch formula, to be released once v0.9998 is released. The `sqitch_dependencies` script will be gone, and everything should be installed properly as a single bundle, rather than scattered around the file system. I have not encountered this issue with Time::HiRes while developing the new formula; hopefully it will be gone. If not, please open an issue in the [sqitch-homebrew project](/sqitchers/homebrew-sqitch).

**Comment by suederat** [comment]
1540 dist/Time-HiRes/t/stat ......................................... #   Failed test at t/stat.t line 35.
1541 #     Structures begin differing at:                                            
1542 #          $got->[8] = '1554740495.63254'                                       
1543 #     $expected->[8] = '1554740495.63052'                                       
1544 #   Failed test at t/stat.t line 35.                                            
1545 #     Structures begin differing at:                                            
1546 #          $got->[8] = '1554740495.85113'                                       
1547 #     $expected->[8] = '1554740495.74432'                                       
1548 #   Failed test at t/stat.t line 35.                                            
1549 #     Structures begin differing at:                                            
1550 #          $got->[8] = '1554740496.14189'                                       
1551 #     $expected->[8] = '1554740496.01307'                                       
1552 #   Failed test at t/stat.t line 35.                                            
1553 #     Structures begin differing at:                                            
1554 #          $got->[8] = '1554740496.48877'                                       
1555 #     $expected->[8] = '1554740496.30556'                                       
1556 #   Failed test at t/stat.t line 35.                                            
1557 #     Structures begin differing at:                                            
1558 #          $got->[8] = '1554740496.76763'                                       
1559 #     $expected->[8] = '1554740496.62781'                                       
1560 # Looks like you failed 5 tests of 43.                                          
1561 FAILED at test 6

**Comment by theory** [comment]
[This error](https://rt.cpan.org/Ticket/Display.html?id=123405) looks similar, @suederat. @atoomic: Have you seen this Time::HiRes failure on macOS before?
