### ISSUE TITLE
Should we add the core.pager option to override the PAGER environment variable?

### ISSUE THREAD

**Issue by yati-sagade** [sqitchers/sqitch#328]
I noticed that running `sqitch log` produces ANSI color codes, which is sent to `less` on my box by `IO::Pager`. This does not have the intended effect of course, and doing `export PAGER=less -r` resolves it. However, might people not want to set a pager for sqitch alone? If we think so, here's a proposal:

```bash
$ sqitch config --user core.pager 'less -r'
```

That already works! Then, this small patch (or anything that has its effect) will do the trick:

```diff
diff --git a/lib/App/Sqitch.pm b/lib/App/Sqitch.pm
index 77924df..462c02b 100644
--- a/lib/App/Sqitch.pm
+++ b/lib/App/Sqitch.pm
@@ -187,6 +187,9 @@ sub go {
             args    => $cmd_args,
         });
 
+        local $ENV{PAGER} = $config->get(key => "core.pager") //
+            $ENV{PAGER};
+
         # 7. Execute command.
         $command->execute( @{$cmd_args} ) ? 0 : 2;
     } catch {
```

Let me know if you think this is worth implementing (IMO it is a quick win, but you may not want a config creep, but again, sqitch UI is inspired by git's, so...)

PS: I'm playing with sqitch as part of this month's CPAN PRC -- congratulations for the really well written code :)

**Comment by theory** [comment]
Thanks! I like it! Care to write a test, document it in `lib/sqitch-config.pod`, and submit a PR?

**Comment by theory** [comment]
Done in #329.
