### ISSUE TITLE
Tilde in sqlite db path on command line

### ISSUE THREAD

**Issue by woky** [sqitchers/sqitch#337]
It seems that sqitch (0.9995) doesn't expand ~ into user's home directory.  Compare:

```
user@localhost:~/db$ sqitch deploy db:sqlite:$HOME/foo.db 
Adding registry tables to db:sqlite:/home/user/sqitch.db
Deploying changes to db:sqlite:/home/user/foo.db
  + schema .. ok
```

```
user@localhost:~/db$ sqitch deploy db:sqlite:~/foo.db 
Undef did not pass type constraint "Str" (in $args->{"message"}) at (eval 507) line 120
    "Str" is a subtype of "Value"
    "Value" is a subtype of "Defined"
    Undef did not pass type constraint "Defined" (in $args->{"message"})
    "Defined" is defined as: (defined($_))
```

The error message is scary and not useful...

**Comment by theory** [comment]
*May* be a bug in [URI::db](https://github.com/theory/uri-db); but the error message here could certainly be better.

**Comment by theory** [comment]
Hrm. I get:

    sqitch deploy db:sqlite:~/foo.db 
    unable to open database file

Which looks like the error from SQLite itself.

**Comment by theory** [comment]
Can you apply this patch and then trigger the bug again, so I can see exactly where the error is coming from?

    --- a/lib/App/Sqitch/X.pm
    +++ b/lib/App/Sqitch/X.pm
    @@ -49,6 +49,9 @@ sub hurl {
                 : @_ == 1 ? (message => $_[0])
                 :           (ident => $_[0],  message => $_[1])
         );
    +    my %p = @_[1..-1];
    +    __PACKAGE__->throw(message => 'No message') unless defined $p{message};
    +
         goto __PACKAGE__->can('throw');
     }
 
Thanks!

**Comment by theory** [comment]
I plan to release v0.9996 today. If you can try the above patch and send me the output, I can try to fix it before release. Otherwise I'll have to defer it to the next version. Thanks!

**Comment by theory** [comment]
Hey @woky, any chance you could apply the above patch and trigger the bug again? Thinking about another release soon…

**Comment by theory** [comment]
Closing since I can't replicate the nasty error message. Please reopen if the issue persists with v0.9997.
