### ISSUE TITLE
Add Cassandra support

### ISSUE THREAD

**Issue by dimon777** [sqitchers/sqitch#348]
Cassandra has cqlsh cli which can be used to integrate with sqitch. I can help with this where I can. Any docs on how to add another database support to sqitch?

**Comment by dimon777** [comment]
Bumping up my question...

**Comment by theory** [comment]
No docs, really, just the existing implementations, which currently all assume SQL execution through the DBI. They each extend [App::Sqitch::Engine] and use the with [App::Sqitch::Role::DBIEngine] role to share common code. The engines:

* Postgres: [SQL](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/pg.sql) | [Perl](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/pg.pm)
* SQLite: [SQL](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/sqlite.sql) | [Perl](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/sqlite.pm)
* MySQL: [SQL](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/mysql.pm) | [Perl](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/mysql.pm)
* Oracle: [SQL](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/oracle.sql) | [Perl](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/oracle.pm)
* Vertica: [SQL](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/vertica.sql) | [Perl](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/vertica.pm)
* Firebird: [SQL](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/firebird.pm) | [Perl](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/firebird.pm)

[App::Sqitch::Engine]: /theory/sqitch/blob/master/lib/App/Sqitch/Engine.pm
[App::Sqitch::Role::DBIEngine]: /theory/sqitch/blob/master/lib/App/Sqitch/Role/DBIEngine.pm

HTH!

**Comment by theory** [comment]
Closing in favor of PR #361.
