### ISSUE TITLE
Stop setting the MYSQL_PWD environmental variable

### ISSUE THREAD

**Issue by ealter** [sqitchers/sqitch#350]
The [MySql password security documentation](https://dev.mysql.com/doc/refman/5.6/en/password-security-user.html) talks about how this method is very insecure since the `ps e` command exposes all the environmental variables for a given process. Based on the discussion in #100 and #150, it looks like [DBD::mysql](https://metacpan.org/pod/DBD::mysql) didn't use to support the more secure option of `~/.my.cnf`. However when I briefly glanced at it tonight, it looks like it [does have support](https://metacpan.org/pod/DBD::mysql#mysql_read_default_group) for that configuration file.

Do you think we could switch to that method of authentication or at least add a config value to use it?

**Comment by theory** [comment]
Well, Sqitch uses MySQL::Config to read the config files as of a3849dc. As far as I could tell at the time, that was the recommended way to get passwords for MySQL. But if DBD::mysql has been improved to read the config files, I'd welcome a PR that replaces the use of MySQL::Config, along with an appropriate update to [sqitch-passwords](https://github.com/theory/sqitch/blob/master/lib/sqitch-passwords.pod).

**Comment by ealter** [comment]
Didn't see that password page! Thanks for the link.

What's the best way to discover the rest of the sqitch documentation like that? I didn't see that during my searching yesterday.

I'll see what I can do with digging into that mysql library, but I don't know how far I'll get because I don't know any Perl.

**Comment by theory** [comment]
> sqitch help -g
        The common Sqitch guides are:

          changes             Specifying changes for Sqitch
          configuration       Hierarchical engine and target configuration
          environment         Environment variables
          passwords           Specifying target passwords
          tutorial            PostgreSQL Tutorial
          tutorial-firebird   Firebird Tutorial
          tutorial-mysql      MySQL Tutorial
          tutorial-oracle     Oracle Tutorial
          tutorial-sqlite     SQLite Tutorial
          tutorial-vertica    Vertica Tutorial

        See "sqitch help <command>" or "sqitch help <concept>" to read about a
        specific command or concept.

**Comment by ealter** [comment]
Thanks. I didn't see any references to that when I did `sqitch help`.

**Comment by theory** [comment]
> sqitch help help
    Name
        sqitch-help - Display help for Sqitch and Sqitch commands

    Synopsis
          sqitch help [COMMAND]
          sqitch help --guide

    Description
        With no options and no "COMMAND" given, the synopsis of the "sqitch"
        options and a list of the most commonly used Sqitch commands will be
        displayed.

        If the option "--guide" or "-g" is given, then a list of Sqitch guides
        will be displayed

        If a Sqitch command is named, the documentation for that command will be
        displayed.

    Options
        "-g"
        "--guide"
            Prints a list of available Sqitch guides.

    Sqitch
        Part of the sqitch suite.

**Comment by ealter** [comment]
Ah. It might be nice to make a note of that in `sqitch help` since knowing to do `sqitch help help` isn't very intuitive.
