### ISSUE TITLE
Alpine Support?

### ISSUE THREAD

**Issue by bhgames** [sqitchers/sqitch#351]
I'd like to use this in my Alpine docker image, but I'm not sure how. Has anybody else come across this need?

Thanks

**Comment by ealter** [comment]
What have you tried so far and what errors have you run into? I've gotten it working in a debian:stretch based dockerfile but I haven't tried alpine.

**Comment by bhgames** [comment]
Hey so ultimately I made a dockerfile for this. Basically started off an alpine-perl and cpanm installed it. What I do is in my Dockerfile for a node app, start with a base layer that does the yarn install, and then a second layer based on my Dockerfile below. I copy over the compiled node_modules, node, and source code, and then my source code can run on a node server and also make sqitch calls on startup to migrate the database.

www.github.com/bhgames/alpine-sqitch

**Comment by theory** [comment]
@bhgames I love how simple that Dockerfile is! Meanwhile, I've been working on an official project Dockerfile, Also Alpine-based (at least for now), which you'll find [here](/sqitchers/docker-sqitch). Once v0.9998 goes out (hopefully this week), I'll get builds pushed out to Docker Hub, too. Note that this image includes support for Postgres, SQLite, and MySQL; expect it to get better over time. Thanks!

**Comment by dargmuesli** [comment]
Now, what happened to this? :0

**Comment by theory** [comment]
You can install Sqitch on Alpine using `cpanm`, but I had to change the [docker project](/sqitchers/docker-sqitch) to use Debian at some point, don't recall why. Would like to get back to the Alpine Docker image, but I have very little time to work on the project these days.

**Comment by dargmuesli** [comment]
Looks like there are [no firebird packages on alpine linux](https://pkgs.alpinelinux.org/packages?name=*firebird*&branch=edge). Maybe that was the reason to use debian?

**Comment by theory** [comment]
Yes! I realized the Java stuff was going to be a bit more complicated, and wanted to include the OSS databases in the core image, which included Firebird. Thanks for the reminder!

I have envisioned building a process to create a slew of images, each supporting a single engine, based on Alpine where possible and Debian where required. But as I said, `ENOTUITS`. :-(
