### ISSUE TITLE
Deploying for first time using pgpool fails

### ISSUE THREAD

**Issue by golpa** [sqitchers/sqitch#359]
We have a pgpool server in front of 3 postgres servers doing streaming replication. It appears the first deploy (which creates the sqitch schema and tables) doesn't work through pgpool. In this scenario sqitch just gets stuck. The sqitch command doesn't provide any output and never exits. If we bypass pgpool and directly connect to the master postgres server we can perform the first deploy with no problems.

After the first deploy has been performed subsequent operations seem to work fine over pgpool including reverting to an empty db and redeploying.

**Comment by golpa** [comment]
Forgot to mention versions:
`App::Sqitch 0.9996`
`Pgpool 3.5.7`
`Postgresql 9.4.11`

**Comment by theory** [comment]
I assume this is because pgPool doesn't support DDLs, yes?

**Comment by golpa** [comment]
Certainly not a pgPool expert but we've not had trouble using DDLs through pgPool for anything else.

[This](https://www.2ndquadrant.com/media/pdfs/talks/char10/master-slave-pgpool.pdf) slideshow seems to suggest at least for our mode of operation DDL is supported (slide 20)

**Comment by theory** [comment]
Would be useful to know what it's choking on. First deploy does initializes the registry, which encompasses [a bunch of stuff](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/pg.pm#L178), though especially running [the DDLs](/theory/sqitch/blob/master/lib/App/Sqitch/Engine/pg.sql) through `psql`. With pg_pool, does `psql -c 'SHOW server_version_num'` show the version number?

**Comment by golpa** [comment]
Looks like it's responding with the same version if I connect via pgpool or directly to master host.

pgpool host:
```
psql -h dbpool01 -U sessions_dev -c 'SHOW server_version_num'
Password for user sessions_dev: 
 server_version_num 
--------------------
 90411
(1 row)
```
Master host directly:
```
psql -h dclst02 -U sessions_dev -c 'SHOW server_version_num'
Password for user sessions_dev: 
 server_version_num 
--------------------
 90411
(1 row)
```

**Comment by theory** [comment]
So it's not that. See if you can figure out what it's getting hung up on.

**Comment by theory** [comment]
Hi @golpa, any luck tracking down the hangup?

**Comment by theory** [comment]
Hi @golpa, any luck tracking down the hangup?

**Comment by theory** [comment]
Closing since no progress in two years. Please re-open if the issue comes up again.
