### ISSUE TITLE
Unable to launch brewed sqitch on mac

### ISSUE THREAD

**Issue by xleliberty** [sqitchers/sqitch#381]
Hi, 
i've just tried to install sqitch on my mac via homebrew

I'me facing the following problem: 

dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /usr/local/lib/perl5/darwin-thread-multi-2level/auto/Locale/gettext_xs/gettext_xs.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /usr/local/lib/perl5/darwin-thread-multi-2level/auto/Locale/gettext_xs/gettext_xs.bundle
  Expected in: flat namespace

[1]    48679 abort      sqitch

here are information: 

Macos : 10.13.4
Homebrew 1.6.3
Homebrew/homebrew-core (git revision 1b61c; last commit 2018-05-18)

I've tried: 

cpanm -U --local-lib "`brew --prefix`" --notest Locale::gettext_xs
and
cpanm --local-lib "`brew --prefix`" --notest Locale::gettext_xs

but still same problem

Any help possible ? 

Thanks in advance

**Comment by xleliberty** [comment]
Ok, 
found the problem.

The brew sqitch installed version has an hardcoded shebang pointing to system installed perl

#!/usr/bin/perl -w -CAS

eval 'exec /usr/bin/perl -w -CAS -S $0 ${1+"$@"}'

found in /usr/local/Cellar/sqitch/0.9997/bin/sqitch

Once modified for /usr/local/bin/perl , it works

**Comment by theory** [comment]
That script should have been copied to ` /usr/local/Cellar/sqitch/0.9997/blib/scripts/sqitch` and the shebang updated for the Perl that installs it. What's in *that* file?

**Comment by theory** [comment]
I've rewritten the Homebrew formulas and will be releasing them soon. If this is still an issue post v0.9998, please file an issue with the [homebrew-sqitch])(/sqitchers/homebrew-sqitch) project.
