### ISSUE TITLE
Unable to Connect to postgres on google cloud

### ISSUE THREAD

**Issue by noamtzuberi** [sqitchers/sqitch#385]
Hi,

I'm trying to connect from sqitch to postgres on google cloud and I can't succeed to establish a connection.

**My command:**
```
sqitch status -t prod
```
**Output:**
```
# On database prod
could not connect to server: Operation timed out
	Is the server running on host "" and accepting
	TCP/IP connections on port 5432?
```

My uri is db:pg://[user_name]:[password]@[google_cloud_ip_address]/[dbname]
Any suggestion maybe? 

Thanks,
Noam.

**Comment by theory** [comment]
I'm afraid you'll to provide more information. I suggest you post to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) and include the contents of your `sqitch.conf` file (with sensitive information redacted, of course).
