### ISSUE TITLE
Best way to re-deploy a view?

### ISSUE THREAD

**Issue by joeandaverde** [sqitchers/sqitch#386]
It's often the case that changing a view will require other views to be updated. This kind of behavior has a trickling effect that may require multiple drops and creates.

Any thoughts on how this experience could be improved?

Here's an example:

I want to alter a table to change the column type from int to bigint. A view (vw_x) referenced that column and subsequently needs to be dropped and recreated. That view is referenced by another view (vw_y).

Alter file:
```
BEGIN;
DROP VIEW vw_y;
DROP VIEW vw_x;
ALTER TABLE .... 
COMMIT;
```

*** database in an invalid state since views are missing ***

sqitch reworked vw_x:

```
CREATE VIEW vw_x
```

sqitch reworked vw_y

```
CREATE VIEW vw_y
```

Couple simple not thought through ideas:
* Perhaps there's a sqitch type that can include multiple files to support transaction DDL changes while maintaining the nice file structure.
* A new app plan entry to just re-run a file without tag.

**Comment by theory** [comment]
I use `psql`'s `\include` syntax for stuff like this.

**Comment by joeandaverde** [comment]
This could be game changing for us! May I suggest adding this suggestion to the website? 

How do you deal with relative paths?

**Comment by theory** [comment]
I always run sqitch from a specific directory (where the project`sqitch.conf` file lives, typically the Git repo root), so just specify paths from there. But there are [other ways to deal with paths](https://stackoverflow.com/a/7626897/79202),

**Comment by joeandaverde** [comment]
Will the working directory of the psql process be the directory of `sqitch.conf`?

With this new information here's what I've come up with:

This is what I tried first:

```
BEGIN;

DROP VIEW my_schema.vw_x;
DROP VIEW my_schema.vw_y;

ALTER TABLE my_schema.my_table
ALTER COLUMN foo_id TYPE bigint;


\include deploy/my_schema/views/vw_y@v4.24.0.sql
\include deploy/my_schema/views/vw_x.sql

COMMIT;
```
I ended up doing this to get the view at the time of the change. This will be dependent of course on the change. In this case, there was no change to the view definition:

```
-- Deploy phoenix:my_schema/schema/alter/fix_fk_column_types to pg

BEGIN;

CREATE TEMP TABLE IF NOT EXISTS _migration_view_temp (
   view_name text,
   view_definition text
);

INSERT INTO _migration_view_temp
SELECT 'my_schema.vw_x', view_definition
FROM information_schema.views
WHERE table_name = 'vw_x'
   AND table_schema = 'my_schema';

INSERT INTO _migration_view_temp
SELECT 'my_schema.vw_patient_outbound_messages', view_definition
FROM information_schema.views
WHERE table_name = 'vw_patient_outbound_messages'
   AND table_schema = 'my_schema';

DROP VIEW my_schema.vw_patient_outbound_messages;

DROP VIEW my_schema.vw_x;

ALTER TABLE my_schema.my_table
ALTER COLUMN foo_id TYPE bigint;

DO $$
BEGIN
   EXECUTE (
      SELECT 'CREATE VIEW ' || view_name || ' AS ' || view_definition
      FROM _migration_view_temp
      WHERE view_name = 'my_schema.vw_x'
   );
END $$;

DO $$
BEGIN
   EXECUTE (
      SELECT 'CREATE VIEW ' || view_name || ' AS ' || view_definition
      FROM _migration_view_temp
      WHERE view_name = 'my_schema.vw_patient_outbound_messages'
   );
END $$;

COMMIT;
```

I tried to use includes but found that I couldn't guarantee the code that ran unless I reworked a view and added a tag to the file name.

**Comment by theory** [comment]
I suggest you post to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) about this.
