### ISSUE TITLE
Could not connect to remote cloud database with ssh tunnel

### ISSUE THREAD

**Issue by ProvoK** [sqitchers/sqitch#387]
Hello there,
I'm having trouble connecting to a remote database using an ssh tunnel.

Since the DB is not exposed to the outside, but there is thee need to deploy from local machines, what we've done is

`ssh -i ~/.ssh/my_certificate user@remote-host -L 32000:database_cloud_host:5432`

and then, while that is open

`sqitch status db:pg://db_user:db_password@localhost:32000/database_name`

 but what I get in return is

```
could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 32000?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 32000?
```

That exact same connection URI works with `psql`, `pgAdmin` and so on.

EDIT: with the homebrew v0.9997 seems working. With the built version from master it's not working

**Comment by theory** [comment]
Please direct questions such as this to the [mail list](https://groups.google.com/d/forum/sqitch-users).
