### ISSUE TITLE
When trying to brew install sqitch I get this error any thoughts?

### ISSUE THREAD

**Issue by Domthegrom** [sqitchers/sqitch#388]
<img width="491" alt="screen shot 2018-06-25 at 4 57 50 pm" src="https://user-images.githubusercontent.com/23178405/41875515-0b8f2d6e-7899-11e8-9f21-eb9485c36907.png">
First time attempting to install sqitch and use sqitch also.

**Comment by theory** [comment]
Have you set up the tap?

  brew tap sqitchers/sqitch

BTW, Brew issues in the future should go into the [Homebrew Sqitch](/sqitchers/homebrew-sqitch) project.

**Comment by Domthegrom** [comment]
Sorry about that @theory I'll make sure if I have brew issues in the future to open them there. Yeah I attempted to run `brew tap sqtichers/sqitch` but I get this error in return. 
<img width="573" alt="screen shot 2018-06-25 at 9 36 28 pm" src="https://user-images.githubusercontent.com/23178405/41884091-db3bafbc-78bf-11e8-9f71-0655e72f0a1a.png">

**Comment by theory** [comment]
`https://github.com/sqitchers/homebrew-sqitch` is the correct URL; I'm afraid I don't know what the issue is here, since it's emitted by Homebrew. Maybe [ask them](https://discourse.brew.sh/)?
