### ISSUE TITLE
Cannot find deploy template when sqitch add

### ISSUE THREAD

**Issue by ienugr** [sqitchers/sqitch#389]
# Background
I am trying to add new change on my plan by executing:
```bash
sqitch add my_changes -n "My changes"
```
and it returned:
```bash
Cannot find deploy template
```
# Additional Information
My Sqitch etc directory
```bash
sqitch --etc-path
/usr/local/etc/sqitch
```
# Workaround
Run `sqitch add` as SUDO
```bash
sudo sqitch add my_changes -n "My changes"
```
The problem here every time I made changes on the generated sql file, will always ask for password.

Another workaround is by copying the `etc` directory to another directory and use `--template-directory` flag when `sqitch add`. For example:
```bash
# copy sqitch folder from etc directory to home folder
sudo cp -R $(sqitch --etc-path) ~/.

# go to home directory and change ownership & permission for the copied folder
cd ~
sudo chown -R $USER:$USER sqitch
sudo chmod u+rx,go-w sqitch
sudo chmod u+rx,go-w sqitch/*

# make sure can cd to the sqitch folder 
cd ~/sqitch
cd templates

# try sqitch add by using --template-directory flag
cd <your-sqitch-project>
sqitch add my_changes -n "My changes" --template-directory ~/sqitch/templates
```

**Comment by theory** [comment]
Sounds like the permissions are screwed up on your templates, so you can't read them unless you're root. You should be able to `chmod` the etc directory and its contents to let all have read access to them.

    chmod -R o+r $(sqitch --etc-path)

**Comment by ienugr** [comment]
Hi @theory, I tried to `chmod` the etc directory using above command, but still unable to access the etc directory with `permission denied` message. But, if run this following command:
```
chmod -R o+rx $(sqitch --etc-path)
```
I am able to access the etc directory. Thank you :bowing_man:
