### ISSUE TITLE
production deployment

### ISSUE THREAD

**Issue by itaied246** [sqitchers/sqitch#390]
I'm trying out `sqitch` on my project `pg` db for a web application.

I was wondering how should the db migrations (or updates) be executed?
I am deploying my app in a continuous deployment automated tool connected to my `git` repo (using gitlab).

I don't want to keep the passwords in my development environment,
so keeping it in a file seems a bit odd (I read an issue for env vars, but it was declined).

The process I was thinking about is applying a `migration` stage during the pipeline,
just before the deployment (like `gitlab` does).

How do you suggest to do it?

**Comment by theory** [comment]
I sugggest you join the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) and post your questions there.

**Comment by christiaanwesterbeek** [comment]
Since this is the most related git issue I could find that is related to a similar question I'm having, I leave a link to the question I've posted on the mail list.

https://groups.google.com/forum/#!topic/sqitch-users/I-OHG4yIxlM
