### ISSUE TITLE
sqitch rebase "No such file or directory" error

### ISSUE THREAD

**Issue by renchdev2** [sqitchers/sqitch#391]
I'm running sqitch on macOS.  When I run:

 `sqitch rebase -y --verify`

I get this error:

`No such file or directory.  "/usr/local/Cellar/postgresql/10.4/bin/psql" unexpectedly returned value 1`

I had run this config setting:

`sqitch config --user engine.pg.client /usr/local/Cellar/postgresql/10.4/bin/psql`

but it seems to have caused a problem.  Is there a way to unset this ?  I've tried:

`sqitch config --unset engine.pg.client`

but it returns "No occurrence of engine.pg.client found to unset in sqitch.conf.

**Comment by theory** [comment]
Try again but pass the `--user` option again.
