### ISSUE TITLE
use pgsql extension for sqitch

### ISSUE THREAD

**Issue by lifeiscontent** [sqitchers/sqitch#392]
Hi, I was wondering if sqitch has support for changing the `.sql` to something like `.pgsql` my code editor formats code different depending on filetype and was wondering if this is possible, or I should just overwrite my editor settings.

**Comment by theory** [comment]
Yes, you can set the [`extension`](/sqitchers/sqitch/blob/master/lib/sqitch-configuration.pod#user-content-extension) config at the target, engine, or core level. `.sql` is just the default.

I suggest you consider joining the [mail list](
https://groups.google.com/forum/#!forum/sqitch-users) if you have any more questions. Thanks!
