### ISSUE TITLE
How to add new database engine?

### ISSUE THREAD

**Issue by mgtest42** [sqitchers/sqitch#395]
I’m using sqitch quite long with postgresql, but now I need to add another database to the project (clickhouse).
It’s quite new database and doesn’t have own migration tools.
And I can’t find docs about adding new engines to sqitch.
Is it hard? Where can I start?

**Comment by theory** [comment]
Please provide more detail about what you need (different database same schema? Different schema?) and send your question to the [mail list](
https://groups.google.com/forum/#!forum/sqitch-users). Thank you!
