### ISSUE TITLE
[Question] How to verify alter column data type?

### ISSUE THREAD

**Issue by nackjicholson** [sqitchers/sqitch#399]
Restatement from:
https://stackoverflow.com/questions/51903122/how-can-i-verify-an-alter-column-data-type-change-with-sqitch-postgresql

Any help would be much appreciated.

I am making the following `deploy` change. Changing the value of a `timestamp` column to `timestamptz`.

```sql
-- Alter the is_deleted flags to be timestamp with time zone
alter table source_meta.sources alter column is_deleted set data type timestamptz
      using
        is_deleted at time zone 'UTC';
alter table source_meta.series alter column is_deleted set data type timestamptz
      using
        is_deleted at time zone 'UTC';
```

How can I write a `verify` script that will error if the data type has not been changed?

**Comment by theory** [comment]
Your solution looks perfectly valid to me, @nackjicholson. I posted a slight alternative that yields a more informative error message.

**Comment by theory** [comment]
You might also be interested in subscribing to the [mail list](https://groups.google.com/d/forum/sqitch-users).
