### ISSUE TITLE
sqitch don't capture errors for: verify, deploy or revert when using mysql on a ssh tunnel

### ISSUE THREAD

**Issue by marcoarthur** [sqitchers/sqitch#401]
I have the following configuration:
MySQL running on a remote host. I setup a tunnel on 3306 localhost port to this remote host, using:

> ssh -L 3306:localhost:3306 root@database.myapp.dev -N

I was following sqitch tutorial for [mysql](https://metacpan.org/pod/sqitchtutorial-mysql) and noticed that sqitch can't capture any error
<pre>
Verifying flipr_test
  * appuser ................... ok
  * users ..................... ERROR 1054 (42S22) at line 5 in file: 'verify/users.sql': Unknown column 'nonexistente' in 'field list'
ok
  * insert_user ............... ok
  * change_pass @v1.0.0-dev1 .. ok
Verify successful
</pre>
On this I inserted a non existing column **nonexistente**
<pre>
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ cat verify/users.sql 
-- Verify flipr:users on mysql

BEGIN;

SELECT nickname, password, timestamp, nonexistente
  FROM users
 WHERE 0;

ROLLBACK;
</pre>

I then tried with sqlite engine and it follows that it shows me error as expected:
<pre>
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/simple$ sqitch verify db:sqlite:simple.db
Verifying db:sqlite:simple.db
  * people .. Error: near line 6: no such column: nonexistent
# Verify script "verify/people.sql" failed.
not ok

Verify Summary Report
---------------------
Changes: 1
Errors:  1
Verify failed
</pre>

Should this be due only I'm access mysql from  ssh a tunnel ?
Also my output for targets on mysql tutorial directory:

<pre>
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ sqitch target -v
flipr_test	db:mysql://admin@127.0.0.1/flipr_db_test
</pre>

**Comment by marcoarthur** [comment]
I'm running sqitch version:

> sqitch --version \#sqitch (App::Sqitch) 0.9997

**Comment by theory** [comment]
You need to make sure that whatever you're using for the `mysql` client that it exit with an error code other than `0` when there is an error. The Maria `mysql` client failed to do this, IIRC. I don't know how the SSH tunnel affects things, but make sure the error code propagates across the tunnel.

**Comment by marcoarthur** [comment]
I checked here that mysql client returns non zero code
<pre>
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ mysql -D flipr_db_test -u admin -p -h 127.0.0.1 < verify/users.sql 
Enter password: 
ERROR 1054 (42S22) at line 5: Unknown column 'nonexistente' in 'field list'
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ echo $?
1
</pre>
I'm using this client:
<pre>
$ mysql --version
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
</pre>
I also tried to setup a higher verbosity but it does not show anything, my sqitch.conf follows:
<pre>
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ cat sqitch.conf 
[core]
	engine = mysql
	# plan_file = sqitch.plan
	# top_dir = .
# [engine "mysql"]
	# target = db:mysql:
	# registry = sqitch
	# client = mysql
    verbosity = 3
    pager = less -R
[target "flipr_test"]
	uri = db:mysql://admin@127.0.0.1/flipr_db_test
[engine "mysql"]
	target = flipr_test
[deploy]
	verify = true
[rebase]
	verify = true
</pre>

**Comment by marcoarthur** [comment]
I'm using MariaDB client, hmm... I will see alternatives to it, and check it out

**Comment by marcoarthur** [comment]
I made a wrapper to mysql command line and could see the problem. Sqitch is constructing the follow command line:
<pre>
mysql --user admin --database flipr_db_test --host 127.0.0.1 --password=changed_my_secret --skip-pager --silent --skip-column-names --skip-line-numbers     --execute 'source verify/users.sql'
ERROR 1054 (42S22) at line 5 in file: 'verify/users.sql': Unknown column 'nonexistente' in 'field list'
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ echo $?
0
</pre>

And mysql command line utility returns wrongly zero status . If I take off the **--execute 'source verify/users.sql'** arg and use redirect to standard input, that gives me the non-zero status
<pre>
mysql --user admin --database flipr_db_test --host 127.0.0.1 --password=changed_my_secret --skip-pager  --skip-column-names --skip-line-numbers     --silent < verify/users.sql 
ERROR 1054 (42S22) at line 5: Unknown column 'nonexistente' in 'field list'
itaipu@ubatuba:~/tools/databases/tutorial/sqitch/flipr$ echo $?
1
</pre>

That seems a bug in mysql client for me :/ anyway, I'm thinking on how I could improve the shell wrapper to check on stderr and give a proper return value on errors, or use a redirect, instead of --execute argument.

**Comment by theory** [comment]
This bug has been in the Maria client for *years,* sadly. Don't know why it has never been fixed.
