### ISSUE TITLE
'Array must contain only scalars and other arrays' error during 'sqitch deploy' command

### ISSUE THREAD

**Issue by MikeAlexMartinez** [sqitchers/sqitch#407]
I run this command:

`sqitch deploy db:postgresql://<username>:<password>@<host>:<port>/<db>`

I get this error:

`Arrays must contain only scalars and other arrays at /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/DBI.pm line 1694.`

Is this anyone is able to help with? I'm running Ubuntu 18.04 and have Perl v5.26.1.
postgresql-client is already the newest version (10+190).
libdbd-pg-perl is already the newest version (3.7.0-1).
sqitch is already the newest version (0.9996-1).

**Comment by MikeAlexMartinez** [comment]
postgresql-client is already the newest version (10+190).
libdbd-pg-perl is already the newest version (3.7.0-1).
sqitch is already the newest version (0.9996-1).

**Comment by theory** [comment]
What does your `sqitch.plan` look like?

**Comment by MikeAlexMartinez** [comment]
`%syntax-version=1.0.0
%project=flipr
%uri=db:postgresql://<username>:<password>@<host>:<port>/<db>

appschema 2018-09-28T16:59:27Z <my name> <my-email@mail.com> # Add schema for all flipr objects`

I was working through the flipr postgres tutorial and encountered that error at the first sqitch deploy command

**Comment by MikeAlexMartinez** [comment]
The postgres instance I'm attempting to deploy to is an amazon RDS service. Not sure if that will affect it in any way.

**Comment by theory** [comment]
Oh quite possibly. The result of that line in the plan would be an empty array. Something like this:

``` sql
CREATE TABLE tryme (id int primary key, tags text[]);
INSERT INTO tryme (1, '{}');
```

I've never used RDS myself, though, so can't really say. Perhaps someone on the [mail list](
https://groups.google.com/forum/#!forum/sqitch-users) is familiar with it?

**Comment by MikeAlexMartinez** [comment]
Thanks for your help, I will post to the mailing list and try and figure something out. In the mean time I might just try running sqitch locally to get my head around the basics of sqitch. I can then can figure out how to integrate it with RDS as that is where we host our DBs.

**Comment by theory** [comment]
Easiest might be to spin up a quick Postgres cluster using [pgenv](/theory/pgenv) or a [docker image](https://hub.docker.com/_/postgres/).

**Comment by theory** [comment]
BTW, the latest version of Sqitch is v0.9997; v0998 will be out this week. I doubt this issue is changed, though.

**Comment by MikeAlexMartinez** [comment]
Cool, thanks for your recommendation (and thanks for all your work on sqitch and pgenv!).

**Comment by davehodg** [comment]
I consulted with a colleague and our conclusion was that it smells like a DBI.pm issue that you're provoking. Possibly 5.26-related which is known to have some smells. I'd post a bug to that.

Can you provoke it locally? There's no reason why it should be an RDS issue.

**Comment by MikeAlexMartinez** [comment]
Okay thanks for your feedback! I'll post a bug there and see what they come back with.

**Comment by theory** [comment]
Checking in, @MikeAlexMartinez have you been able to confirm whether it's an issue with the DBI and/or Perl 5.26?

**Comment by theory** [comment]
Hi, checking in again, @MikeAlexMartinez. Did you hear back from the bug report you posted for Perl 5.26?

**Comment by theory** [comment]
Closing, assuming was an issue with the DBI and/or Perl 5.26.
