### ISSUE TITLE
Add top-level -C option to switch current working directory

### ISSUE THREAD

**Issue by tsibley** [sqitchers/sqitch#411]
I'd like to keep multiple sqitch projects with their own `sqitch.conf` files as sibling directories in a single git repo and be able to run, for example, `sqitch -C project-a/ deploy …` and `sqitch -C project-b/ deploy …` instead of `(cd project-a/; sqitch deploy …)`. Both git and tar have `-C` options which have the effect of ~immediately changing the working directory when they start:

       -C <path>
           Run as if git was started in <path> instead of the current working
           directory. When multiple -C options are given, each subsequent
           non-absolute -C <path> is interpreted relative to the preceding -C
           <path>.

       -C, --directory=DIR
              Change  to DIR before performing any operations.  This option is
              order-sensitive, i.e. it affects all options that follow.

**Comment by theory** [comment]
Great idea, thanks!

**Comment by theory** [comment]
How does 55b95db look to you, @tsibley?

**Comment by tsibley** [comment]
Commit looks good to me! I haven't had a chance to test it but will sooner or later. Thanks!
