### ISSUE TITLE
Unimplemented localization in French

### ISSUE THREAD

**Issue by Ovid** [sqitchers/sqitch#412]
Just to make sure a change worked, I reverted the last change and redeployed it:

```
~/veure $ sqitch revert --to @HEAD^ -y && sqitch deploy
Reverting changes to blueprints/branch-office-fix-slug from veure_test
  - loot_table_items/scrap-metal .. ok
Déploiement des changements vers veure_test
  + loot_table_items/scrap-metal .. ok
```

Note that the deploy statement (`Déploiement des changements vers veure_test`) is in French (as I expect on my computer), but the revert is not.

**Comment by Ovid** [comment]
I have no idea how the localization is implemented, so I cannot supply a patch :(

**Comment by theory** [comment]
FWIW, the canonical interface for editing po files is [Emacs po-mode](https://www.gnu.org/software/gettext/manual/html_node/PO-Mode.html#PO-Mode). Want to makes up dates to the French translations? I expect to release v0.999 in the next couple weeks, so now's a good time!

**Comment by theory** [comment]
Hey @arhuman, is this something you might be able to give a little time to update? Thanks!

**Comment by theory** [comment]
Closing; l10n updates should just be handled via PRs.
