### ISSUE TITLE
Sqitch db setup tables for Oracle

### ISSUE THREAD

**Issue by imranlk2002** [sqitchers/sqitch#416]
It would be great if sqitch instial setup tables can be renamed to sqitch_<table_name> so that it does not conflict with the real tables. or is there any easy way to rename those?

Eg:
        CHANGES   -> SQITCH_CHANGES
	DEPENDENCIES -> SQITCH_DEPENDENCIES
	PROJECTS -> SQITCH_PROJECTS
	RELEASES  -> SQITCH_RELEASES 
	TAGS  -> SQITCH_TAGS  
	EVENTS  -> SQITCH_EVENTS 

Thanks
Imran

**Comment by theory** [comment]
Work started in #247, but was never finished. In Oracle, however, if you set the registry to a different schema, Sqitch will install its tables in that schema. No need to put them in the same schema as your business objects.

**Comment by imranlk2002** [comment]
Thanks. As you said I have done the following;

sqitch.conf

[core]
	engine = oracle
	# plan_file = sqitch.plan
	# top_dir = .
engine "oracle"
	target = db:oracle://scott_sqitch:scott_sqitch@/localhost:1521/xe.oracle.docker
	registry = scott_sqitch
	client = sqlplus.exe

As system user:
grant CREATE ANY INDEXTYPE,CREATE ANY INDEX ,comment any table,UNDER ANY TYPE , create any synonym ,CREATE ANY TYPE,CREATE ANY TABLE,drop any table to scott;

When i deploy 
>sqitch deploy db:oracle://scott:tiger@/localhost:1521/xe.oracle.docker

Now I get;

ORA-01031: insufficient privileges (DBD ERROR: error possibly near <*> indicator at char 998 in '
        SELECT * FROM (
            SELECT c.change_id
                 , c.script_hash
                 , c.change
                 , c.project
                 , c.note
                 , c.committer_name
                 , c.committer_email
                 , CAST(to_char(c.committed_at AT TIME ZONE 'UTC', '"year":YYYY:"month":MM:"day":DD') AS VARCHAR2(100 byte)) || CAST(to_char(c.committed_at AT TIME ZONE 'UTC', ':"hour":HH24:"minute":MI:"second":SS:"time_zone":"UTC"')  AS VARCHAR2(168 byte)) AS committed_at
                 , c.planner_name
                 , c.planner_email
                 , CAST(to_char(c.planned_at AT TIME ZONE 'UTC', '"year":YYYY:"month":MM:"day":DD') AS VARCHAR2(100 byte)) || CAST(to_char(c.planned_at AT TIME ZONE 'UTC', ':"hour":HH24:"minute":MI:"second":SS:"time_zone":"UTC"')  AS VARCHAR2(168 byte)) AS planned_at
                 , CAST(COLLECT(CAST(t.tag AS VARCHAR2(512))) AS sqitch_array) AS tags
              FROM changes   c
              LEFT JOIN <*>tags t ON c.change_id = t.change_id
             WHERE c.project = :p1
             GROUP BY c.change_id
                 , c.script_hash
                 , c.change
                 , c.project
                 , c.note
                 , c.committer_name
                 , c.committer_email
                 , c.committed_at
                 , c.planner_name
                 , c.planner_email
                 , c.planned_at
             ORDER BY c.committed_at DESC
        ) WHERE rownum = 1
    ')


It can't see LEFT JOIN <*>tags ;

Any idea?

**Comment by imranlk2002** [comment]
As a work around;
I have done the following

login as scott_sqitch and then 
    grant select on tags to scott;
    grant select on changes to scott;
    grant select on releases to scott;
    grant execute on sqitch_array to scott;

> sqitch deploy db:oracle://scott:tiger@/localhost:1521/xe.oracle.docker

Now getting;
Use of uninitialized value in numeric ne (!=) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1031.
Use of uninitialized value $oldver in numeric lt (<) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1066.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
Use of uninitialized value $oldver in numeric gt (>) at C:/Strawberry/perl/site/lib/App/Sqitch/Engine.pm line 1075.
  * From {old} to 1.0
old   1: CREATE TABLE &registry..releases (
new   1: CREATE TABLE scott_sqitch.releases (
CREATE TABLE scott_sqitch.releases (
                          *
ERROR at line 1:
ORA-00955: name is already used by an existing object

sqlplus.exe unexpectedly returned exit value 187

**Comment by theory** [comment]
Bah. What does this return when you run it?

``` sql
SELECT MAX(version) FROM releases
```

Seems like somehow your registry tables are out of whack.

**Comment by imranlk2002** [comment]
Here's the output;
SQL> show user;
USER is "SCOTT_SQITCH"
SQL> select table_name from user_tables;
TABLE_NAME
--------------------------------------------------------------------------------
RELEASES
PROJECTS
CHANGES
TAGS
DEPENDENCIES
SQL> SELECT version FROM releases;
no rows selected
SQL> SELECT MAX(version) FROM releases;
MAX(VERSION)
------------
SQL> select * from PROJECTS;
no rows selected
SQL> select * from CHANGES;
no rows selected
SQL> select * from TAGS;
no rows selected
SQL> select * from DEPENDENCIES;
no rows selected

sqitch --version
sqitch (App::Sqitch) 0.9998

**Comment by theory** [comment]
Try inserting a row into the `releases` table:

``` sql
INSERT INTO releases VALUES(0.0, current_timestamp, 'imranlk2002', 'your_email@domain.com');
```

Then see if the upgrades run properly.
