### ISSUE TITLE
brew install fails due to cpantesters.org being blocked by OpenDNS

### ISSUE THREAD

**Issue by mcallaway** [sqitchers/sqitch#418]
Trying to brew install sqitch I see:

    > brew install sqitch --with-sqlite-support
    ==> Installing sqitch from sqitchers/sqitch
    ==> Downloading http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9998.tar.gz
    
    curl: (22) The requested URL returned error: 403 Forbidden
    Error: An exception occurred within a child process:
      DownloadError: Failed to download resource "sqitch"
    Download failed: http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9998.tar.gz

Visiting http://cpan.cpantesters.org fails as OpenDNS flags it as possible malware.

Visiting https://cpan.cpantesters.org reveals an invalid SSL certificate.

I am able to download App-Sqitch via cpan.org. Perhaps that site should be used instead of cpantesters.org?

**Comment by mcallaway** [comment]
> brew edit sqitch
    Editing /usr/local/Homebrew/Library/Taps/sqitchers/homebrew-sqitch/Formula/sqitch.rb

Change the URL to http://cpan.org/... and it proceeds.

**Comment by theory** [comment]
And now port 443 doesn't respond at all. @preaction, did something change?
