### ISSUE TITLE
Attempt to bless into a reference at .../lib/perl5/App/Sqitch.pm line 325.

### ISSUE THREAD

**Issue by tbug** [sqitchers/sqitch#428]
Just upgraded sqitch via brew.
I'm at ce8c93e

Calling sqitch with no arguments:
```
Attempt to bless into a reference at <brew prefix>/lib/perl5/App/Sqitch.pm line 325.
```

**Comment by arcaartem** [comment]
@theory As of today, I received the same error message when calling with no arguments:

`Attempt to bless into a reference at /usr/local/Cellar/sqitch/0.9999/bin/../lib/perl5/App/Sqitch.pm line 325.`

Latest version (0.9999)

**Comment by theory** [comment]
Well yeah, the fix hasn't been released yet. Check out v1.0.0 tomorrow!

**Comment by arcaartem** [comment]
doh, missed the release tag 🤦‍♂

**Comment by pyramation** [comment]
still happens when you do `sudo apt install sqitch` on ubuntu 20.04

**Comment by theory** [comment]
What version is on ubuntu, @pyramation?

**Comment by xandermathews** [comment]
As I appear to be in the same boat as Pyramation:

As of a fresh Ubuntu 20.04 LTS created today, after updating / upgrading everything:

sqitch version is `sqitch (App::Sqitch) 0.9999`

Given the release tag, sounds like "leave closed" to me.

**Comment by theory** [comment]
Sounds like Ubuntu needs to update its apt package.

**Comment by pyramation** [comment]
Sorry about the delay! Here was my fix just incase somebody desperately needs things working on Ubuntu 20.04

## workaround

download the distribution tar gz https://metacpan.org/release/App-Sqitch

```
cpan
```

in cpan cli, write and hit enter

```
install Module::Build
```

also in cpan cli you may install additional Netmask module, long compilation with many times need hit Y key

```
install Net::Netmask
```

reboot...

```
perl Build.PL 
 ./Build installdeps
 ./Build 
 ./Build install
```

get `cpanm` 

```
curl -L https://cpanmin.us | perl - --sudo App::cpanminus
cpanm Menlo::CLI::Compat
```

get pg packages

```
sudo apt-get install libpq-dev libdbd-pg-perl
```

Finalize the build!

```
./Build bundle --with postgres
```
