### ISSUE TITLE
Sqitch not creating registy tables on first sqitch deploy

### ISSUE THREAD

**Issue by caseylargent** [sqitchers/sqitch#429]
I am currently trying to connect to Snowflake through sqitch deploy and perform a migration test. Currently, when attempting to perform the sqitch deploy, the preliminary registry tables are not created. it is assumed they are already there. 

Is this something that needs to be made on the Snowflake side before performing migrations? 

![snowflake_sqitch_errors](https://user-images.githubusercontent.com/17444278/52503542-7d1d8780-2bab-11e9-8a24-9b664cd6e46d.png)

**Comment by theory** [comment]
Can you provide your connection info? Specifically, what is your target URI, and does it include a warehouse name that exists?

**Comment by caseylargent** [comment]
Hi there. I can't give you the exact URL (for security reasons), but here is the basic connection string I'm trying.

"db:snowflake://<ACCOUNT_NAME>.snowflakecomputing.com/<EXISTING_DB_NAME>?Driver=SnowflakeDSIIDriver;authenticator=externalbrowser;warehouse=<WAREHOUSE_NAME>"

**Comment by caseylargent** [comment]
The spaces around snowflake are to prevent the emoji from showing up :)

**Comment by caseylargent** [comment]
![chrome_xtihw0frt8](https://user-images.githubusercontent.com/17444278/52571176-abcd7500-2dda-11e9-8014-dd1f67e823c5.png)

**Comment by caseylargent** [comment]
If you could help me by providing me the ability to have the same level of output as I did before, that would be great! For some reason, it doesn't have the same level of output as before

**Comment by theory** [comment]
What "level of output" do you mean?

That 403 forbidden error seems to be the issue. Note that Sqitch connects via ODBC, and then it runs scripts via the SnowSQL client -- including the creation of the registry. Could it be that the external browser authentication thing isn't working somehow, or that the user account is forbidden from creating objects? For example is it unable to create the registry schema?

[Here's the script](/sqitchers/sqitch/blob/master/lib/App/Sqitch/Engine/snowflake.sql) that creates the registry. The `&registry` variable is set to "sqitch". If your account does not have the ability to create a schema, perhaps you need to create a registry schema manually in advance? I'm kind of guessing here.

It does look like it's choking on that script. To see exactly how it's executing it, apply this patch and run it again:

```
--- a/lib/App/Sqitch/Engine/snowflake.pm
+++ b/lib/App/Sqitch/Engine/snowflake.pm
@@ -428,6 +428,7 @@ sub run_handle {
 
 sub _run {
     my $self   = shift;
+    $sqitch->emit_literal( join ' ', $self->snowsql, @_);
     my $sqitch = $self->sqitch;
     my $pass   = $self->password or
         # Use capture and emit instead of _run to avoid a wayward newline in
```

**Comment by caseylargent** [comment]
I will try with a basic account and let you know. Thanks

**Comment by theory** [comment]
BTW, if you have to do some sort of external auth for Snowflake, you'll rapidly find it annoying, because Sqitch connects via ODBC, and then for each script it executes. At my work, we require 2FA, but I got our admins to turn it off while doing development, because otherwise it would prompt me to authenticate multiple times every time I ran a deploy. Ideally, for Sqitch use, you'll probably want some sort of very closely controlled user and perhaps limit the IPs it can connect from. I think you'll find the alternative maddening.

**Comment by caseylargent** [comment]
Yep this was just for initial testing. This will be apart of an automation process with a service account

**Comment by caseylargent** [comment]
So I used an user account, called SQITCH_USER and gave it a role that is able to perform all CRUD operations. For some reason, the database isn't getting set properly with the DB URI format that was provided.

![pwsh_3kfzhxufgy](https://user-images.githubusercontent.com/17444278/52578479-e559ac80-2de9-11e9-889d-ad7192b0461b.png)

**Comment by caseylargent** [comment]
I think I might know the problem now. 

When looking at the log file in ~/.snowsql (after setting it to DEBUG level) it seems that the entire domain name isn't getting set properly. I'm now getting an error saying "Failed to connect to DB. Verify that the account name is correct: foo" 

When it should be foo.us-east-1.snowflakecomputing.com

(assume foo is my not full account name)

**Comment by caseylargent** [comment]
It seems to be an issue with the regex in the has account thing (sorry I'm not familiar with perl) at line 123

```
has account => (
    is      => 'ro',
    isa     => Str,
    lazy    => 1,
    default => sub {
        my $self = shift;
        if (my $host = $self->uri->host) {
            # <account_name>.<region_id>.snowflakecomputing.com
*************************$host =~ s/[.].+//;*************************
            return $host;
        }
        return $ENV{SNOWSQL_ACCOUNT} || $self->_snowcfg->{accountname} || hurl engine => __(
            'Cannot determine Snowflake account name'
        );
    },
);
```

Instead of returning foo.us-east-1 (which is what snowsql expects), it just returns foo

**Comment by theory** [comment]
It should be retaining the region in the `_host` method. I don't see the region in the connection URI you posted above, which was:

```
db:snowflake://<ACCOUNT_NAME>.snowflakecomputing.com/<EXISTING_DB_NAME>?Driver=SnowflakeDSIIDriver;authenticator=externalbrowser;warehouse=<EXISTING_WAREHOUSE_NAME>
```

Do you need to add it to this URI?

**Comment by caseylargent** [comment]
I think the main underlying issue was with the way that my .snowsql/config file was setup, as the account name had the region in there as well, probably causing some bad URIs to be formed. Thank you for your help, but it was mainly user error on my part 👍

**Comment by theory** [comment]
Great, glad you figured it out!

**Comment by sfc-gh-lramamurthy** [comment]
@theory I tried to run the script manually  and then run deploy and I get the following error
Use of uninitialized value in numeric ne (!=) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1098.
Use of uninitialized value $oldver in numeric lt (<) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1133.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Use of uninitialized value $oldver in numeric gt (>) at /usr/local/Cellar/sqitch/v1.2.1/bin/../lib/perl5/App/Sqitch/Engine.pm line 1142.
Upgrading the Sqitch registry from {old} to 1.1
  * From {old} to 1.0
250001 (08001): Failed to connect to DB:
Can you help me with this

**Comment by theory** [comment]
Hi @sfc-gh-lramamurthy. What database engine are you using? What version? What version of Perl and the database driver? 

```
250001 (08001): Failed to connect to DB:
```

Here it looks like there is a database connection failure. How are you running Sqitch, with what options and what target?
