### ISSUE TITLE
Windows: DBD::Oracle 1.23 required to manage Oracle

### ISSUE THREAD

**Issue by nfantis** [sqitchers/sqitch#430]
Hello,

I used Sqitch at my previous job and loved it, so now I'm trying to introduce it in a Windows/Oracle environment.  I downgraded to 0.9998 due to bug #428.  

I receive an error `DBD::Oracle 1.23 required to manage Oracle`.  DBD::Oracle version 1.76 is installed.  Is it required to downgrade to DBD::Oracle 1.23 or is there possibly something else going on? I reviewed #206 and everything suggested there seems to be in place.  Thanks in advance!

**Sqitch version**
```
C:\> sqitch --version
sqitch (App::Sqitch) 0.9998
```

**Sqitch Config**
```
C:\oracle-ci\database\migrations>sqitch config --list
core.engine=oracle
engine.oracle.client=C:\oracle-client-18-3\
```

**Sqitch deploy**
```
C:\> sqitch deploy --target=db:oracle://tssadmin:oracle@/localdb
DBD::Oracle 1.23 required to manage Oracle
```

**DBD::Oracle version**
```
C:\> cpan -D DBD::Oracle
Loading internal logger. Log::Log4perl recommended for better logging
CPAN: CPAN::SQLite loaded ok (v0.212)
Database was generated on Fri, 15 Feb 2019 16:22:56 GMT

DBD::Oracle
-------------------------------------------------------------------------
        CPAN: Module::CoreList loaded ok (v5.20181130)
(no description)
        Z/ZA/ZARQUON/DBD-Oracle-1.76.tar.gz
        C:\Strawberry\perl\vendor\lib\DBD\Oracle.pm
        Installed: 1.76
        CPAN:      1.76  up to date
        Kieren Diment (ZARQUON)
        diment@gmail.com
```

**tnsnames.ora**
```
localdb =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orclpdb1)
    )
  )
```

**SQL*Plus Connection**
```
C:\oracle-client-18-3\> sqlplus tssadmin@localdb

SQL*Plus: Release 18.0.0.0.0 - Production on Fri Feb 15 12:02:40 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Enter password:

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL>
```

**Comment by theory** [comment]
DBD::Oracle isn't loading. What does this output?

```
perl -MDBD::Oracle -E1
```

**Comment by nfantis** [comment]
Thanks for the reply.  Nothing returned:

```
C:\> perl -MDBD::Oracle -E1

C:\>
```

**Comment by nfantis** [comment]
Closing, was able to get to the bottom of this.

When I downloaded the Oracle instant client, I did not include the SDK files.  Once I downloaded those and put them in the Instant Client directory, everything worked as expected.

![image](https://user-images.githubusercontent.com/22967457/53049178-7cff7080-3464-11e9-8bae-6c2aa34259bb.png)

Thanks for your help!

**Comment by theory** [comment]
Glad you figured it out. Database clients can be a PITA.
