### ISSUE TITLE
Database changes parametrization

### ISSUE THREAD

**Issue by przemekd** [sqitchers/sqitch#432]
Hey, I didn't find a way to parametrize a change file. That's necessary when creating an object in a DB that needs to be created with a secret value.

E.g. in Snowflake when creating an external stage using Amazon S3 one should pass credentials if a bucket is protected/private.

Is something like this below possible?
```
CREATE STAGE my_stage URL = 's3://bucket/stage' CREDENTIALS =(AWS_KEY_ID = ${aws_key_id},
AWS_SECRET_KEY = ${aws_secret_key});

**Comment by theory** [comment]
On Thu, Feb 21, 2019, at 5:44 AM, przemekd wrote:

> Hey, I didn't find a way to parametrize a change file. That's necessary 
> when creating an object in a DB that needs to be created with a secret 
> value.

You want to use variables.

  https://github.com/sqitchers/sqitch/blob/master/lib/sqitch-configuration.pod#user-content-variables

HTH,

David

**Comment by przemekd** [comment]
Thanks, I didn't notice that option. It works flawlessly.
