### ISSUE TITLE
How is `change_id` calculated?

### ISSUE THREAD

**Issue by jnj16180340** [sqitchers/sqitch#434]
What parameters does `change_id` depend on? I'm trying to figure out the source of a nondeterministic scripted plan generation, and my poor Perl fluency is making it tricky to figure out on my own.

I *have* figured out
- `script_hash` is sha1 of rendered plan file
- `change_id` is not a DB-generated random primary key

**Comment by jhannah** [comment]
I could be wrong but [it looks like change_id is a SHA of the deploy file](https://github.com/sqitchers/sqitch/blob/develop/lib/App/Sqitch/Plan/Change.pm#L189-L196) as generated at the point in time of the change.

**Comment by jnj16180340** [comment]
https://github.com/sqitchers/sqitch/blob/ef4bb33a787b9b95cd0e9e8f266dfa4cec237450/lib/App/Sqitch/Plan/Change.pm#L133

https://github.com/sqitchers/sqitch/blob/ef4bb33a787b9b95cd0e9e8f266dfa4cec237450/lib/App/Sqitch/Plan/Change.pm#L111

Hmm and not a hash of change name + user + timestamp etc.?

**Comment by theory** [comment]
You can see the text that gets hashed using the [`show` command](https://github.com/sqitchers/sqitch/blob/develop/lib/sqitch-show.pod):

```
sqitch show change $changename`
```
