### ISSUE TITLE
Sqitch revert fails to revert log-only changes

### ISSUE THREAD

**Issue by nkvavle** [sqitchers/sqitch#438]
After performing a sqitch deploy with the "--log-only" flag, performing a sqitch revert of those changes yields output indicating that there are no changes to revert (as expected). However, the sqitch tags laid down by the --log-only flag in the sqitch.tags table are not removed. 

This is using sqitch version 0.9995.

**Comment by theory** [comment]
Okay, having a little trouble following this. If you deploy with `--log-only`, when you revert, it should actually revert. An example:

    > md trylog
    > cd trylog
    > sqitch init --engine sqlite trylog
    Created sqitch.conf
    Created sqitch.plan
    Created deploy/
    Created revert/
    Created verify/

    > sqitch add foo -m foo 
    Created deploy/foo.sql
    Created revert/foo.sql
    Created verify/foo.sql
    Added "foo" to sqitch.plan

    > sqitch add bar -m bar 
    Created deploy/bar.sql
    Created revert/bar.sql
    Created verify/bar.sql
    Added "bar" to sqitch.plan

    > sqitch tag foo -m Foo
    Tagged "bar" with @foo in sqitch.plan

Now we have a plan with two changes and a tag. Let's deploy it with `--log-only`:

    > sqitch deploy --log-only db:sqlite:log.db           
    Adding registry tables to db:sqlite:sqitch.db
    Deploying changes to db:sqlite:log.db
      + foo ....... ok
      + bar @foo .. ok

Have a look at the tags table:

    > sqlite3 sqitch.db 'SELECT * FROM tags'
    tag_id                                    tag         project     change_id                                 note        committed_at             committer_name    committer_email             planned_at           planner_name      planner_email             
    ----------------------------------------  ----------  ----------  ----------------------------------------  ----------  -----------------------  ----------------  --------------------------  -------------------  ----------------  --------------------------
    fad7e1f32d524be37b5b5b9e4855c3df584e6240  @foo        trylog      f9c151911685240b7e521e9407ead8e333b11c09  Foo         2019-03-27 18:22:38.402  David E. Wheeler  david.wheeler@iovation.com  2019-03-27 18:16:18  David E. Wheeler  david.wheeler@iovation.com

As expected, right? Now when we revert, it reverts:

    > sqitch revert db:sqlite:log.db
    Revert all changes from db:sqlite:log.db? [Yes] y
      - bar @foo .. ok
      - foo ....... ok

Note: this succeeds even though I didn't use `--log-only` because these are just dummy changes; there is no actual SQL in the revert or deploy scripts. Anyway, now the tags table is empty:

    > sqlite3 sqitch.db 'SELECT * FROM tags'

Is this different than what you expect, @nkvavle?

**Comment by nkvavle** [comment]
I apologize for the long response, I believe this is not actually a bug and just my own misuse/misunderstanding of sqitch. 

My understanding now is that when doing a ```sqitch deploy --log-only``` this is reversed (the tags are removed) when running ```sqitch revert --log-only```
