### ISSUE TITLE
Snowflake - Support for Public/Private Key Pair Authentication

### ISSUE THREAD

**Issue by caseylargent** [sqitchers/sqitch#441]
Currently, when parsing the ~/.snowsql/config file when connecting to Snowflake via Sqitch, it only supports username and password authentication. Snowflake supports key based authentication, which is more secure and allows for other services to perform rotation.

- https://docs.snowflake.net/manuals/user-guide/snowsql-start.html#using-key-pair-authentication

When adding the requisite private_key_path entry into ~/.snowsql/config, it errors out with this.

```
Error parsing C:\Documents and Settings\larcas01\.snowsql\config at line 15, position 0.
Bad line was: 'private_key_path = C:\path\to\key_file.pkcs8'
```

There should be an option within the snowflake sqitch engine to use private key authentication

**Comment by caseylargent** [comment]
Interestingly enough, I thought this was a non-issue because I was able to authenticate without a password using the authenticator = externalbrowser and I received no such issue. I did have to "authenticate" everytime but it worked without any special configuration.

**Comment by theory** [comment]
It's returning that error because the SnowSQL config file format is not super well defined. Sqitch uses a Git configuration parser, but SnowSQL's config, while similar, might well have differences that aren't supported by the Git config format. In this case, I'll bet it's because the backslashes confuse it. Try putting the path in double-quotes (as [noted here](http://git.661346.n2.nabble.com/Escape-character-for-gitconfig-td7103808.html)).

Not that that will solve the key-based auth issue, but at least let's see if the parsing issue can be dealt with.

**Comment by caseylargent** [comment]
That worked, but now I am getting this error when attempting to deploy

[Snowflake][DSI] (20032) Required setting 'PWD' is not present in the connection settings. (SQL-28000)

**Comment by theory** [comment]
Huh. That's a snowflake error, not a Sqitch error. Have you confirmed that the key pair works when you use SnowSQL manually? Make sure that works before you have Sqitch use it.

Not that that will let Sqitch connect via ODBC, but it's a start.

**Comment by caseylargent** [comment]
Yes I am able to connect using snowsql. Once I put a password within the .snowsql/config, it works fine.

**Comment by caseylargent** [comment]
I am trying this on Linux now, because the Windows ODBC Driver Manager has issues with the PWD field, according to Snowflake.

_In Windows, the ODBC driver displays a Password field in the Data Source Administration tool; however, the driver does not store any values entered in the field. Instead, the driver requires login credentials to be provided at connection time.

If the connecting application does not provide the required credentials, the driver interactively prompts for the information._

**Comment by theory** [comment]
Well, that won't matter if Sqitch passes the credential it reads from the configuration file off to ODBC; it hasn't much use for the DS admin interface. We'll need to see the docs for key pair authentication with SnowSQL and ODBC to figure out how to make it work.

**Comment by caseylargent** [comment]
It seems that these settings need to be included within the ODBC driver (.odbc.ini)

AUTHENTICATOR = SNOWFLAKE_JWT:
--
  | Specifies to authenticate the Snowflake connection using keypair-based authentication with JSON Web Token (JWT).

  | Optional. Specifies the length of time Snowflake waits to receive the JWT (in seconds) before timing out. If that happens, authentication fails and the driver returns an Invalid JWT token error. To resolve repeated occurrences of the error, increase the parameter value.Default:30 | 30
30

  | Specifies the local path to the private key file you created (i.e. rsa_key.p8).

  | Specifies the passcode to decode the private key file.

**Comment by theory** [comment]
Have you tried adding the appropriate params to the connection URI? IOW:

    db:snowflake://someacct.snowflakecomputing.com/dbname?Driver=SnowflakeDSIIDriver;warehouse=COMPUTE_WH;authenticator=SNOWFLAKE_JWT

Sqitch should pass the params to the DBI connection.

**Comment by caseylargent** [comment]
I was able to connect!!! But I had to pass everything via the connection string (probably because I don't have my ODBC DSN entry set up properly). But now on initial connect, I'm running into this issue.

uri = "db:snowflake://ACCT_NAME.snowflakecomputing.com/SQITCH_DEMO?Driver=SnowflakeDSIIDriver;warehouse=QUERY_S;authenticator=SNOWFLAKE_JWT;UID=TEST_USER;PRIV_KEY_FILE=PATH_TO_PRIV_KEY;PRIV_KEY_FILE_PWD=PASSWORD"

SQL compilation error:
Object 'CHANGES' does not exist. (SQL-42S02)

**Comment by caseylargent** [comment]
It doesn't seem to like using the ~/.snowsql/config properties for this purpose and instead uses the connection string properties in order to connect with the private key

**Comment by theory** [comment]
Awesome. Can you post an example? I'd like to mention it somewhere in the docs.

**Comment by caseylargent** [comment]
How to use Sqitch to connect with Private Key
- Follow the instructions from https://docs.snowflake.net/manuals/user-guide/snowsql-start.html#using-key-pair-authentication in order to setup the keypair. Verify that the key pair works via snowsql
    - in ~/.snowsql/config, add the corresponding username that the public key is associated with and add this field
    `private_key_path = "path/to/private/key/file.p8"`

In your sqitch.conf or from the command line, your connection string should look as follows

"db:snowflake://{ACCOUNT_NAME}.snowflakecomputing.com/DB?Driver=SnowflakeDSIIDriver;warehouse=COMPUTE_WH;authenticator=SNOWFLAKE_JWT;UID=USERNAME;PRIV_KEY_FILE=path/to/encrypted/private_key.p8;PRIV_KEY_FILE_PWD=PWD_USED_TO_DECRYPT_PRIVATE_KEY"

**Comment by theory** [comment]
Does it work to put the username ahead of the domain, e.g.,

```
"db:snowflake://USERNAME@{ACCOUNT_NAME}.snowflakecomputing.com/DB?Driver=SnowflakeDSIIDriver;warehouse=COMPUTE_WH;authenticator=SNOWFLAKE_JWT;PRIV_KEY_FILE=path/to/encrypted/private_key.p8;PRIV_KEY_FILE_PWD=PWD_USED_TO_DECRYPT_PRIVATE_KEY"
```

Also, with that stuff in the URI, do you need it in the config file, as well? I'm guessing yes, in order for SnowSQL to find it, but just want to be sure.

**Comment by caseylargent** [comment]
Yes you do, and you need to set an environment variable in order to actually decrypt the private key file, as mentioned above

**Comment by caseylargent** [comment]
and if you put the USERNAME in front of the ACCOUNT_NAME, it doesn't work and fails with this error.

[Snowflake][DSI] (20032) Required setting 'UID' is not present in the connection settings. (SQL-28000)

**Comment by theory** [comment]
Huh, okay. Thanks.

**Comment by theory** [comment]
Does it work with the query params lowercased?

**Comment by caseylargent** [comment]
Yes, except it's required that the authenticator=SNOWFLAKE_JWT be capitalized as per Snowflake

**Comment by theory** [comment]
Right.

**Comment by theory** [comment]
How does 0483451 look, @caseylargent?

**Comment by theory** [comment]
PR #445
