### ISSUE TITLE
Snowflake - Hanging Registry Table Deployment

### ISSUE THREAD

**Issue by caseylargent** [sqitchers/sqitch#444]
When attempting to do the initial deployment with the creation of the registry tables, it hangs and doesn't finish. When looking at the ODBC log, this is where it left off. 

[sqitch_snowflake_log.txt](https://github.com/sqitchers/sqitch/files/3019982/sqitch_snowflake_log.txt)

When looking at my Snowflake History, this is the last query that was executed. 

![image](https://user-images.githubusercontent.com/17444278/55190063-2d9c1680-516d-11e9-8a05-90b208f38e06.png)

I applied https://github.com/sqitchers/sqitch/commit/f363a323c4b083348ccfa91a3b84159b1c999f69 recently in order to even connect.

**Comment by theory** [comment]
Did f363a32 fix the issue for you, then?

**Comment by caseylargent** [comment]
This was related to not having my ~/.snowsql/config done properly for the private key authentication, specifically not having the password set in the SNOWSQL_PRIVATE_KEY_PASSPHRASE environment variable before running any sqitch commands.

**Comment by theory** [comment]
Ah, okay. I think I need to document SNOWSQL_PRIVATE_KEY_PASSPHRASE, too.

**Comment by caseylargent** [comment]
Yep. But the Table change was necessary in order to connect. If this bug fix could go in the next release as soon as possible, that would be great.

**Comment by theory** [comment]
Table change?

**Comment by caseylargent** [comment]
Sorry I meant the error code for the table that was fixed in f363a32

**Comment by caseylargent** [comment]
That was necessary in order to run a successful deployment

**Comment by theory** [comment]
Yes, that will be in the next release, as will the docs added in #445.

**Comment by caseylargent** [comment]
Cool, the sooner the better! Thank you 👍
