### ISSUE TITLE
Unable to define target variable

### ISSUE THREAD

**Issue by maximejanssens** [sqitchers/sqitch#454]
Hello, I'm currently trying to pass a variable for a target.
sqitch.conf file (initial state):
>[core]
	engine = snowflake
[target "Test_Stable_TSTEV3"]
>	uri = "db:snowflake://****"
 
I used this command: 
>sqitch target alter Test_Stable_TSTEV3 --set database='TSTEV3'
sqitch.conf file:
[core]
	engine = snowflake
[target "Test_Stable_TSTEV3"]
>	uri = "db:snowflake://****"
[target "Test_Stable_TSTEV3.variables"]
>	database = "TSTEV3"

However, when I try deploying:
>sqitch deploy Test_Stable_TSTEV3
Deploying changes to Test_Stable_TSTEV3
>  + MOVESTATEMENT ................... Variable database is not defined

For some reason it's not recognising the variable:
>sqitch target show Test_Stable_TSTEV3
* Test_Stable_TSTEV3
    URI:           db:snowflake:***
    Registry:      sqitch
    Client:        /var/snowsql
    Top Directory: .
    Plan File:     sqitch.plan
    Extension:     sql
    Script Directories:
      Deploy:      deploy
      Revert:      revert
      Verify:      verify
    Reworked Script Directories:
      Reworked:    .
      Deploy:      deploy
      Revert:      revert
      Verify:      verify
    No Variables

When I define the variable on command level it does pass the variable:
>sqitch deploy Test_Stable_TSTEV3 --set database='TSTEV3'

Now the variable 'database' in the deploy/revert and verify scripts is replaced by TSTEV3 and everything is working fine, but I'd prefer defining it beforehand in the sqitch.conf file.
Could anybody tell me what I'm doing wrong? I've also tried creating the target and defining the variables at the same time with 'sqitch target add $target --set $key=$val -s $key2=$val2' as described in the documentation but it gives the same result.

**Comment by maximejanssens** [comment]
Update: appearently this issue occurs when you have a capital letter in the targetname. 
If I use test_stable_tstev3 it does recognise the variable
command: sqitch target show test_stable_tstev3
>test_stable_tstev3
    URI:           db:snowflake://MJAS:hgzEye92Q7I@attentia.west-europe.azure.snowflakecomputing.com/DISEV3?Driver=Snowflake;warehouse=LOAD_WH
    Registry:      sqitch
    Client:        /var/snowsql
    Top Directory: .
    Plan File:     sqitch.plan
    Extension:     sql
    Script Directories:
      Deploy:      deploy
      Revert:      revert
      Verify:      verify
    Reworked Script Directories:
      Reworked:    .
      Deploy:      deploy
      Revert:      revert
      Verify:      verify
Negative repeat count does nothing at /bin/../lib/perl5/App/Sqitch/Command/target.pm line 218.
    Variables:
Negative repeat count does nothing at /bin/../lib/perl5/App/Sqitch/Command/target.pm line 221.
  database:TSTEV3
>
Still getting a weird notification 
'Negative repeat count does nothing at /bin/../lib/perl5/App/Sqitch/Command/target.pm line 218.'
But it does seem to solve the issue.

**Comment by theory** [comment]
I've replicated that it can't find the variables, but not finding them lowercase. What's the command you're running in that last example? And does the target still have a name with uppercase characters, or did you change it, too? IOW, what's in your `sqitch.conf` file?

**Comment by theory** [comment]
Never mind, I figured it out. Fix forthcoming.

**Comment by maximejanssens** [comment]
Wasn't on my computer for the weekend so couldn't reply.

Thanks for the fix :)
