### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by franciscohanna92** [sqitchers/sqitch#458]
I'm running Sqitch from the docker image provided in Docker Hub, following the steps provided there. It seems to be working fine.

I'm goint trought the first part of the docs and I already have a change created ready to be deployed. But, when I try to deploy the changes, I get the following error:

> Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory") 

This is `sqitch.conf`:
```
[core]
	engine = mysql
	# plan_file = sqitch.plan
	# top_dir = .
# [engine "mysql"]
	# target = db:mysql:
	# registry = sqitch
	# client = mysql
[engine "mysql"]
	client = mysql
	target = db:mysql:sqitch_test
[user]
	name = Francisco Hanna
	email = franciscohanna92@gmail.com
[target "sqitch_test"]
	uri = db:mysql://root@/sqitch_test
```

I have already check:
1. From a terminal `mysql -u root` works fine.
2. The `sqitch_test` schema is already created.

I'm running mysql server v5.7.26
This is the info from `service mysql status`

> ● mysql.service - MySQL Community Server
>    Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sun 2019-05-12 17:18:33 MST; 50min ago
>   Process: 1394 ExecStart=/usr/sbin/mysqld --daemonize --pid-file=/run/mysqld/mysqld.pid (code=exited, status=0/SUCCESS)
>   Process: 1111 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
>  Main PID: 1396 (mysqld)
>     Tasks: 30 (limit: 4915)
>    CGroup: /system.slice/mysql.service
>            └─1396 /usr/sbin/mysqld --daemonize --pid-file=/run/mysqld/mysqld.pid

**Comment by theory** [comment]
Are you on a Mac with MySQL running on that Mac? IF so, try setting the MySQL hostname to host.docker.internal.

```
sqitch engine alter mysql --target db:mysql:://host.docker.internal/sqitch_test
```

Then try again. See [this StackOverflow answer](https://stackoverflow.com/a/43541732/79202) for details.

**Comment by franciscohanna92** [comment]
No, i'm on Ubuntu 18.04.2 LTS. But I tried anyway. Still the same error.

I think it's looking for the mysqld socket in `/var/run/mysqld/`. But in my case, `mysqld.sock` it's located in `/run/mysqld/`. Or I'm missing something?

**Comment by theory** [comment]
It's looking inside the docker container, where MySQL isn't running. You'll need to enable your MySQL server on TCP/IP and point Sqitch inside the container to the IP of your host.

**Comment by franciscohanna92** [comment]
Any ideas on how to accomplish that? I'm using the bash script that it's provided in the [docker hub page for squitch](https://hub.docker.com/r/sqitch/sqitch/) to interact with the sqitch container.

**Comment by theory** [comment]
[This SO answer](https://stackoverflow.com/questions/41897077/connect-to-mysql-on-localhost-from-docker-container) might help. If you need to change how the Docker container is started, you'll need to edit the shell script.

**Comment by franciscohanna92** [comment]
Yay, got it working. Here's what I did:

Since the container was complaining about not founding `/var/run/mysqld/mysqld.sock`, what I did was to mount my `/run/mysqld` folder (which has the socket file in localhost) in `/var/run/mysqld` inside the container, and voilá.

Should I add this issue in https://github.com/sqitchers/docker-sqitch?

**Comment by theory** [comment]
Hrm. Should probably add something to the docs for the container on how to connect outside your database. Sure, go ahead and put that info in an issue there, and I'll think about where to put it. Thanks!
