### ISSUE TITLE
Possible To Get 1.0.0 Beta For Sqitch/Sqitch docker?

### ISSUE THREAD

**Issue by mcurtis125** [sqitchers/sqitch#462]
Hey guys, was wondering if you could upload a .tgz build of sqitch 1.0.0 to the location: https://www.cpan.org/authors/id/D/DW/DWHEELER/App-Sqitch-$VERSION.tar.gz . This would allow me to continue to rely on the sqitch/sqitch docker image rather than having to rebuild that docker image pointing at a local build of sqitch. 

This helps me build out snowflake infrastructure as I am blocked by: 
https://github.com/sqitchers/sqitch/issues/439

Docker image reference:
https://github.com/sqitchers/docker-sqitch/blob/master/Dockerfile

**Comment by mcurtis125** [comment]
To give you guys some more context on what I'm working on...

I've build out some scripting tools that allow command line interaction with multiple snowflake account sources via sqitch. Those commands are executed inside of a custom docker image that relies on https://github.com/sqitchers/docker-sqitch/blob/master/Dockerfile.

**Comment by theory** [comment]
I added [this workaround](/sqitchers/docker-sqitch/commit/f31b349), so if you pull that repo, you should be good to go.

**Comment by mcurtis125** [comment]
You are a life saver @theory! Thank you!

**Comment by theory** [comment]
I take it that the fix worked for you, then, @mcurtis125?

**Comment by mcurtis125** [comment]
Yes it did.
