### ISSUE TITLE
Failed test 'DB URI should be filled in' at t/snowflake.t line 81 

### ISSUE THREAD

**Issue by RachetRalph** [sqitchers/sqitch#463]
The error i get when I try to install Sqitch 
-------------------
`t/rebase.t .......... ok
t/revert.t .......... ok
t/rework.t .......... ok
t/show.t ............ ok
t/snowflake.t ....... 1/?
Failed test 'DB URI should be filled in'
at t/snowflake.t line 81.

<code>got: 'db:snowflake://nonesuch.snowflakecomputing.com/LENOVO%20USER'     </code>
<code>expected: 'db:snowflake://nonesuch.snowflakecomputing.com/LENOVO USER'</code>

Failed test 'Destination should be URI string'
at t/snowflake.t line 82.
<code>got: 'db:snowflake://nonesuch.snowflakecomputing.com/LENOVO%20USER'  </code>
<code>expected: 'db:snowflake://nonesuch.snowflakecomputing.com/LENOVO USER'  </code>
t/snowflake.t ....... 41/? # Looks like you failed 2 tests of 128.
t/snowflake.t ....... Dubious, test returned 2 (wstat 512, ### 0x200)
Failed 2/128 subtests
        (less 1 skipped subtest: 125 okay)
t/sqlite.t .......... ok
t/status.t .......... ok
t/tag.t ............. ok
t/tag_cmd.t ......... ok
t/target.t .......... ok
t/target_cmd.t ...... ok
t/upgrade.t ......... ok
t/verify.t .......... ok
t/vertica.t ......... ok
t/x.t ............... ok

==Test summary report== 
t/snowflake.t     (Wstat: 512 Tests: 128 Failed: 2)
  Failed tests:  12-13
  Non-zero exit status: 2
Files=47, Tests=6957, 67 wallclock secs ( 1.00 usr +  0.33 sys =  1.33 CPU)
Result: FAIL
Failed 1/47 test programs. 2/6957 subtests failed.
  DWHEELER/App-Sqitch-0.9999.tar.gz
  C:\Strawberry\perl\bin\perl.exe ./Build test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports DWHEELER/App-Sqitch-0.9999.tar.gz
Stopping: 'install' failed for 'App::Sqitch'.`

**Comment by RachetRalph** [comment]
Can someone please guide me in the right direction, I finding it hard to even compose the question here, not sure whats going on. I want to use mysql, have no urge to deal with snowflake at the moment. Why does one test failure result in the installation failure of the whole app? 
Im new to sqitch and perl.

**Comment by theory** [comment]
Oh, unexpected error. I'll fix, but it's just a bug in the test, I think, not the code. How are you installing it? You just want to force install it so it ignores test failures, or set the `SQITCH_ORIG_SYSUSER` environment variable to something without special characters before you run the test. Or run the test using a username without a space in it.
