### ISSUE TITLE
Test suite fails with German locale

### ISSUE THREAD

**Issue by eserte** [sqitchers/sqitch#472]
If a German locale is in effect (e.g. `LC_ALL=de_DE.UTF-8`), then the test suite of v1.0.0 fails:
```
#   Failed test 'Unknown argument error message should be correct'
#   at t/add.t line 593.
#          got: 'Unbekannte Argumente: "foo, bar"'
#     expected: 'Unknown arguments: foo, bar'
# Looks like you failed 1 test of 236.
t/add.t ............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/236 subtests 
```
... and more test scripts fail, with a total of:
```
Failed 13/47 test programs. 36/6943 subtests failed.
```

**Comment by theory** [comment]
Thanks @eserte! I need to figure out how to run the tests with each supported l10n enabled, but it would be super slow, since it would require building a bundle with `dzil build`, which is what creates the l10n files. Maybe I can work out how to do it without `dzil`…
