### ISSUE TITLE
Add command to check list deployed changes for which the deploy script has changed

### ISSUE THREAD

**Issue by matthieu-foucault** [sqitchers/sqitch#475]
I'm relatively new to using sqitch so let me know if there's something obvious that I'm missing here.

Here is a scenario describing the behavior I would expect from `sqitch`:
 1. deploy a plan containg one or more changes
 1. make changes to some deploy scripts
 1. `sqitch verify` should output which scripts should be re-deployed, by comparing the sha1 sum of the scripts in the working directory to the ones in the `changes` table

This would be particularly useful when developing deploy scripts. AFAIK, there is no easy way to tell which scripts need to be redeployed when switching branches. One would expect `sqitch checkout` to ensure that the database has a state that matches the deploy scripts in the checked out branch, but that does not seem to be the case.

I'm going to start working on implementing this, and will submit a PR if you think that this feature should be added.

**Comment by ssoriche** [comment]
Welcome to sqitch!

Sqitch changes are deployed in order. If you need to go back and change a deploy script that has already been deployed, that’s when `sqitch rework` is used. The other option is creating a new deploy script that updates to the way you want the database to appear now.

If you’re working in your development environment and you’re making changes to the sqitch files to make sure they work, you can use `sqitch revert` to undo the changes that have been applied and then redeploy them. The `sqitch revert` command also takes a change name parameter to revert to, allowing changes to be reverted to a previous change.

I hope this helps clarify the workings for you.

**Comment by matthieu-foucault** [comment]
We're working in our development environment. We are starting to have a significant number of scripts, and we want to improve our development process. 

The problem with `sqitch revert` is figuring out which change to revert to. This is something that needs to be done multiple times a day, as we switch branches, pull new changes, etc. The needed commands will be implemented in git hooks eventually, but I feel that something is missing here, as I haven't found a sqitch command indicating the developer that their working directory contains deploy scripts what do not match what is deployed.

When deploying, sqitch stores the SHA1 of the deploy script, so it would be easy, when doing a `sqitch verify` (or whatever command is most appropriate), to check which deploy scripts have changed in the working directory.

**Comment by theory** [comment]
Good idea. Not for `sqitch verify`, but a new command, "Show me what's changed" sort of thing.

**Comment by matthieu-foucault** [comment]
Any preference on how that command should be named?
I asked around and we have those for now:
 - `sqitch check-workdir`
 - `sqitch checksum`
 - `sqitch digest`

**Comment by ssoriche** [comment]
@matthieu-foucault thank you for clarifying, I understand better what you’re trying to do and agree, it’s a good idea.

As for a command name, would this make sense to add as an option to the `sqitch plan` command? Maybe something like `sqitch plan —validate`

**Comment by theory** [comment]
The reason for the deploy checksums is to add a `merge` command, as described in #200. But I like using it for the purpose described here, too, and it goes nicely with the proposed `check` command in #13.

**Comment by theory** [comment]
Done by merging #477. Thank you, @matthieu-foucault!
