### ISSUE TITLE
Sqitch with MySQL on Windows 10 continued issue

### ISSUE THREAD

**Issue by TBSliver** [sqitchers/sqitch#478]
#262 mentions exactly the same issue. Heres what I've attempted:

* Putting my username/password into:
  * The correct mysql user config files (`%APPDATA%\MySQL\.my.login.cnf`)
  * An extra file `%HOME\.my.cnf` so that MySQL::Config can find it...
* Added the following to my sqitch.conf:
```
[engine "mysql"]
	client = C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysql.exe
```

However all I get is the help text output from mysql while it tries to deploy the registry tables.

Note that not having the ~/.my.cnf file present makes it default to the current username and no password.

The command its trying to run is:

```
C:\Users\Tom Bloor\Documents\Wdir\Client\Project [TBSliver/Branch ≡ +0 ~3 -0 !]> berrybrew exec --with 5.30.0_64 sqitch deploy db:mysql:db_test
Adding registry tables to db:mysql:sqitch
From _run at C:/berrybrew/5.30.0_64/perl/site/lib/App/Sqitch/Engine/mysql.pm line 377.
$VAR1 = 'C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysql.exe';
$VAR2 = '--user';
$VAR3 = 'tomb';
$VAR4 = '--database';
$VAR5 = 'db_test';
$VAR6 = '--password=testing';
$VAR7 = '--silent';
$VAR8 = '--skip-column-names';
$VAR9 = '--skip-line-numbers';
$VAR1 = '--execute';
$VAR2 = 'SET sql_mode = ansi; CREATE DATABASE IF NOT EXISTS "sqitch"';
```

(dumping the args of $sqitch->run from _run in Engine::mysql).

**Comment by theory** [comment]
Are you running v1.0.0? Because 0148359 is supposed to fix this issue.

**Comment by TBSliver** [comment]
Yep im running v1.0.0 which is why Im confused this is still an issue...

```
➜ berrybrew exec --with 5.30.0_64 perl -M"App::Sqitch 99"
App::Sqitch version 99 required--this is only version v1.0.0.
BEGIN failed--compilation aborted.
```

**Comment by theory** [comment]
I don't have MySQL but have installed SQLite on a Windows VM. With this patch applied for debugging:

``` patch
--- a/lib/App/Sqitch.pm
+++ b/lib/App/Sqitch.pm
@@ -333,7 +333,9 @@ sub run {
         die $msg;
     };
     if (ISWIN && IPC::System::Simple->VERSION <= 1.25) {
-        runx ( shift, $self->quote_shell(@_) );
+        my @args = ( shift, $self->quote_shell(@_) );
+        use Data::Dumper; print Dumper \@args;
+        runx @args;
         return $self;
     }
     runx @_;
```

And a pointer to the SQLite client in the config file:

```
[core]
	engine = sqlite
[engine "sqlite"]
	target = db:sqlite:
    client = C:\\sqlite\\sqlite3.exe
```

I see output like so:

```
perl -CAS ..\t\sqitch deploy db:sqlite:foo
Deploying changes to db:sqlite:foo.db
  + foo .. $VAR1 = [
          'C:\\sqlite\\sqlite3.exe',
          '"-noheader" "-bail" "-batch" "-csv" "foo.db" ".read \'deploy\\foo.sql\'"'
        ];
ok
```

So it's properly escaping quoting the args in a single string. But maybe it doesn't like spaces in the first argument? Let's try `C:\sqlite 3\sqlite.exe`:

```
  - foo .. $VAR1 = [
          'C:\\sqlite 3\\sqlite3.exe',
          '"-noheader" "-bail" "-batch" "-csv" "foo.db" ".read \'revert\\foo.sql\'"'
        ];
not ok
```

So perhaps the spaces need to be escaped?

/me futzes for a while…

No, the Config format doesn't require the space to be escaped. I think the issue is that my workaround for the lack of meeting of pjf/ipc-system-simple#29 isn't quite right when the executable path has spaces in it, and I can't see a way to massage it to work with the bugs in the current release of IPC::System::Simple. So two questions for you:

1. Does it work if you move the MySQL client to a path without spaces?
2. If you leave it with spaces, does it work if you manually apply pjf/ipc-system-simple#29?

**Comment by TBSliver** [comment]
Oops sorry GH doesnt seem to ping me as loudly as other things, so only just saw this - will add it to my todo list for soon(tm)

**Comment by TBSliver** [comment]
Right, finally got to the point of being able to try this. Patched IPC::System::Simple as your PR showed, however now its over quoting things, such that it doesnt read the user properly from CLI. However, it is a step in the right direction - i'l see if I can find an error in the IPC patch....

**Comment by TBSliver** [comment]
Found it! Its a case of too much quoting. Commenting out the windows specific part in `App::Sqitch run` (so it just uses `runx` without any massaging), then in `IPC::System::Simple runx` I added `Win32::ShellQuote` to the deps for Windows, and then changed the args for _spawn_or_die to:

```perl
        my $pid = _spawn_or_die($command, Win32::ShellQuote::quote_native($command, @args));
```

And it just worked. I think the issue was, all the arguments getting quoted as a concatenated string, and then the string being re-quoted in IPC::System::Simple...

**Comment by theory** [comment]
Yeah, I think this is because I assumed that IPC::System::Simple would have the fix, but it doesn't. There's some movement on the patch now, so I'm optimistic for 1.27, but in the meantime, Sqitch is not compatible with 1.26 on Windows, sadly.

**Comment by theory** [comment]
Here's a patch that should also fix the issue:

``` patch
--- a/lib/App/Sqitch.pm
+++ b/lib/App/Sqitch.pm
@@ -332,7 +332,7 @@ sub run {
         ( my $msg = shift ) =~ s/\s+at\s+.+/\n/ms;
         die $msg;
     };
-    if (ISWIN && IPC::System::Simple->VERSION <= 1.25) {
+    if (ISWIN && IPC::System::Simple->VERSION <= 1.26) {
         runx ( shift, $self->quote_shell(@_) );
         return $self;
     }
```
