### ISSUE TITLE
Snowflake - management of present data

### ISSUE THREAD

**Issue by MeQT** [sqitchers/sqitch#480]
Hey,

I was wondering how it should work in a scenario where data is present.
When started working sqitch on snowflake I stopped when I lost all data after each deployment.
Looking into the snowflake query histroy there is only the create or replace statement.

Is there something missing or did I not understand the feature set of sqitch? I was assuming that it would backup the data beforehand or even right alter statements if possible for saving snowflake credits.

Could you tell me if there is somekind of data strategy in place or do I need to handle it on my own. Your framework is actually quite awesome when coming from a application developer background and not dba. Would be happy to use it.

OS: Windows Server 2016 | Ubuntu 19.04

Greetings

**Comment by theory** [comment]
Hi. I suggest that you post your question to the [mail list](https://groups.google.com/group/sqitch-users), as we reserve GitHub issues for bugs, feature requests, and the like. Thank you!
