### ISSUE TITLE
Default value for client variables

### ISSUE THREAD

**Issue by carragom** [sqitchers/sqitch#482]
Hi there,

I'm starting to use conditional meta-commands in `psql` and client variables to control whether some parts of the deploy/revert/verify scripts gets executed. For example when loading test data.

Something like

```sql
begin;

-- create table

\if :test_data
-- insert test data into table
\endif

commit;
```

Then with this `sqitch deploy -s test_data=true` we can control whether test data gets inserted or not.

That's all great but it would be awesome if we could specify default values for those variables in the config file. In this case I would like to set `test_data=false` by default in `sqitch.conf` to prevent the warning `unrecognized value ":test_data" for "\if expression"` that will get printed when no client variable is passed at all. Is this currently possible?.

**Comment by kwakwaversal** [comment]
The deploy manual implies that `-s` overrides any default configuration variables - https://metacpan.org/pod/sqitch-deploy#-s - but I'm not sure what the config block for doing that looks like after looking at the config manual.

**Comment by carragom** [comment]
Thanks for the answer and the link to the docs. Happily reporting that either the `core` or `deploy` sections with subsection `variables` can be used to achieve my goal, e.g.

```ini
[core]
	engine = dev
	top_dir = ./migrations
[deploy "variables"]
	test_data=false
[target "dev"]
	uri = db:pg:dev
[engine "dev"]
	target = dev
```

I would love however for someone to clarify how to do it in the `engine` or `target` sections which are the ones that will normally differ in variable definition for example when you have a dev/test/prod engine/target. I tried reading the [GitLike](https://metacpan.org/pod/Config::GitLike) docs but could not figure it out how to have more than 3 levels of nesting.

**Comment by carragom** [comment]
And never mind, found it [here](https://metacpan.org/pod/sqitch-config). Variables can be added with `sqitch config --add target.dev.variables q=qwe` if you don't want to edit `sqitch.conf` manually. Multiple variables can be defined and that resulting configuration file will look like this

```ini
[core]
	engine = dev
	top_dir = ./migrations
[target "dev"]
	uri = db:pg:dev
        variables = q=qwe
        variables = a=asd
        variables = z=zxc
[engine "dev"]
	target = dev
```

**Comment by carragom** [comment]
Sorry, talked too soon. While it's effectively possible to add multiple client variables with `sqitch config --add` and retrieve them using `sqitch config --get-all` they are not honored by the deploy command. For example when doing `sqitch deploy`

## These Work

```ini
[core "variables"]
    test_data=false
```

```ini
[deploy "variables"]
    test_data=false
```

## These Don't

```ini
[core]
    variables = test_data=false
```

```ini
[deploy]
    variables = test_data=false
```

```ini
[engine "pg"]
    variables = test_data=false
```

```ini
[target "dev"]
    variables = test_data=false
```

**Comment by theory** [comment]
I think [sqitch-configuration](https://sqitch.org/docs/manual/sqitch-configuration/) is the doc you’re looking for.

**Comment by carragom** [comment]
That is indeed the doc I was looking for. Thanks a lot.
Just to document this issue before closing it, the following command `sqitch target alter dev --set test_data=true` would achieve what I wanted and create a section on *sqitch.conf* like this

```ini
[target "dev.variables"]
	test_data=true
```
