### ISSUE TITLE
sqitch log: ambiguous call resolved as CORE::open()

### ISSUE THREAD

**Issue by dudleycarr** [sqitchers/sqitch#487]
Version: 1.0.0 (installed via brew)
Platform: MacOS X Mojave

I get the following warning running sqitch log:
```
\Ambiguous call resolved as CORE::open(), qualify as such or use & at /usr/local/Cellar/sqitch/v1.0.0/bin/../lib/perl5/IO/Pager.pm line 180.
```

Sqitch log seems to be working fine otherwise.

**Comment by theory** [comment]
This is a [known IO::Pager issue](https://rt.cpan.org/Public/Bug/Display.html?id=127551). No harm in it, just annoying.
