### ISSUE TITLE
Snowflake deployment error , Windows OS

### ISSUE THREAD

**Issue by BalaMuralibi** [sqitchers/sqitch#489]
Please help. I ran following to deploy changes to snowflake
sqitch deploy "db:snowflake://username:Pwd8@Sfaccount.east-us-2.azure.snowflakecomputing.com/flipr?Driver=SnowflakeDSIIDriver;"

Error : 
Adding registry tables to db:snowflake://Username:@rb36322.east-us-2.azure.snowflakecomputing.com/flipr?Driver=SnowflakeDSIIDriver;
"snowsql" failed to start: "The system cannot find the file specified"

My sqitch.config look like this 
[engine "snowflake"]
	client = snowsql
[user]
	name = 'xxxx'
	email = 'xxxxx@outlook.com'

I can't able to give complete path of snowsql client C:\Program Files\Snowflake SnowSQL.

**Comment by theory** [comment]
It needs the full path to `snowsql`. You can either add `C:\Program Files\Snowflake SnowSQL` to your path, or else set the path in the configuration file with

```
sqitch config --user engine.snowflake.client "C:\Program Files\Snowflake SnowSQL"
```

It might also be choking on the space in the path, though; I've been having a hard time getting the command dispatcher to behave; see #478 for more information.

**Comment by BalaMuralibi** [comment]
Yes, its not configuring correctly sqitch config --user engine.snowflake.client "C:\Program Files\Snowflake SnowSQL" with this.

Rather it worked with this. sqitch config --user engine.snowflake.client "SnowSQL"
