### ISSUE TITLE
Sqitch config Multiple target Uri Snowflake engine

### ISSUE THREAD

**Issue by BalaMuralibi** [sqitchers/sqitch#491]
Hi David,

This is not an issue , but more of information 
Can sqitch.config allow to create multiple target uri and configiuring uri targets to snowflake engine ? something like below image.

I am able to add target uri's but can't able to map uri to engine. Please help

![image](https://user-images.githubusercontent.com/41836891/68126701-a427a080-ff14-11e9-86ef-e337a9b1825f.png)

**Comment by theory** [comment]
I believe it's implied by the `db:snowflake` part of the URIs.
