### ISSUE TITLE
usql support?

### ISSUE THREAD

**Issue by jetzerb** [sqitchers/sqitch#493]
Wondering if you're aware of [usql](https://github.com/xo/usql), which runs on Linux, Mac, & Windows and claims to be
> A universal command-line interface for PostgreSQL, MySQL, Oracle Database, SQLite3, Microsoft SQL Server, and many other databases including NoSQL and non-relational databases!

Might simplify `sqitch` internals if all DB communication is done via a single tool, rather than a specific tool for each DB.

Disclaimer: I'm not affiliated with the `usql` project.  Nor have I evaluated it in any way.  I just heard about it on a podcast on my way in to work this morning.

**Comment by theory** [comment]
One of the design goals of Sqitch is to let folks feel at home by using the features of their native database command-line clients. There's not much to the internals for this; Sqitch simply lets the CLIs be responsible for deploying SQL scripts however they see fit.

You can,  however, use other clients by implementing a shell script to convert the native command-line clients to those expected by `usql` and then call `usql`. Then set `core.client` to point to your shell script.
