### ISSUE TITLE
"Cannot determine local time zone" error when deploying

### ISSUE THREAD

**Issue by datafoo** [sqitchers/sqitch#494]
I use Sqitch successfully for my development and I wanted to use it in a Continous Integration pipeline on [Gitlab.com](https://gitlab.com/).

Specifically, I use the Docker with a [`nixos/nix:latest`](https://hub.docker.com/r/nixos/nix/) image to easily get all my dependencies with [Nix](https://nixos.org/nix/).

When the first sqitch-deploy command is executed, I get a "Cannot determine local time zone" error:
```
[…]
805 $ sqitch --version
806 .sqitch-wrapped (App::Sqitch) v1.0.0
807 $ psql --version
808 psql (PostgreSQL) 11.5
809 $ sqitch deploy --cd db/cluster --target db:pg://postgres:postgres@postgres:5432/postgres
810 Adding registry tables to db:pg://postgres:@postgres:5432/postgres
811 Deploying changes to db:pg://postgres:@postgres:5432/postgres
812   + database/postgres.privileges ................ Cannot determine local time zone
813 Cannot determine local time zone
814 Deploy failed
818 ERROR: Job failed: exit code 2
```

I see there is a mention of this error in the [0.9992 changelog](https://github.com/sqitchers/sqitch/blob/992b8943dfbcdb0a35dbdaf2d329371944132d6c/Changes#L643) but as indicated above, I use Sqitch 1.0.0.

Am I doing anything wrong?

**Comment by theory** [comment]
Make sure that you have the time zone database files installed on your OS.

**Comment by datafoo** [comment]
> Make sure that you have the time zone database files installed on your OS.

I am not sure how to do that but I tried to add `tzdata` and I ran into another issue that is not related to Sqitch:
```
collision between `/nix/store/qm06pmc7vyi78vpm1cd9ash2vdmmrlwy-tzdata-2019b-bin/bin/zic' and `/nix/store/hblpx8x5w88igmwa4ydnsnb65s363lji-glibc-2.27-bin/bin/zic'
```

I tried something else instead. I added `export TZ=Etc/UTC` in my `.gitlab-ci.yml` file and I managed to sqitch-deploy successfully.

I don't fully understand the cause of this issue but I guess it is not related to Sqitch anyway.

**Comment by theory** [comment]
No idea what that collision would be about, but yeah, it sounds like an issue with the package on your OS somehow. As long as Sqitch can determine the time zone and find the time zone files (or rather, the [DateTime](/houseabsolute/DateTime.pm) module can), you should be fine.
