### ISSUE TITLE
How to escape & character

### ISSUE THREAD

**Issue by tk3369** [sqitchers/sqitch#495]
I have a script that needs to insert data into a table. There's an `&` character in a string but sqitch thinks that it is a variable.... How do I escape the `&` character so that it is not considered a variable?  Thanks

**Comment by theory** [comment]
It's not Sqitch, but the database client. If you're using Snowflake, [the docs](https://docs.snowflake.net/manuals/user-guide/snowsql-use.html#using-variables) say to use a double ampersand to escape it, e.g.,

```
user#> select '&&notsubstitution';

+--------------------+
| '&NOTSUBSTITUTION' |
|--------------------|
| &notsubstitution   |
+--------------------+
```

**Comment by tk3369** [comment]
Thanks, appreciate the quick response!
