### ISSUE TITLE
Snowflake initialize error (SQL-42S02)

### ISSUE THREAD

**Issue by tk3369** [sqitchers/sqitch#496]
I am unable to initialize the registry.... Any idea? 
Is there any other way to initialize the registry?  
thanks for your help. 

```
$ sqitch deploy 'db:snowflake://myuser@myaccount/flipr?Driver=SnowflakeDSIIDriver;warehouse=mywarehouse' --registry sqitch_flipr
SQL compilation error:
Object 'CHANGES' does not exist or not authorized. (SQL-42S02)
```

My sqitch.plan file:
```
%syntax-version=1.0.0
%project=flipr

appschema 2020-02-11T19:11:29Z Tom <myemail@whatever.com> # add schema
```

My sqitch.conf file:
```
[core]
        engine = snowflake
        # plan_file = sqitch.plan
        # top_dir = .
[engine "snowflake"]
        # target = db:snowflake:
        # registry = sqitch
        client = snowsql
```

I have verified that snowsql works and have proper permission.

**Comment by theory** [comment]
Do you need to set an role?

**Comment by tk3369** [comment]
The role is already set in the ~/.snowsql/config file.

**Comment by theory** [comment]
As the default role, yes? Sqitch looks for a role in this order: 

1. The URI query param, e.g., `db:snowflake:account/dbname?role=whatever`
2. The `$SNOWSQL_ROLE` environment variable
3. The default `rolename` value in `~/.snowsql/config` (not under a named section)

**Comment by theory** [comment]
@tk3369 Did you get your issue worked out?
