### ISSUE TITLE
Tests fail if you have no GECOS

### ISSUE THREAD

**Issue by davel** [sqitchers/sqitch#497]
On a VM without a GECOS set up, tests fail like this,

```
t/add.t ............. ok

#   Failed test 'Default user_name should be set from system'
#   at t/base.t line 56.
# Looks like you failed 1 test of 189.
```

In `/etc/passwd` I had,

```dlambley:x:1001:1001::/home/dlambley:/bin/bash```

The obvious workaround of populating GECOS allows the tests to pass.

**Comment by theory** [comment]
Does 992b8943d not fix that issue?

**Comment by davel** [comment]
Yes, running the tests at 992b8943dfbcdb0a35dbdaf2d329371944132d6c on a clean machine works.
