### ISSUE TITLE
Failure in t/base.t for user_name default if the unix user building has no GECOS

### ISSUE THREAD

**Issue by shadowcat-mst** [sqitchers/sqitch#498]
Because of the way $sqitch->user_name is defaulted, its last attempt is to use the GECOS field from the User::pwent struct. This means that if the unix user being used to build/test/install sqitch has an empty GECOS field, $sqitch->user_name returns '' which is falsey and as such the test for it in t/base.t fails.

I'm not entirely sure what the correct fix for this is - I'd suggest either accepting that that can happen and adjusting the test, or defaulting to using just the unix username if the GECOS is empty are probably the two best options.

**Comment by theory** [comment]
Does 992b8943d not fix that issue? (See also #497)

**Comment by theory** [comment]
Yo @shadowcat-mst, can you verify that 992b894 addresses your issue? Thanks!

**Comment by shadowcat-mst** [comment]
Looks great, sorry I forgot to check master before reporting.
