### ISSUE TITLE
How to Extract from database schema  to sqitch with dependency

### ISSUE THREAD

**Issue by laurentankri** [sqitchers/sqitch#500]
It is possible to extract a schema database to load it in git source control using sqitch ?

**Comment by theory** [comment]
If you can dump your database, yes. See [this wiki(https://github.com/sqitchers/sqitch/wiki/How-do-I-get-started-with-an-existing-database%3F) for a quick primer.

Please direct questions such as this to the mail list (details [here](https://sqitch.org/community/)), as we try to use GitHub issues for bug reports and feature tracking.
