### ISSUE TITLE
grant minimal rights on sqitch IS to any db role

### ISSUE THREAD

**Issue by jpruliere** [sqitchers/sqitch#507]
I want to create a small Node package that makes assertions on the database "version", to ensure an app only uses features that were previously deployed with Sqitch.

e.g. with this sqitch plan
```
init 2020-03-05 # 2 tables, some constraints
some_function 2020-03-07 # some_function(int, text) returns boolean
some_other_function 2020-03-09 # some_other_function(int, int) returns boolean
```

to enable writing assertions like these
```js
// at the app level
// the whole app needs at least this change to be deployed
sqitch.assertDeploy('some_function');

// or at any finer level
function(some_int, some_other_int) {
    // this function calls a function added in a specific change
    sqitch.assertDeploy('some_other_function');
    // use a pg client to call some_other_function($1, $2) with [some_int, some_other_int]
}
```

Those calls would read info from the `sqitch` schema (or wherever the registry is on other DBMS). I only use PG but I think the problem is the same everywhere : I use the superuser _postgres_ to deploy with Sqitch but I use a specific restricted user to access the database from within the app. And since the Sqitch information system was created by _postgres_, it's a no go for any other user.

Currently, I write a deploy that creates a security definer function that returns the `change` column from the `sqitch.changes` table ordered by `commited_at` and grants its usage to _public_. That's about all I need but it feels like tinkering... Another way would be to grant select right on the `sqitch.changes` to _public_ but it still has to be done manually.

Would you consider adding this feature to a future version ? :pray:

**Comment by theory** [comment]
Sqitch doesn't specify any permissions on its registry, as you can see [here](/sqitchers/sqitch/blob/develop/lib/App/Sqitch/Engine/pg.sql). So you can change them however you like. Or use a function like you've already done; both seem legit to me.

You might want to post to the [mail list](https://sqitch.org/community/) to see what other kinds of things folks might suggest.
