### ISSUE TITLE
How to bundle multiple plans?

### ISSUE THREAD

**Issue by moshthepitt** [sqitchers/sqitch#516]
Suppose you have projects organised this way:

```
project-1/
|-- deploy/
|-- revert/
|-- verify/
|-- sqitch.conf
|-- sqitch.plan
project-2/
|-- deploy/
|-- revert/
|-- verify/
|-- sqitch.conf
|-- sqitch.plan
```

Suppose further that the plan in `project-2` contains migrations that reference and require migrations in `project-1`.

Is it possible to bundle `project-2` such that the resulting bundle includes all migrations in `project-2` as well as their dependencies in `project-1`?

--

PS:  Sorry if this is the wrong place to ask this.

**Comment by theory** [comment]
1. No, they're separate, but there are various ways you can mix and match things. See the [Target Configuration](https://sqitch.org/docs/manual/sqitch-configuration/#target-configuration) section of [sqitch-configuration](https://sqitch.org/docs/manual/sqitch-configuration/) for a handy discussion.

2. Consider joining the [mail list](https://sqitch.org/community/) to post questions in the future.
