### ISSUE TITLE
Use of uninitialized value

### ISSUE THREAD

**Issue by fniko** [sqitchers/sqitch#519]
I have no clue what happened, but I tried to use different settings for sqitch and now I cannot even try to do plan or verify.

### Expected Behavior
Sqitch should proceed and show the results.
### Current Behavior
I am redirected to something like "man" or simplified vim:
```
# Project: test
# File:    sqitch.plan

ESC[32mDeploy cff1b2812937fe7c7f85ae9be06ab422fc7470a1ESC[0m
Name:      create_role
Planner:   Filip Niko <filip.niko25@gmail.com>
Date:      2020-05-29 16:00:13 +0200

    Add Initial Roles
```
after hitting key **q** it exits and I can see the following error:
```
Use of uninitialized value in string eq at /usr/local/Cellar/sqitch/v1.1.0/bin/../lib/perl5/IO/Pager.pm line 23.
Use of uninitialized value $IO::Pager::PAGER in string eq at /usr/local/Cellar/sqitch/v1.1.0/bin/../lib/perl5/IO/Pager.pm line 23.
```
### Steps to Reproduce
Run `sqitch plan`
### Context (Environment)
- sqitch (App::Sqitch) v1.1.0
- macOS Mojave 10.14.6 (18G95) (installed through Brew)
### Possible Implementation

Is there a way how to fix this, please?

**Comment by fniko** [comment]
It seems like I screwed some settings so this is not the bug.

**Comment by theory** [comment]
Well no, IO::Pager should not complain like that, but I don’t think it’s fatal, but a warning.
