### ISSUE TITLE
Invalid connection string to snowflake

### ISSUE THREAD

**Issue by zmaleki** [sqitchers/sqitch#524]
sqitch deploy keeps returning invalid connection string. I have checked the username and password multiple times and tried it with same connection string that was working a few weeks ago. I even tried to connect to snowsql directly using the same account name, username and password and it all works perfectly however sqitch connection does not work.

```
sqitch target add newtarget "db:snowflake://myusername@myaccount.us-east-1/sqitchdbname?Driver=SnowflakeDSIIDriver;warehouse=mywarehouse;role=ACCOUNTADMIN"
sqitch deploy newtarget
```
Error message:
```
[Snowflake][Support] (50404) Invalid connection string. (SQL-HY000)
```

**Comment by theory** [comment]
Thanks for the report. Do you have any special characters in any of the values in the URI? They might need to be URL-encoded.

**Comment by zmaleki** [comment]
Yes that was the issue, I had special chars in the password value

**Comment by ankita61299** [comment]
Hi,
Am getting the error of 
 sqitch deploy db:snowflake://****:****@snowhouse/it?Driver=Snowflake;warehouse=it_data_ingest
[Snowflake][Support] (50404) Invalid connection string. (SQL-HY000)

**Comment by sfc-gh-stekavade** [comment]
@zmaleki  I'm getting same error and my password starts with special char ';'
can you please help me understand how did you resolve it ? 
my URL looks like. - `'db:snowflake://$username:$password@myaccount/mydb?Driver=Snowflake;warehouse=my_wh'`

**Comment by theory** [comment]
I suggest you not use the password in the URI, but if you do, make sure you quote it and URI-encode it. You can find extensive information on specifying credentials in the [Authentication Guide](http://sqitch.org/docs/manual/sqitch-authentication/).

**Comment by sfc-gh-stekavade** [comment]
@theory  Thanks this resolved the password issue.
now our project is stalled at - [https://github.com/sqitchers/sqitch/issues/586](url)

```
`+ cd TestCode_Folder
+ sqitch deploy db:snowflake ://sqitch_user:****@myaccount/mydb?Driver=Snowflake
Adding registry tables to db:snowflake ://sqitch_user:@myaccount.snowflakecomputing.com/it?Driver=Snowflake
003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'mydb'
"snowsql" unexpectedly returned exit value 5`
```

**Comment by theory** [comment]
Does `sqitch_user` have permission to create a schema in the mydb database?

**Comment by ankita61299** [comment]
No,But sqitch_user has access to create table inside schema and we are
trying to deploy table
Schema is already created
We only have DDL command for table creation  inside deploy folder

**Comment by theory** [comment]
Sqitch creates its own schema for the registry. Create a schema named "sqitch" and try again.

**Comment by sfc-gh-stekavade** [comment]
@theory  What if we create schema 'SQITCH' manually and give all privileges to our default role. We are trying to avoid sqitch_user having CREATE SCHEMA privileges just in case if there is a bug and what if sqitch dropped a schema by mistake? 
CREATE SCHEMA also gives right to DROP SCHEMA
Out security Team is hesitant about giving CREATE SCHEMA privilege to sqitch user.

**Comment by sfc-gh-stekavade** [comment]
@theory Is it like sqitch runs create schema statement on database every time it tries to deploy something? 
We tried creating sqitch schema manually and assigning all privileges to sqitch user but it did not work getting same error.
`003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'mydb'
"snowsql" unexpectedly returned exit value 5`

**Comment by sfc-gh-stekavade** [comment]
@theory  We tried that but getting same error. I think Sqitch runs CREATE SCHEMA statement irrespective of the fact that schema exist or not in database when it deploys code for the first time. We were able to deploy the code second time onwards once sqitch creates registry schema in 1st run.
 
Is there any way to remove dependency of having to run CREATE SCHEMA for sqitch deployments ? 
CREATE SCHEMA also gives privileges to DROP SCHEMA
Our security Team is hesitant to provide snowflake service user CREATE SCHEMA privilege as there is a possibility of someone pushing buggy/incorrect code into the repo and sqitch ends up dropping any existing schemas.

**Comment by theory** [comment]
[It uses CINE](/sqitchers/sqitch/blob/1fb67131f9389a56f206e51e0ebb7f1a7cc97f80/lib/App/Sqitch/Engine/snowflake.sql#L1), so it should work fine if the schema's not there. What error did you get after you created the schema and let Sqitch run?

**Comment by sfc-gh-stekavade** [comment]
Same error that we got earlier - 
`003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'mydb'
"snowsql" unexpectedly returned exit value 5`

**Comment by theory** [comment]
I think you need to talk to your admin, as this is a permissions issue.
