### ISSUE TITLE
Sqitch Snowflake status command works but deploy command fails

### ISSUE THREAD

**Issue by kashifmalik-sde** [sqitchers/sqitch#526]
Hello Sqitchers,

I am connecting to Snowflake using Pub/Private key authentication and running the Sqitch Snowflake docker image via CICD pipeline. The `sqitch status` command works fine for me but when I run the `sqitch deploy connectionString` command, I have an error which is pasted below. Could someone please help on this one?

`sqitch deploy 'db:snowflake://***.***/mydb?Driver=Snowflake;role=***;authenticator=SNOWFLAKE_JWT;warehouse=***;uid=***;priv_key_file=/var/.snowsql/privatekey.p8;priv_key_file_pwd=**************'
Deploying changes to db:snowflake://***.***.snowflakecomputing.com/mydb?Driver=Snowflake;role=***;authenticator=SNOWFLAKE_JWT;warehouse=***;uid=***;priv_key_file=/var/.snowsql/privatekey.p8;priv_key_file_pwd=*************
  + my_change/stage .. Execution of finally() block CODE(0x5583f2cb56a8) resulted in an exception, which *CAN NOT BE PROPAGATED* due to fundamental limitations of Perl. Your program will continue as if this event never took place. Original exception text follows:

DBD driver has not implemented the AutoCommit attribute at /bin/../lib/perl5/App/Sqitch/Role/DBIEngine.pm line 985.

[Snowflake][Snowflake] (10) 
      Failed to execute query. Error code=-1, GS error code=390111, GS error message=Session no longer exists.  New login required to access the service.
     (SQL-HY000)
Deploy failed
    (in cleanup) @zªó·U····Úð·U at /bin/../lib/perl5/Throwable.pm line 76 during global destruction.
make: *** [Makefile:31: deploy_verify] Error 2

[Container] 2020/06/11 04:01:18 Command did not exit successfully make deploy_verify exit status 2`

**Comment by theory** [comment]
Sounds a little like #520. As I said there:

> Be sure to set all the environment variables as well as pass the parameters in the connection URI; there seem to be some places where one is read but not the other, and I haven't had time to track them all down.

But this is weird:

```
DBD driver has not implemented the AutoCommit attribute at /bin/../lib/perl5/App/Sqitch/Role/DBIEngine.pm line 985.
```

Because that attribute is kind of fundamental to the DBI. And what about this?

```
[Snowflake][Snowflake] (10)
Failed to execute query. Error code=-1, GS error code=390111, GS error message=Session no longer exists. New login required to access the service.
(SQL-HY000)
Deploy failed
(in cleanup) @zªó·U····Úð·U at /bin/../lib/perl5/Throwable.pm line 76 during global destruction.
```

So it *was* connected, but somehow became disconnected?

Are you using the Docker image? Did you pull it within the last few days? I updated it to use the latest release of the Snowflake ODBC driver, but perhaps it has a bug.

**Comment by kashifmalik-sde** [comment]
Thanks for looking into it @theory . I am using the docker image from https://github.com/sqitchers/docker-sqitch/tree/master/snowflake. The ODBC driver I have is from the previous version i.e, `2.20.5` rather than `2.21.5`.  I believe the connection parameters and the snowsql .conf files are ok, because I am able to read the correct status while running 'sqitch status' in the pipeline which is using docker image. I can try bumping up the odbc version of the driver in the image file but not sure if that would fix the problem.

**Comment by theory** [comment]
Okay, if `status` works, the ODBC connection is probably fine, as `status` simply reads from the registry via ODBC. The `publish` command, OTOH, both connects to the registry for reading and writing *and* passes script files to SnowSQL for execution. So perhaps it's SnowSQL that's unhappy. Hard to tell from those messages, though.

**Comment by kashifmalik-sde** [comment]
Agreed, and just to provide you a bit more context, if I connect using username/password (not using docker), I am successfully executing my Snowsql script. So I am thinking that when running the cicd using docker with pub/priv key auth mechanism, `sqitch deploy` is failing because perhaps snowsql is not able to handle the auth parameters properly and falling over. There are special characters like $ and double quotes in the passphrase.

**Comment by theory** [comment]
Oh, yeah, maybe. Are you both specifying the params in the URI and setting the environment variables? Here's the list of SnowSQL environment variables that the [shell script](/sqitchers/docker-sqitch/blob/master/docker-sqitch.sh) passes to the container:

https://github.com/sqitchers/docker-sqitch/blob/738302a9b3d7a16b254c009ea73042df757b0ef0/docker-sqitch.sh#L42

**Comment by kashifmalik-sde** [comment]
Good point, let me validate against what you have kindly highlighted. I am not using `docker-sqitch.sh` but have my own make file, so maybe some Env Variable has not been set up and being missed. Would confirm back on Monday if someone was indeed missing, cheers

**Comment by kashifmalik-sde** [comment]
The env variables seem fine. Interesting if I start a new project then there are no issues with `sqitch deploy` command. So I might have to revert my changes and reapply them perhaps.

**Comment by theory** [comment]
That seems odd; have you made any progress, @kashifmalik-sde?

**Comment by kashifmalik-sde** [comment]
`sqitch deploy` works now after I ran: 
1) `sqitch revert` using username and password approach; i originally created everything with this 
2) removed Sqitch registry tables, and finally ran 
3)`sqitch deploy` in my cicd pipeline using pub/private key auth mechanism for a service user.

It seems like the change of Auth mechanism and user required a fresh start. Happy for you to close because I am now able to progress on.

Thank you very much for actively helping, cheers

**Comment by theory** [comment]
Ah, permission issue the, awesome. Glad you got it cleared up!
