### ISSUE TITLE
Fixed schema

### ISSUE THREAD

**Issue by vedicHippie** [sqitchers/sqitch#527]
I would like to fix a schema as default and avoid mentioning it in every query file. Is it possible in the config file that I fix a schema and every query (deploy/revert/verify) is then by default applied to this schema?

**Comment by theory** [comment]
A copule things:

1. You can use a variable for your client to control the schema used; Search for "Database client variables" in [sqitch-configuration](https://sqitch.org/docs/manual/sqitch-configuration/).

2. Please don't post questions here; GitHub issues are for bug reports and feature requests. Send your questions to the [community mail list](https://sqitch.org/community/), instead. Thank you!
