### ISSUE TITLE
Multiple changes in same transaction

### ISSUE THREAD

**Issue by TimoStolz** [sqitchers/sqitch#528]
Using PostgreSQL, is it possible to deploy multiple changes in only one transaction? Thus, if one change fails, the whole deployment could easily be rolled back to the initial state.

**Comment by theory** [comment]
Hi Tim, a couple things:

1. You can use `BEGIN` and `COMMIT` in change scripts, and each change script is run through a single invocation of `psql`. If you want to run more stuff in a single transaction, you have to put it in a single deploy script.

2. In the future, please send questions to the [Sqitch community](https://sqitch.org/community/) mail list; GitHub issues are reserved for bug reports and feature requests. Thanks you!
