### ISSUE TITLE
[New feature request] sqitch --revert --force and `sqitch prune`

### ISSUE THREAD

**Issue by wkoszek** [sqitchers/sqitch#529]
# Use case

I have many interns and their work is to add a lot of new models to the DB. We use `sqitch` to provision all these changes, and often I test the code locally.

I'd love to be able to checkout between git branches, and just forcefully run all `revert/*.sql` files, regardless, if the middle one failed or not.

Another cool feature for using sqitch for development would be: `sqitch prune` or `sqitch wipe`, where it could delete all the state of migrations listed in `sqitch.plan`, so that once I get into a very dirty state, I can at least get back to fresh registry for that particular project. (other projects on my machine should stay intact).

If there's some combination of current flags I could use, that would be awesome. I tried Golang's migration frameworks, and they all lack this feature too, so sqitch could somehow stand out.

**Comment by theory** [comment]
Have you tried [sqitch checkout](https://sqitch.org/docs/manual/sqitch-checkout/)?

I also use [sqtich revert](https://sqitch.org/docs/manual/sqitch-revert/) to get back to a known state. But sometimes the revert scripts fail because something else got messed up, and I have to either fix it manually or just drop the database and start over. Sqitch doesn't know the content of changes or why things fail, so can't really fix much.

**Comment by wkoszek** [comment]
@theory I'm going to try `sqitch checkout` I admit I haven't noticed that before nor have tried it before. Yeah, I often get to the state where things are broken, and I just do: "drop schema prod cascade". But then sqitch registry stays out-of-date, and I often wish I could do:
```
echo "drop schema prod cascade" | psql
sqitch wipe registry for this project
sqitch deploy
```

**Comment by theory** [comment]
I drop the whole database, but if that's not an option you can just add 

```
psql -c "drop schema sqitch cascade"
```

**Comment by wkoszek** [comment]
@theory That's what I'm doing now. But it wipes my (1) work projects and (2) my side projects. I guess the hack would be:

psql -c "drop schema sqitch cascade where project = 'my_work_project'"

Just wanted to have it done a little prettier.

**Comment by theory** [comment]
Oh, in that case

```
sqitch revert --log-only`
```

Will revert all the changes without actually running your revert scripts.

**Comment by wkoszek** [comment]
Oh, ok.. I read through the whole man page, but I admit I didn't understand `--log-only`.

Shouldn't this be `--registry-only` ?

I'm going to this thing out!

**Comment by theory** [comment]
Maybe. It might pre-date the term "registry", I can't recall.

**Comment by wkoszek** [comment]
@theory I see `--log-only` exists in other subcommands too. If you'd be interested in getting a contribution of a PR with  just making `--registry-only` = `--log-only`, let me know. If not, I think I'm ready to close this issue.

**Comment by theory** [comment]
I don't know if the option name needs to change, but perhaps suggest it in the [mail list](https://sqitch.org/community/)?

It surely could use a better explanation, though. How would the documentation have helped you to better understand this option?

**Comment by wkoszek** [comment]
@theory I guess we use `registry` everywhere in the Sqitch docs, so I'm used to it. `log` is more like .. `sqitch.log` or something. Will propose the idea via mailing list and see what folks say.

**Comment by theory** [comment]
`log` is a verb, as in "log changes to the registry".

**Comment by theory** [comment]
Closing. Open a new ticket about adding an alias for the `--log-only` option if it comes up again. Thanks!
