### ISSUE TITLE
Setting variables for Snowflake in sqitch add command?

### ISSUE THREAD

**Issue by lelando** [sqitchers/sqitch#530]
Hi,

I am looking to set variables in the sqitch add command via the [doc ](https://sqitch.org/docs/manual/sqitch-add/)using sqitch add --set test_var_name="test" but that doesnt seem to write the var anywhere and im not sure how to accomplish that. We are using Azure DevOps to deploy and need to change a snowflake stage URL based on environment. If I can inject it another way that may work for us too.

I saw that Snowsql CLI will allow variable substitution using the -D option as outlined in this question on the snowflake forums:
https://community.snowflake.com/s/question/0D50Z00008zOulRSAS/how-do-you-pass-variables-to-a-sql-script-using-snowsql-via-a-shell-script

Thanks for your time and we love this project so far!

**Comment by theory** [comment]
The `--set` option on [sqitch add](https://sqitch.org/docs/manual/sqitch-add/) is not for setting variables in the scripts it generates. It's for setting values to fill in variables in templates. If that interests you, check out [this post](https://justatheory.com/2013/09/sqitch-templating/) on templating, and [this one](https://justatheory.com/2014/01/templating-tests-with-sqitch/) on adding templates for additional files.

If what you want to do is use Snowflake variables, write them into your Snowflake deploy, revert, and verify scripts with an ampersand, as described in that post. Then, to pass values to them, pass them via the `--set` option to `deploy`, `revert`, and friends, or set them in your configuration file for the appropriate engine (snowflake in this case) or target. Have a look at [sqitch-configuration](https://sqitch.org/docs/manual/sqitch-configuration/) for details on configuration hierarchy, including the setting of variables to be passed to your scripts upon execution.

Also, please post questions to the [mail list](https://sqitch.org/community/), as we reserve GitHub issues for bug reports and feature requests. Thanks!
