### ISSUE TITLE
`sqitch checkout ...` fails when plan isn't in git root

### ISSUE THREAD

**Issue by kwakwaversal** [sqitchers/sqitch#535]
We store our sqitch plan in the folder `infrastructure/sql/sqitch.plan`. When using `git checkout` it fails to find the plan during the `git show` part of the `checkout` command.

https://github.com/sqitchers/sqitch/blob/1a41f3255e5053851289fc29ada6df7ee5510e1d/lib/App/Sqitch/Command/checkout.pm#L72-L81

I don't know what the fix would be in this case. The `git show` can be the absolute path or relative path. The problem is that there's no combination of `top_dir` and `plan_file` that works as changing them both interfere with the typical sqitch functionality in other commands.

I've figured out a hack that works for me, but as default it won't work for others.

It involves setting the `plan_file` to `./sqitch.plan` allowing `git show master:./sqitch.plan` to work as long as `sqitch checkout` is run from within the directory `infrastructure/sql` in my instance.

I don't know what the permanent fix would be. Perhaps another optional argument to `sqitch checkout` called `--plan_file_git` which could override the `plan_file` in the snippet above?

**Comment by theory** [comment]
I was just about to look into fixing this, and I think maybe I already did in a2c920545 in response to #560. Does that look right to you, @kwakwaversal?
