### ISSUE TITLE
sqitch-revert: Default should not be "all changes"

### ISSUE THREAD

**Issue by kbluck** [sqitchers/sqitch#541]
At the moment:

> All changes will be reverted unless a change is specified, either via --to or with no option flag, in which case changes will be reverted back to that change.

This seems very dangerous to me. Convenient for development, perhaps, easily disastrous for production targets.

I would suggest that there should be no default change for `sqitch-revert` at all. Whenever reverting, I propose that a specific change should always be required.

If there really must be a default change to revert, it should be `@HEAD^`

Reverting literally all changes should be somewhat inconvenient, and have to be specified explicitly:
`sqitch revert --change @ROOT^ <target>`

**Comment by theory** [comment]
Production targets should probably avoid `sqitch revert`. By default, in the event of a deployment failure, Sqitch will revert back to where it started. If you want a different behavior, pass the `--mode` [option](https://sqitch.org/docs/manual/sqitch-deploy/#options) to `sqitch-deploy`. For example, to have the deploy command revert nothing on a failure, pass `--mode change`. If you want it to be the default set `sqitch config deploy.mode change`.

**Comment by Kinrany** [comment]
Reverting all changes explicitly with `@ROOT^` does not work by the way. I think that makes it impossible to use `deploy.mode change` at the same time with reverting all changes?

**Comment by theory** [comment]
`@ROOT^` is not necessary; just omit the change to revert to and Sqitch will revert them all:

``` console
❯ sqitch deploy
Adding registry tables to db:pg:david
Deploying changes to db:pg:david
  + appschema ................. ok
  + users ..................... ok
  + insert_user ............... ok
  + change_pass @v1.0.0-dev1 .. ok
  + lists ..................... ok
  + insert_list ............... ok
  + delete_list ............... ok
  + flips ..................... ok
  + insert_flip ............... ok
  + delete_flip @v1.0.0-dev2 .. ok
  + pgcrypto .................. ok
  + insert_user ............... ok
  + change_pass ............... ok

sqitch-intro on  main 
❯ sqitch revert -y
Reverting all changes from db:pg:david
  - change_pass ............... ok
  - insert_user ............... ok
  - pgcrypto .................. ok
  - delete_flip @v1.0.0-dev2 .. ok
  - insert_flip ............... ok
  - flips ..................... ok
  - delete_list ............... ok
  - insert_list ............... ok
  - lists ..................... ok
  - change_pass @v1.0.0-dev1 .. ok
  - insert_user ............... ok
  - users ..................... ok
  - appschema ................. ok
```
