### ISSUE TITLE
upgraded via brew and now things don't work

### ISSUE THREAD

**Issue by pyramation** [sqitchers/sqitch#542]
Recently, `brew` automatically upgraded some packages and something complained saying that things had been changed to main from master, so I upgraded it. I should have probably captured the error message, but I just brew uninstall and then brew install sqitch again.

Now, I cannot use sqitch. Previously, I never had to manually install anything like this, but now I'm getting an error that this is missing:

```
DBD::Pg 2.0 required to manage PostgreSQL
```

Should this be included in the brew install? or is this expected?

**Comment by theory** [comment]
Forgot `--with-postgres-support`, @pyramation? :-D

Bugs for homebrew should go to sqitchers/homebrew-sqitch BTW.

**Comment by pyramation** [comment]
Yea sorry, that's why I closed it ;) Thanks for the tip!
