### ISSUE TITLE
How does sqitch compare to flyway?

### ISSUE THREAD

**Issue by gajus** [sqitchers/sqitch#543]
I have not found any resources that provide side by side comparison of how these tools perform.

It would be extremely valuable to have a table such as this in documentation (and it would drive a lot of people to discover Sqitch when others are searching for alternatives to Flyway).

It could start as a conversation in this issue thread and be later summarised in a markdown table.

I tried asking on Reddit, but didn't get a lot of answers.

https://www.reddit.com/r/PostgreSQL/comments/igq1m8/if_you_have_used_flyway_and_sqitch_can_you_share/

**Comment by theory** [comment]
A [similar question in 2018](https://groups.google.com/forum/#!searchin/sqitch-users/flyway%7Csort:date/sqitch-users/Asox0J51LCs/g1VkZStWCgAJ) didn't get much of a response, but perhaps it'd be worthwhile to ask on the Sqitch and Flyway mail lists again.
