### ISSUE TITLE
V1.1.1 docker image is not available

### ISSUE THREAD

**Issue by mzaatar** [sqitchers/sqitch#545]
Hey,

Thanks for the great tool. We are using in one of products and wondering when will v1.1.1 be available on cpan and docker?

I couldn't find a way to contribute to upgrading Sqitch in CPAN and docker? I assume that should be done by the core team only.

Any plans to release v1.1.1 in the near future?

**Comment by theory** [comment]
I haven't made any plans. Is there something you need urgently?

**Comment by mzaatar** [comment]
Nothing specific in my mind, it would be great if you are the plan for upgrades when you have them.

**Comment by theory** [comment]
V1.1.1 has not been released, and therefore neither has the docker image.
