### ISSUE TITLE
Sqitch v1.1.0. verify bug [mysql]

### ISSUE THREAD

**Issue by wyldone** [sqitchers/sqitch#547]
I am running Sqitch on a Windows 10 machine. Using mysql 8.0.19. I initially installed Sqitch using Strawberry Perl.

Every time I try to run verify scripts, the verify script fails. Every time my co-worker runs the same verify script on his machine that has Sqitch .9999 it works flawlessly.

We have both tried to diagnose the issue, and we have been able to narrow it down being a sqitch issue. As both our setups are the same except for the version of Sqitch we run. I am using the latest version of Sqitch 1.1.0.

Additional note: The checkit() function is part of the sqitch schema. 
```
CREATE DEFINER=`root`@`localhost` FUNCTION `checkit`(doit INTEGER, message VARCHAR(256)) RETURNS int
    DETERMINISTIC
BEGIN
    IF doit IS NULL OR doit = 0 THEN
        SIGNAL SQLSTATE 'ERR0R' SET MESSAGE_TEXT = message;
    END IF;
    RETURN doit;
END
```
When the checkit() function is run as a standalone query (in workbench) it return a value of 1 indicating that the checkit() function knows that particular schema exists. 

The error I get;
```
ERROR 1049 (42000): Unknown database 'verify\sp_upsert_dc_src.sql'
# Verify script "verify\sp_upsert_dc_src.sql" failed.
not ok
```

**Comment by ra1fee** [comment]
Additionally what is the best way to downgrade sqitch ? Here is my question on stackover flow. 
https://stackoverflow.com/questions/63947368/how-do-i-downgrade-sqitch

**Comment by theory** [comment]
Hrm. The only change relevant to the handling of the `mysql` client since v0.9999 is #485. Could you have variations in your `~/.my.cnf` files?

**Comment by ra1fee** [comment]
@theory could be a difference in my.cnf files, anything particular I should look out for in config file that may cause this issue?

**Comment by theory** [comment]
Perhaps a password set to an empty string? I don't really know, diff the two of them to see what varies.

**Comment by ra1fee** [comment]
Thanks.

**Comment by theory** [comment]
Did you find the issue?

**Comment by ra1fee** [comment]
No I did not. Even after a clean install of mysql on my machine, I am still unable to verify.

**Comment by theory** [comment]
Hang on, is it only verify that fails? Deploy and revert work?

**Comment by ra1fee** [comment]
@theory yes that is correct.

**Comment by theory** [comment]
That’s bizarre.

**Comment by ra1fee** [comment]
It does not work either way I try.

**Comment by ra1fee** [comment]
Additionally, my co-worker has been facing similar issues since he upgraded to the latest version as well. 

He gets; 
`ERROR at line 1: Unknown command '\U'.`
when he trys to deploy in his local and remote machines. 

```
# Verify script "C:\Users\username\Documents\Repo\project\sql\verify\change.sql" failed.
not ok
```
when he tries to verify in his local and remote machines as well. So I can say without a doubt this is not an isolated issue. 

Also when he runs the same script from the docker image it works just fine.

**Comment by theory** [comment]
What's at line 1 of `C:\Users\username\Documents\Repo\project\sql\verify\change.sql`? Could it be that `\U` is supported by some versions of the MySQL client and not others?

**Comment by ra1fee** [comment]
Ill check with him and let you know, he is on vacay.

**Comment by theory** [comment]
Hi @ra1fee, were you able to get to the bottom of this issue?
