### ISSUE TITLE
Not able to use --merge option with deploy

### ISSUE THREAD

**Issue by kenneth-go** [sqitchers/sqitch#550]
Hey all, first time user, first time writer. I saw this comment in a previous issue describing a new --merge option to merge a registry with a modified plan: https://github.com/sqitchers/sqitch/issues/200#issuecomment-68946425

Has this option come to fruition? It looks like it's not documented under sqitch deploy either.

**Comment by theory** [comment]
No it has not. Please refer to #200 for details. If you have other questions, please send them to the [mail list](https://sqitch.org/community/).
