### ISSUE TITLE
SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by ltamrazov** [sqitchers/sqitch#553]
Hi, 

We are trying to run a fairly heavy migration with sqitch, populating a DB table. Its resulting in what seems like a timeout. However the same query completes fine when we ran it through PgAdmin4. The error trace we get is:

```
Deploying changes to db:postgres://{user}{password}@{host}:5432/{db}
  + migration1 .. ok
  + migration2 ................ psql:deploy/migration2.sql:13: SSL SYSCALL error: EOF detected
psql:deploy/populate_image_count.sql:13: connection to server was lost
Execution of finally() block CODE(0x557df1537b20) resulted in an exception, which *CAN NOT BE PROPAGATED* due to fundamental limitations of Perl. Your program will continue as if this event never took place. Original exception text follows:

no connection to the server
DBD::Pg::db commit failed: no connection to the server
Trace begun at /usr/local/share/perl5/site_perl/App/Sqitch/Role/DBIEngine.pm line 985
App::Sqitch::Role::DBIEngine::finish_work('App::Sqitch::Engine::pg=HASH(0x557df05a2ff0)', 'App::Sqitch::Plan::Change=HASH(0x557df07ad130)') called at /usr/local/share/perl5/site_perl/App/Sqitch/Engine.pm line 973
App::Sqitch::Engine::finally {...} ('"psql" unexpectedly returned exit value 2^J') called at /usr/local/share/perl5/site_perl/Try/Tiny.pm line 179
eval {...} at /usr/local/share/perl5/site_perl/Try/Tiny.pm line 181
Try::Tiny::ScopeGuard::DESTROY('Try::Tiny::ScopeGuard=ARRAY(0x557df15380f0)') called at /usr/local/share/perl5/site_perl/Throwable.pm line 76
eval {...} at /usr/local/share/perl5/site_perl/Throwable.pm line 76
Try::Tiny::try('CODE(0x557df154d670)', 'Try::Tiny::Finally=REF(0x557df1537cd0)', 'Try::Tiny::Catch=REF(0x557df15dbc08)') called at /usr/local/share/perl5/site_perl/App/Sqitch/Engine.pm line 978
App::Sqitch::Engine::deploy_change('App::Sqitch::Engine::pg=HASH(0x557df05a2ff0)', 'App::Sqitch::Plan::Change=HASH(0x557df07ad130)') called at /usr/local/share/perl5/site_perl/App/Sqitch/Engine.pm line 878
App::Sqitch::Engine::try {...}  at /usr/local/share/perl5/site_perl/Try/Tiny.pm line 102
eval {...} at /usr/local/share/perl5/site_perl/Try/Tiny.pm line 93
Try::Tiny::try('CODE(0x557deeba1998)', 'Try::Tiny::Catch=REF(0x557df14caf98)') called at /usr/local/share/perl5/site_perl/App/Sqitch/Engine.pm line 8
App::Sqitch::Engine::_deploy_all('App::Sqitch::Engine::pg=HASH(0x557df05a2ff0)', 'App::Sqitch::Plan=HASH(0x557defd48ae0)', 2) called at /usr/local/share/perl5/site_perl/App/Sqitch/Engine.pm line 252
App::Sqitch::Engine::deploy('App::Sqitch::Engine::pg=HASH(0x557df05a2ff0)', undef, 'all') called at /usr/local/share/perl5/site_perl/App/Sqitch/Command/deploy.pm line 126
App::Sqitch::Command::deploy::execute(undef) called at /usr/local/share/perl5/site_perl/App/Sqitch.pm line 206
App::Sqitch::try {...}  at /usr/local/share/perl5/site_perl/Try/Tiny.pm line 100
eval {...} at /usr/local/share/perl5/site_perl/Try/Tiny.pm line 93
Try::Tiny::try('CODE(0x557defdeeb38)', 'Try::Tiny::Catch=REF(0x557defaf1418)') called at /usr/local/share/perl5/site_perl/App/Sqitch.pm line 226
App::Sqitch::go('App::Sqitch') called at /usr/local/bin/sqitch line 15

SSL SYSCALL error: EOF detected
Reverting all changes
  - add_image_count_column_to_listings .. no connection to the server
The schema will need to be manually repaired
Deploy failed
```

Are there any sort of timeout settings we can tweek? Or any other clues as to what the issue might be? Again this completes successfully when run on PgAdmin.

Thank you!

**Comment by ltamrazov** [comment]
Also just some context on the query:
- Updating a table with 800K rows
- Does a count look up on another table to populate the values
- Completes on PgAdmin in ~17min

**Comment by theory** [comment]
These lines:

```
  + migration2 ................ psql:deploy/migration2.sql:13: SSL SYSCALL error: EOF detected
psql:deploy/populate_image_count.sql:13: connection to server was lost
```

Show pretty clearly that the connection to Snowflake was lost while the script was running. The addition of these two lines:

```
no connection to the server
DBD::Pg::db commit failed: no connection to the server
```

Suggest that it wasn't just `psql` that lost the connection, so did the DBI. Could you have suffered a network outage or something?

As for timeout, try passing [`statement_timeout`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT) in the GET string:

```
sqitch deploy db:postgres://{user}{password}@{host}:5432/{db}?statement_timeout=300
```

Though it shouldn't be necessary unless you have a low value set somewhere else.

I don't typically suggest using Sqitch to add/insert/update/delete rows except for limited cases (such as a table listing countries in the world or months in a year). 800K rows is a lot!

**Comment by ltamrazov** [comment]
Thanks for prompt reply! I will try the `statement_timeout` setting and will report back.

Honestly I doubt its a network outage. I've tried running this many many times against a test DB on AWS. We tried running this from our local machines (onto AWS) as well as deploying this on AWS. 

Though if we run it against a local DB it works just fine...

I thought it might have been some setting on RDS, though then I would have expected it to fail when running through PgAdmin, but it succeeded.

Ya, its big update so this might not be a good pattern to begin with...

**Comment by theory** [comment]
Hwy @ltamrazov, have you made any progress on this issue?

**Comment by ltamrazov** [comment]
Hi @theory , sorry no resolution. But it might not be relevant. We realized doing such a large update is not really practical in production environments and ended up switching tools where we an paginate updates through code. Sorry, I should have followed up much sooner.

**Comment by theory** [comment]
Oh, so might have been an issue with the size of the change, eh?

**Comment by ltamrazov** [comment]
Ya, I think its definitely with the size of the change because like I said even locally it took ~17 min to execute. So my guess is its either a connection timeout or an interrupt, or something of that sort.
