### ISSUE TITLE
deploy hangs in case of too many warnings

### ISSUE THREAD

**Issue by DimitriyKh** [sqitchers/sqitch#554]
Hello, 

I've encountered with some issue trying to deploy to aurora v:2.09 with mysql engine v:5.7 and sqitch v:0.999.
Our deploy script issued an update statement that results in a 103 warning messages about Duplicate entry for unique key (which is tolerable for that specific case).
I've tried to execute the deployed script on copy of aurora cluster in workbench and it was done in 68 seconds.
but when I run it within sqitch deploy it hangs for ours and mysql processlist shows the query in state 'Sending data'
Once I've modified the script with "SET SQL_NOTES=0" command it was executed in sqitch without hang.

So I guess there's something wrong with processing of high amount of warnings.

**Comment by theory** [comment]
Sqitch passes the change scripts to the `mysql` client, which then handles errors; Sqitch just waits for the exit code. [Here's where Sqitch assembles options for the client](/sqitchers/sqitch/blob/b34cf8a2b8f337200b2b458a36f06c44f888e0e0/lib/App/Sqitch/Engine/mysql.pm#L162-L214); perhaps it disables or enables something unexpected to you?
