### ISSUE TITLE
[SNOWFLAKE] Object 'CHANGES' does not exist or not authorized. 

### ISSUE THREAD

**Issue by qqcvd** [sqitchers/sqitch#556]
Hello,
I have the following error during my first execution
Object 'CHANGES' does not exist or not authorized. (SQL-42S02)

I am really surprised because I can see the command in the QUERY_HISTORY in the database,
and I see the "use warehouse" and the "use schema" command in success, following by a SELECT request .... but no "create" request to create the CHANGES tables...

Is there a method to force the execution of the CREATE commands?

thaks in advance for your help
Regards
Steph

**Comment by theory** [comment]
Sqitch only creates the registry schema after it tries to query the changes table and it fails. It then create it. So it should create it after it hits that error. What command are you running?

**Comment by qqcvd** [comment]
I use the following command 
sqitch deploy 'db:snowflake://**********/***my db name***?Driver=SnowflakeDSIIDriver;warehouse=*** my warehouse***;role=*** my admin role ***' 


I can see the request in the log. there is a SELECT on the "changes" table which failed but it is ont followed by a "create" statement.

**Comment by qqcvd** [comment]
Hello
thanks for your help,

I got the solution.
My forst install was in 0.9999 version as I use apt-get
but today I installed the 1.1.0 version with cpanm command

And the bug disappeared
:-)
