### ISSUE TITLE
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

### ISSUE THREAD

**Issue by victorsteven** [sqitchers/sqitch#557]
When running sqitch in a docker compose I encounter the error:
migration_1  | could not connect to server: No such file or directory
migration_1  |  Is the server running locally and accepting
migration_1  |  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by theory** [comment]
What target URL are you using? Sounds like it's trying to connect from within the container, which has no Postgres running.
