### ISSUE TITLE
sqitch checkout in monorepo fails when PWD is deeper than root

### ISSUE THREAD

**Issue by francois** [sqitchers/sqitch#560]
Our repository is a monorepo, with applications stored similarly to this:

```
.
├── backend
│   ├── crds-rails
│   ├── partner-rails
│   ├── sharethebus-rails
│   └── vishnu
├── shared
│   ├── gems
│   └── protos
```

`sharethebus-rails` and the other directories at the same level essentially have the same structure:

```
.
├── app
│   ├── models
├── db
│   ├── deploy
│   ├── migrate
│   ├── revert
│   ├── sqitch.plan
│   ├── structure.sql
│   └── verify
├── sqitch.conf
```

PWD was `backend/sharethebus-rails`. I expected to be able to `sqitch checkout` to another branch, but stumbled upon something Sqitch didn't expect:

```
$ sqitch checkout improve-development-environment-reproducibility
fatal: path 'backend/sharethebus-rails/db/sqitch.plan' exists, but not 'db/sqitch.plan'
hint: Did you mean 'improve-development-environment-reproducibility:backend/sharethebus-rails/db/sqitch.plan' aka 'improve-development-environment-reproducibility:./db/sqitch.plan'?
"git" unexpectedly returned exit value 128
```

I tried to init from the top-level, but then adding a change whiel PWD is `backend/sharethebus-rails` fails with:

```
$ sqitch init --top-dir backend/sharethebus-rails/db --uri https://github.com/Bus-com/sharethebus-rails/tree/master/backend/sharethebus-rails --engine pg sharethebus-rails
$ cd backend/sharethebus-rails
$ sqitch add -n Initial initial_transfer
Plan file backend/sharethebus-rails/db/sqitch.plan does not exist
```

My ideal case would be to fix the first scenario, where I have multiple sqitch.conf and sqitch.plan, one per project, and improve the ability of `sqitch checkout` to handle non-root directories when changing branch.

Here's a self-contained reproduction recipe:

```sh
#!/bin/bash
set -eu

( dropdb -h localhost repro || exit 0 ) && createdb -h localhost repro
rm -rf repro
git init -b main repro
cd repro
mkdir -p projects/{a,b}/db
cd projects/a
sqitch init --top-dir db --engine pg a
sqitch target add dev db:pg://localhost/repro
sqitch add initial_transfer -n "x"
cat <<EOF > db/deploy/initial_transfer.sql
BEGIN;
  CREATE TABLE a(id bigint generated always as identity);
COMMIT;
EOF
cat <<EOF > db/revert/initial_transfer.sql
BEGIN;
  DROP TABLE a;
COMMIT;
EOF
sqitch deploy dev
cd ../..
touch projects/b/db/.gitkeep
git add --all .
git commit --message "initial commit"

# Start new feature branch
git switch -c feature-cookie
cd projects/a
sqitch add -n "x" tables/cookies
cat <<EOF > db/deploy/tables/cookies.sql
BEGIN;
  CREATE TABLE cookies(id bigint generated always as identity);
COMMIT;
EOF
cat <<EOF > db/revert/tables/cookies.sql
BEGIN;
  DROP TABLE cookies;
COMMIT;
EOF
sqitch deploy dev
cd ../..
git add --all .
git commit -m "cookies feature"

# This is expected to succeed and remove the cookies table
cd projects/a
echo
echo "================== EXPECTED NOT TO FAIL"
sqitch checkout main
```

**Comment by francois** [comment]
I wonder if it would be as simple as applying this:

```diff
diff --git a/lib/App/Sqitch/Command/checkout.pm b/lib/App/Sqitch/Command/checkout.pm
index d200be2b..0e4bdf3c 100644
--- a/lib/App/Sqitch/Command/checkout.pm
+++ b/lib/App/Sqitch/Command/checkout.pm
@@ -76,7 +76,7 @@ sub execute {
         target => $target,
       )->parse(
         # XXX Handle missing file/no contents.
-        scalar $sqitch->capture( $git, 'show', "$branch:" . $target->plan_file)
+        scalar $sqitch->capture( $git, 'show', "$branch:./" . $target->plan_file)
     );
 
     # Find the last change the plans have in common.
```

Maybe there are other places where we would need to apply this logic, but this changed is based on a hint Git gives us:

> hint: Did you mean 'improve-development-environment-reproducibility:backend/sharethebus-rails/db/sqitch.plan' aka 'improve-development-environment-reproducibility:./db/sqitch.plan'?

What do you think?

**Comment by theory** [comment]
It looks like `git show` supports relative paths only from the root, but not from a subdirectory. I can replicate this easily in the Sqitch repo itself:

```
$ cd lib
$ git show main:sqitch.pod 
fatal: path 'lib/sqitch.pod' exists, but not 'sqitch.pod'
hint: Did you mean 'main:lib/sqitch.pod' aka 'main:./sqitch.pod'?
```

Seems odd that it knows in the hint exactly which file I mean, but doesn't default to it. I tried passing `--relative`, but it didn't help, sadly. [The manual explains how it works](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltrevgtltpathgtemegemHEADREADMEememmasterREADMEem). Seems like your suggested fix makes the most sense, though as a workaround you ca change the path to the plan file in `sqitch.conf` to use the `./` prefix.
