### ISSUE TITLE
Problem with deploy sqitch changes

### ISSUE THREAD

**Issue by ArtemiusSnape** [sqitchers/sqitch#563]
I using Windows 10. 
try using sqitch for mysql database. Using SQITCH_PASSWORD variable for authentication.
After run command
`sqitch deploy --db-host <my_host> -u sqitch_user`
I get this error
"sqitch" failed to start: "The system cannot find the file specified"
But interesting I try testing my updates for Snowflake and it is working

**Comment by theory** [comment]
Make sure you have [DBD::mysql](https://metacpan.org/release/DBD-mysql) installed. Please post other questions and requests for help to the [mail list](https://sqitch.org/community/), where there are more folks who might be familiar with your situation. Thanks.
