### ISSUE TITLE
HOW TO ADD MULTIPLE SCRIPTS TO SQITCH.PLAN ??

### ISSUE THREAD

**Issue by nags28** [sqitchers/sqitch#566]
My question is I have multiple SQL files  I want to deploy all the files to snowflake using sqitch.
Currently, consider the folder structure has below:
deploy/sql/a.sql,b.sql,c.sql 
my question is how to add all the SQL file in a plan at the same time.

**Comment by Ovid** [comment]
Hi nags28. Can you be more specific? Do you mean, "how to add multiple changes"? If so, you do it one changes at at time:

```
sqitch add some_change
# edit the files
sqitch deploy
sqitch add another_change
# edit the files
sqitch deploy
```

And so on. However, I have a feeling that's not what you're asking for.

**Comment by theory** [comment]
You might also want to post your question to the mail list, as [GitHub issues](https://sqitch.org/community/) are reserved for issue tracking.
