### ISSUE TITLE
HOW TO ADD MULTIPLE SCRIPTS TO SQITCH.PLAN ??

### ISSUE THREAD

**Issue by nags28** [sqitchers/sqitch#567]
![image](https://user-images.githubusercontent.com/46648905/110312730-7e8c3900-802b-11eb-9caa-a6a5c32eb1ba.png)

![image](https://user-images.githubusercontent.com/46648905/110312902-bb583000-802b-11eb-88bc-d7adc5cc50ca.png)

My question is I have multiple SQL files I want to deploy all the files to snowflake using sqitch.
Currently, consider the folder structure has above image
I want to deploy functions, views, incremental-ddl all the SQL files to snowflake using sqitch.
how to I add them to in the plan ???

**Comment by theory** [comment]
Have you read [the tutorial](https://sqitch.org/docs/manual/sqitchtutorial-snowflake/)? You might find it helpful. Your deploy files will need to go in the deploy folder.

Please feel free to join the [mail list](https://sqitch.org/community/) and post questions there. Thank you!
