### ISSUE TITLE
Best practice in dropping a view that has been created as part of a prior tag

### ISSUE THREAD

**Issue by dlawrences** [sqitchers/sqitch#572]
Hey team

I was wondering what would your recommendation be in terms of dropping a view that has been created earlier as a sqitch change and is already part of a tag?

The route we went for now is to `rework` the change and:
- updated the revert script to contain the `CREATE OR REPLACE VIEW` script that the initial deploy script presented
- updated the deploy script to contain `DROP VIEW IF EXISTS`
- updated the verify script to crash if the view hasn't been dropped

In general, I am trying to assess whether there is a more direct and cleaner way to remove some change that was already tagged if it is not needed anymore. I know sqitch support the `--conflicts` argument on both `sqitch add` and `sqitch rework`, but I am not sure whether there is any logic built around this or whether the argument is only used to add a comment in the deploy script to let the developer know of the conflict.

Thoughts?

Thanks

**Comment by theory** [comment]
Hi @dlawrences. In general, questions like this are best sent to the mail list ([subscription info](https://sqitch.org/community/), but your approach is exactly how I would do it, except that I would use `DROP VIEW IF EXISTS` only if `CREATE OR REPLACE VIEW` isn't viable (e.g., you're changing the columns).
