### ISSUE TITLE
Can not install from cpan on fedora 32.

### ISSUE THREAD

**Issue by hansbretscher** [sqitchers/sqitch#576]
Hello,
I tried to evaluate the use of squitch for a postgresql database, but fail at installing the tool.
I tried installation according to http://sqitch.org/download/redhat/ It worked until the last step, where I get:
````
jbr@AIRA-207:~$ cpanm --notest App::Squitch
! Finding App::Squitch on cpanmetadb failed.
! Finding App::Squitch () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution App::Squitch
jbr@AIRA-207:~$
````
Do I need to configure anything that is not mentioned on above page? Or anything else I have to do to complete the install?

**Comment by theory** [comment]
Its `Sqitch`, not `Squitch`.

**Comment by hansbretscher** [comment]
Thank you.
I was pretty sure I just copied that line. Well, apparently I didn't.
