### ISSUE TITLE
If a plan contains a change multiple times after the latest valid tag and you try adding a target, the operation completes and fails with a weird error

### ISSUE THREAD

**Issue by dlawrences** [sqitchers/sqitch#577]
Say you have the following plan (that has been modified manually in an incorrect manner):

```
change1 2021-04-01T12:18:21Z UserName <user@domain.com> # added change1
change2 2021-04-01T12:18:21Z UserName <user@domain.com> # added change2
change3 2021-04-01T12:18:21Z UserName <user@domain.com> # added change3
@v1.0.0 2021-04-29T08:22:49Z UserName <user@domain.com> # Some tag
change1 [change1@v1.0.0] 2021-05-04T09:40:44Z UserName <user@domain.com> # reworked change1
change1 [change1@v1.0.0] 2021-05-04T10:40:44Z UserName <user@domain.com> # reworked change1 and slightly updated message
```

Then a command like:

```shell
sqitch target add someTargetName someTargetUri
```

will fail with the following error: `Cannot write a plan file without a project name`. Obviously, the plan above is not correct, but I believe the error handling here could be a little better. I guess we ended up here because the plan parsing has failed in some manner.

Thanks!

**Comment by theory** [comment]
That error described the issue exactly, but I imagine a bit of additional context would help. How about something like

   Cannot write a plan file without a project name but none found in sqitch.conf.

**Comment by theory** [comment]
Or perhaps

    Plan file corrupted: No project name found in sqitch.plan.

**Comment by theory** [comment]
Actually, I think I'll dupe the error from the plan file parser;

    Missing %project pragma in sqitch.plan
