### ISSUE TITLE
Deployment to single target gets registered for all targets

### ISSUE THREAD

**Issue by BoochParadise** [sqitchers/sqitch#578]
The issue happens on ubuntu using the docker container and connecting to a remote mysql database.  I've created a project, added a change, and added two targets.  Both targets are on the same database server, but are different schemas.  When I deploy the change to one target, and then check the status on the other target, both wind up having the change registered.  

root@ubuntu:/repo# sqitch target
US_AZIN85048_KO50
US_AZIN85215_JH8
root@ubuntu:/repo# sqitch status US_AZIN85048_KO50
# On database US_AZIN85048_KO50
No changes deployed
root@ubuntu:/repo# sqitch status US_AZIN85048_KO50
# On database US_AZIN85048_KO50
No changes deployed
root@ubuntu:/repo# sqitch deploy US_AZIN85048_KO50
Deploying changes to US_AZIN85048_KO50
  + 7.0.2 .. ok
root@ubuntu:/repo# sqitch verify US_AZIN85048_KO50
Verifying US_AZIN85048_KO50
  * 7.0.2 .. ok
Verify successful
root@ubuntu:/repo# sqitch status US_AZIN85215_JH8
# On database US_AZIN85215_JH8
# Project:  sspos
# Change:   a2fc694af96abfd813eb7d1e77ff34ee09374f7e
# Name:     7.0.2
# Deployed: 2021-05-25 02:23:04 +0000
# By:       root <root@ubuntu>
# 
Nothing to deploy (up-to-date)
root@ubuntu:/repo# sqitch verify US_AZIN85215_JH8
Verifying US_AZIN85215_JH8
  * 7.0.2 .. ERROR 1644 (ERR0R) at line 5 in file: 'verify/7.0.2.sql': column not modified
# Verify script "verify/7.0.2.sql" failed.
not ok

Verify Summary Report
---------------------
Changes: 1
Errors:  1
Verify failed

**Comment by theory** [comment]
On MySQL, Sqitch uses a separate schema (database) for the registry. If both of your target databases on on the same server, they will use the same registry. To record them separately, configure them to use separate registries. See [sqitch-target](https://sqitch.org/docs/manual/sqitch-target/) for details.
