### ISSUE TITLE
[Snowflake][Support] (50404) Invalid connection string. (SQL-HY000)

### ISSUE THREAD

**Issue by ankita61299** [sqitchers/sqitch#581]
Hi,
Am getting the error of
sqitch deploy db❄️//:@snowhouse/it?Driver=Snowflake;warehouse=it_data_ingest
[Snowflake][Support] (50404) Invalid connection string. (SQL-HY000)

**Comment by theory** [comment]
Please post a request for help to the mail list. See the [community page](https://sqitch.org/community/) for subscription information.
