### ISSUE TITLE
250001 (08001): Failed to connect to DB. Verify the account name is correct: BA0 "snowsql" unexpectedly returned exit value 1

### ISSUE THREAD

**Issue by PoojaSSahu** [sqitchers/sqitch#583]
Hi There, I am trying to run sqitch with snowflake after many unsuccessful attempt, I am looking for some help to resolve the snowsql connection issue from sqitch .

![image](https://user-images.githubusercontent.com/56446795/125775882-dea14fb2-997e-403f-ba1e-513c2ad2e980.png)

Please suggest next debug steps 

Thanks

**Comment by theory** [comment]
Moved to the mail list.
