### ISSUE TITLE
sqitch cannot find a change in sqitch.plan, however this change is not in the sqitch plan at all

### ISSUE THREAD

**Issue by schulzalbrecht** [sqitchers/sqitch#584]
## 1. background

My sqitch.plan: 

```
%syntax-version=1.0.0
%project=flipr
%uri=https://github.com/sqitchers/sqitch-mysql-intro/

appuser 2021-07-17T16:17:06Z Batman <bat@caverna.com> # Creates an application user.
users [appuser] 2021-07-17T21:01:50Z Batman <bat@caverna.com> # Creates table to track our users.
insert_user [users appuser] 2021-07-18T08:50:23Z Batman <bat@caverna.com> # Creates a function to insert users
change_pass [users appuser] 2021-07-18T08:51:52Z Batman <bat@caverna.com> # Creates a function to change a user password
@v1.0.0-dev1 2021-07-18T13:49:38Z Batman <bat@caverna.com> # Tag v1.0.0-dev1

fliprs [appuser users] 2021-07-19T18:54:01Z Batman <bat@caverna.com> # Add table for storing flips.
insert_flip [appuser users] 2021-07-19T19:26:03Z Batman <bat@caverna.com> # Insert records into flip table
delete_flip [appuser users] 2021-07-19T19:26:33Z Batman <bat@caverna.com> # Delete records into flip table
products [appuser users] 2021-07-20T20:11:21Z root <root@CH5CG01444YC> # Add table for storing products
@v1.0.0-dev2 2021-07-21T17:54:18Z Batman <bat@caverna.com> # Tag v1.0.0-dev2
```` 

When i run `$ sqitch status`, i get the below error:
```
# On database flipr_test2
# Project:  flipr
# Change:   9eb5bd5880d67e14232aab5b6cf205500829de8d
# Name:     delete_insert_user
# Deployed: 2021-07-22 21:17:31 +0200
# By:       root <root@CH5CG01444YC>
#
Cannot find this change in sqitch.plan
Make sure you are connected to the proper database for this project.
```

## 2. how did i get to this error?

1. I created the scripts to delete the insert user
2. I deployed the scripts
3. I deleted all the scripts from my working directory with `$ git resert --hard <last-commit>`

## 3. comments 

I get it that I removed the *revert* script and therefore sqitch lost the link between the changes and the current state of the database. 

To try to solve this, I created a new database (*flipr_test2*) then and run `$ sqitch deploy` to start everything from scratch; however, I stil get the same error. 

It seems that sqitch is holding a reference of the changes somewhere else, and not only in the *sqitch.plan*. Based on that, it seems to be a bug, that's why I'm openning the issue here. 

Thanks

**Comment by theory** [comment]
This error will happen if you change the plan file entries for values prior to the last deployed change, for example by changing the description or name of a change. In your case, it sounds like you added a change to delete users, deployed that change, then deleted it. If you run `sqitch log`, you'll see that change as the most recently deployed, and Sqitch expects it to always be there. If it's not there, why deploy it?

If your goal was to make a change without keeping a record of that change, I think you'd be better off by either making the change manually yourself, or else reverting to the change before the change that makes the thing you want changed, edit its scripts, then deploy again. But only do this during development, never for a released plan.
