### ISSUE TITLE
Sqitch deploy error - "snowsql" unexpectedly returned exit value 5

### ISSUE THREAD

**Issue by sfc-gh-stekavade** [sqitchers/sqitch#586]
I'm trying to deploy SQL code sqitch using SnowSQL and my sqitch deploy command fails with below error. Any help would be really appreciated. Thanks
```
+ cd TestCode_Folder
+ sqitch deploy db:snowflake ://sqitch_user:****@myaccount/mydb?Driver=Snowflake
Adding registry tables to db:snowflake ://sqitch_user:@myaccount.snowflakecomputing.com/it?Driver=Snowflake
003001 (42501): SQL access control error:
Insufficient privileges to operate on database 'mydb'
"snowsql" unexpectedly returned exit value 5
```

FYI - 'sqitch_user' has all the privileges on database mydb and I checked it via logging into Snowflake UI.  We are able to connect our snowflake account via SnowSQL manually but it's failing via Sqitch

**Comment by theory** [comment]
Continuing conversation in #524.
