### ISSUE TITLE
Exasol 7.1.0 not working due to SSL certificate enabled by default

### ISSUE THREAD

**Issue by tglunde** [sqitchers/sqitch#588]
In exasol.pm the command line for exaplus is being setup:
line 62-29
```
        for my $spec (
            [ u => $self->username ],
            [ p => $self->password ],
            [ c => $uri->host && $uri->_port ? $uri->host . ':' . $uri->_port : undef ],
            [ profile => $uri->host ? undef : $uri->dbname ]
        ) {
            push @ret, "-$spec->[0]" => $spec->[1] if $spec->[1];
        }

```

ODBC calls work when passing fingerprint or using SSLCertificate=SSL_VERIFY_NO parameter to the URI. But somehow the exaplus call fails with SSL verification failure - regardless which options I configure.

I unfortunately do not know perl - could somebody help us out and add the correct parsing of the additional parameters?

Tried:
Entry in ~/odbc.ini and cmd: sqitch deploy --target 'db:exasol:dvb'
exaplus fails with 'Profile dvb not found' --> it seems odbc named connection is not supported - even if I try to create the profile - exaplus fails with ' TLS connection error'

Using URI with SSL turned off (odbc call succeeds - exaplus fails):
```
sqitch deploy 'db:exasol://sys:xxxx@li2046-155.members.linode.com:8563/?Driver=Exasol&SSLCertificate=SSL_VERIFY_NONE'
Adding registry tables to db:exasol://sys:xxxx@li2046-155.members.linode.com:8563/?Driver=Exasol&SSLCertificate=SSL_VERIFY_NONE
Error: [08001] java.io.IOException: TLS connection to host (li2046-155.members.linode.com) failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. If you trust the server, connect to it using the fingerprint: 5B55FEBC379EA9EC7678B7ADA15B7344300FFDF6937689570A47410A729266D3. 

exaplus unexpectedly failed; exit value = 2
```

Using URI with fingerprint after hostname (odbc call succeeds - exaplus fails):
```
sqitch --chdir /repo/exasol deploy --verify --target 'db:exasol://sys:xxxx@li2046-155.members.linode.com:8563/?Driver=Exasol&SSLCertificate=SSL_VERIFY_NONE' --set PWD=start123
Adding registry tables to db:exasol://sys:@li2046-155.members.linode.com:8563/?Driver=Exasol&SSLCertificate=SSL_VERIFY_NONE
Error: [08001] java.io.IOException: TLS connection to host (li2046-155.members.linode.com) failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. If you trust the server, connect to it using the fingerprint: 5B55FEBC379EA9EC7678B7ADA15B7344300FFDF6937689570A47410A729266D3. 

/bin/exaplus unexpectedly failed; exit value = 2
```

Thank you!

Torsten

**Comment by theory** [comment]
Sounds like we need to detect the value of `SSL_VERIFY_NONE` and do something with it for exaplus. Can you tell me what should be passed to exaplus? Should we pass `-encryption OFF` for `SSLCertificate=SSL_VERIFY_NONE`?

**Comment by tglunde** [comment]
Hi,
somebody over in exasol community suggested this solution:
`        push @ret => (
            '-q',                       # Quiet mode
            '-L',                       # Don't prompt if login fails, just exit
            '-pipe',                    # Enable piping of scripts to 'exaplus'
            '-x',                       # Stop in case of errors
            '-autoCompletion' => 'OFF',
            '-encoding' => 'UTF8',
            '-autocommit' => 'OFF',
            '-jdbcparam'  => 'validateservercertificate=0',
        );`

Perhaps I can try that myself...

**Comment by ilikutle** [comment]
@theory Hello, as my colleague @tglunde already said, this might be worth trying (mentioned here: [EXASOL 2936](https://www.exasol.com/support/browse/EXASOL-2936)) but we would need assistance in executing Perl code to test it out. Would you be able to help?

**Comment by theory** [comment]
Yeah I'll care some time out this weekend. I assume the idea is to add `'-jdbcparam'  => 'validateservercertificate=0',` if `SSLCertificate=SSL_VERIFY_NONE` is in the URL, yes?

**Comment by theory** [comment]
I believe 9b61e461 will do the trick, but it may also be that you can use the fingerprint in the URL as-is. If I'm reading [the ODBC docs correctly](https://docs.exasol.com/connect_exasol/drivers/odbc/using_odbc.htm), the fingerprint is used instead of the database name. Have you tried this?

```
sqitch deploy 'db:exasol://sys:xxxx@li2046-155.members.linode.com:8563/5B55FEBC379EA9EC7678B7ADA15B7344300FFDF6937689570A47410A729266D3?Driver=Exasol'
```

**Comment by theory** [comment]
Actually that might not work, because Sqitch assumes the database name part of the URI is a profile name, but maybe the fingerprint could go into the profile? I'm out of my depth now.

**Comment by cdbassett** [comment]
I came across the same issue and thought I'd comment here what worked for me.

According to https://github.com/libwww-perl/uri-db which is the spec that db URIs follow, the "/" before the fingerprint means the fingerprint will be parsed as the db name. However, also according to that page, you can use a percent-encoded slash ("%2F") when a regular slash causes parsing problems. When I did this it worked for me.

So the new form should be:

db:exasol://sys:xxxx@li2046-155.members.linode.com%2F5B55FEBC379EA9EC7678B7ADA15B7344300FFDF6937689570A47410A729266D3:8563?Driver=Exasol

**Comment by theory** [comment]
So, uh, the fingerprint comes between the host name and the port, delimited by a slash after the host name and a colon before the port? That's not how URLs work but since the ODBC connection string is not a URL really, it sort of make sense, if a bit weird. But at any rate, yes, `%2f`-encoding the slash will let it work in Sqitch URLs, I think.

**Comment by theory** [comment]
Hi everyone. I tried updating to the Exasol 24 drivers, but started getting the TLS errors when connecting via ODBC. Following the [ODBC docs](https://docs.exasol.com/db/latest/connect_exasol/drivers/odbc/using_odbc.htm#fingerprint), I tried both

```
SSLCERTIFICATE=SSL_VERIFY_NONE&FINGERPRINT=NoCertCheck
```

And just

```
FINGERPRINT=NoCertCheck
```

Without success. You can see the error in [this build](https://github.com/sqitchers/sqitch/actions/runs/12539731661/job/34966152039):

```
    # [Exasol][Exasol Driver]Error in SSL_connect. SSL error code: 1 = SSL_ERROR_SSL    (SQL-HY000)
    # DBI connect('EXAHOST=127.0.0.1;EXAPORT=32768;Driver=Exasol;FINGERPRINT=NoCertCheck','sys',...) failed: [Exasol][Exasol Driver]Error in SSL_connect. SSL error code: 1 = SSL_ERROR_SSL    (SQL-HY000)
```

Any suggestions? TIA!

**Comment by theory** [comment]
Ah, it turned out that the Exasol service hadn't finished starting, even though the GitHub workflow services startup bit reports it as ready:

```
Waiting for all services to be ready
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 320ffbaab4372741a3639fb4c2e6de089d2776b400745a57cdcf6f77843e09f4
  exasol service is healthy.
```

I fixed it by adding code to `t/exasol.t` to check error code `HY000` and try again for up to 30s before failing. 

May I suggest that the ODBC driver be updated to properly report connection failures, rather than a generic SQL error code and bits about an SSL_ERROR_SSL error?
