### ISSUE TITLE
Custom Registry is not working | postgresql

### ISSUE THREAD

**Issue by kapil1699** [sqitchers/sqitch#593]
I tried to set registry under engine in sqitch.conf and also sqitch deploy --registry test but it is always failed with permission.

I have full permisson test schema. I created table,drop table using pgadmin and it is working fine.

Not sure what is missing.

Note: My postgres database is in AWS.

I tried with my local postgres and custom registry is working fine.only with aws postgres,it is not working.

Could you please assist.

**Comment by kapil1699** [comment]
Do we need user to have create schema grant?

I have error at perl/site/lib/App/Sqitch/Engine/pg.sql:4: Error Permission denied

Wheb i check pg.sql, i found below line..

CREATE SCHEMA IF NOT EXISTS :"registry";

**Comment by kapil1699** [comment]
What are the required permissions to create registry tables in postgresql?

**Comment by theory** [comment]
I believe it's `GRANT CREATE ON DATABASE`. But you can also create the schema yourself ahead of time. Make sure the sqitch user has the privileges to create objects in that schema.
