### ISSUE TITLE
How does `sqitch rework` actually work?

### ISSUE THREAD

**Issue by Kinrany** [sqitchers/sqitch#594]
To be more precise, what does `sqitch deploy` do when it finds two changes with the same name, one of them with a tag?

After reading [the docs](https://sqitch.org/docs/manual/sqitch-rework/) I expected it to be one of:

1. Merely a way to have two changes with the same name. Having N changes with the same name would result in N changes being deployed in the order specified in the plan file.
2. A way to replace an old change. Only the latest change would be deployed, possibly reverting the currently deployed version first.

However testing with a new project with two changes shows that `sqitch` tries to deploy both but starting with the **newer** change, not the older one.

```
$ sqitch status --target local
# On database local
# Project:  toy-sqitch-rework
# Change:   e31ac4da7527a2456422b80e184012790a77b460
# Name:     AddTable
# Tag:      @0.1
# Deployed: 2021-11-17 15:02:22 +0300
# By:       Ruslan Fadeev <ruslan.fadeev@showseeker.com>
#
Undeployed changes:
  * AddNote @0.2
  * AddNote
```

I struggle to understand how this behavior is intended to be used.

**Comment by theory** [comment]
Have you read [this bit of the tutorial](http://sqitch.org/docs/manual/sqitchtutorial/#in-place-changes)?

Please post questions to the [mail list](https://groups.google.com/group/sqitch-users) rather than here. Thanks!

**Comment by Kinrany** [comment]
Thanks for the response.

I did read that bit several times. I think what's missing for me is the motivation behind the "You have to make changes like these" part.

Would the post here be an appropriate place to discuss this? https://groups.google.com/g/sqitch-users/c/uwxFTfPXZ0Y

**Comment by theory** [comment]
Sure.
