### ISSUE TITLE
Issue with 1.2.0 tarball on CPAN

### ISSUE THREAD

**Issue by gregoa** [sqitchers/sqitch#600]
The CPAN tarball for the v1.2.0 release seems to have an issue. It's almost 8MB in size, and 56MB unpacked, were most of the space is used by an interesting `local/` directory:
```
% du -sh App-Sqitch-v1.2.0/*      
4.0K	App-Sqitch-v1.2.0/Build.PL                   
124K	App-Sqitch-v1.2.0/Changes
4.0K	App-Sqitch-v1.2.0/LICENSE
4.0K	App-Sqitch-v1.2.0/LICENSE.md
204K	App-Sqitch-v1.2.0/MANIFEST
12K	App-Sqitch-v1.2.0/META.json
4.0K	App-Sqitch-v1.2.0/META.yml
4.0K	App-Sqitch-v1.2.0/README
12K	App-Sqitch-v1.2.0/README.md
8.0K	App-Sqitch-v1.2.0/bin
32K	App-Sqitch-v1.2.0/dist
128K	App-Sqitch-v1.2.0/etc
32K	App-Sqitch-v1.2.0/inc
1.9M	App-Sqitch-v1.2.0/lib
53M	App-Sqitch-v1.2.0/local
1.5M	App-Sqitch-v1.2.0/t
```

Looks like something like a complete `local::lib` installation slipped into the release tarball by accident :)

Cheers,
gregor

**Comment by theory** [comment]
Well that's embarrassing. Fixed in 32989b1b. Fortunately it doesn't look like [cpan indexed all the stuff](https://metacpan.org/dist/App-Sqitch), so that's good. I'll update the release here on GitHub.

**Comment by gregoa** [comment]
Thanks!

Unfortunately CPAN still has the old tarball with `local/` in it;¹ of course I can now grab the new tarball from GitHub but for others that might be less obvious, and having two tarballs of the same release with different content and size might be a bit confusing in general.

I don't know if CPAN/PAUSE allow replacing an existing tarball; or maybe a v1.2.1 fixup release would be the simplest way out …

¹ https://cpan.metacpan.org/authors/id/D/DW/DWHEELER/App-Sqitch-v1.2.0.tar.gz linked from https://metacpan.org/dist/App-Sqitch

**Comment by theory** [comment]
No, PAUSE is write-only. I'll look at release v1.2.1 once #599 gets merged.

**Comment by gregoa** [comment]
Perfect, thanks.

**Comment by theory** [comment]
v1.2.1 is now on CPAN.

**Comment by gregoa** [comment]
On Sun, 05 Dec 2021 12:55:32 -0800, David E. Wheeler wrote:

> v1.2.1 is now on CPAN.

Thanks!

Imported into our packaging repo; now we just need to package the new
requirement Algorithm::Backoff::Exponential but that's a different
story :)

Cheers,
gregor
