### ISSUE TITLE
Possible bug with locking on mysql

### ISSUE THREAD

**Issue by TBSliver** [sqitchers/sqitch#601]
Found an interesting bug when using on github actions with latest version (1.2.0)

basic setup is:

* spin up `mariadb:latest` as a service
* install App::Sqitch and DBD::mysql
* setup the target db using sqitch config --user target.my_setup.uri 'db:mysql://root:pass@127.0.0.1:$port/dbname'
* run `sqitch deploy my_setup`

On 1.2.0, I get an error of `Unknown database 'sqitch'`

Running it on 1.1.0 I get no issue and it creates the sqitch DB as needed

Only thing I can see thats changed is the new locking on mysql, I wonder if its exploding while trying to lock things?

**Comment by theory** [comment]
That is odd. Does it work if you comment-out the locking? You can "comment" it out by simply renaming `try_lock` in mysql.pm to something else (like `_try_lock`). That will disable the locking.

**Comment by ambs** [comment]
Hi, @theory 
I had the same problem.

I did what you suggested and I got into the next issue: Authentication plugin 'caching_sha2_password'.
What is strange, as for complaining on the locking it would need to authenticate first.

But trying to go ahead, in order to debug this, is there anywhere in sqitch configuration where I can configure SSL?
As far as I recall, this is just adding ssl option to DBD::mysql DSN: `mysql_ssl=1`

Thanks 
ambs

**Comment by theory** [comment]
So disabling `_try_lock` got you to the next failure? Odd that there is no error without disabling `_try_lock`.

Try adding `?mysql_ssl=1` to the target URI.

**Comment by ambs** [comment]
Got some more info.

I am not sure what is used if you do not specify a `client` path...
I was unable to make it work with the `?mysql_ssl=1` parameter

But then I just realized that using `mysql` in the command line I do not need any special parameter.
So, I specified the `client` path in `sqitch.conf` and I got authenticated.

Got back and recovered `try_lock` (after dropping the `sqitch` database), and it is still complaining on the database not existing.

As a side note that might be relevant.
I am using Oracle's `mysql`, version 8.

At the moment I got it working for me, but I am happy to help debugging whatever you need.
ambs

**Comment by ambs** [comment]
And yes, it's quite strange that the authentication failure did not show with `try_lock`. 
ambs

**Comment by theory** [comment]
Okay, so it's working, but with the locking bit disabled? Without that it created the `sqitch` database?

Is `mysql` in your path?

**Comment by theory** [comment]
The CI/CD tests run fine against MySQL 8, most recently [here](/sqitchers/sqitch/runs/7063599277?check_suite_focus=true), so I wouldn't think that would be an issue…

**Comment by ambs** [comment]
Yeah, `mysql` is in `/usr/bin/mysql`, in my path, and yes, with locking disabled, it created the `sqitch` database.

**Comment by ambs** [comment]
When you think things can't be stranger...

```
$   sqitch status
# On database db:mysql://root:@127.0.0.1:3306/MediaDB
Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection.
$   mysql -u root -p -P 3306 -h 127.0.0.1
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 8.0.29 MySQL Community Server - GPL
[...]
mysql> ^D
$   sqitch status
# On database db:mysql://root:@127.0.0.1:3306/MediaDB
No changes deployed
```

Isn't programming a joy?

**Comment by theory** [comment]
I am so mystified. What OS and MySQL install are you using? I'd like to find a Docker image to try to replicate these issues.

**Comment by ambs** [comment]
I am so surprised as you. I have no cue where to look to find more answers.
I am running Linux Mint, mysql client version community, 8.0.29
The server is running in a docker image, binding port 3306, with image `mysql`. Noticed now that I did not specify any version, so it should be running `latest`.
Happy to help as far as you give me hints where you want me to look :)

**Comment by theory** [comment]
Good grief, _another_ Linux distro?  o_O [Doesn't look like mint is on Docker Hub](https://hub.docker.com/search?q=mint+linux). [Wikipedia says it's based on Ubuntu](https://en.wikipedia.org/wiki/Linux_Mint), so maybe I'll start there.

So, I created network and fired up mysql:

``` sh
docker network create -d bridge mysqlnet
docker run --net mysqlnet --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3306:3306 -d mysql:8-oracle
```

Then I ran Ubuntu and installed mysql-client with `apt-get`:

```
docker run -it --rm -net mysqlnet ubuntu:latest
apt-get update -qqy
apt-get install -qq mysql-client
```

Then checked the version:

```
$ mysql --version
mysql  Ver 8.0.29-0ubuntu0.22.04.2 for Linux on aarch64 ((Ubuntu))
```

Looks good so far. Let's install Sqitch. I ran these commands:

``` sh
apt-get -qq --no-install-recommends install less libperl5.34 perl-doc nano ca-certificates libdbd-mysql-perl
apt-get -qq install build-essential perl curl
curl -o cpanm http://cpanmin.us
chmod +x cpanm
./cpanm -notest App::Sqitch
```

And here is what we have:

```
perl -v

This is perl 5, version 34, subversion 0 (v5.34.0) built for aarch64-linux-gnu-thread-multi
(with 50 registered patches, see perl -V for more detail)

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

$ sqitch --version
sqitch (App::Sqitch) v1.2.1

$ perl -MDBD::mysql -E 'say DBD::mysql->VERSION'
4.050
```

Now let's give it a try.

``` sh
mkdir project
cd project
sqitch init flipr --engine mysql
sqitch add first-change -m 'First change'
mysql -h mysql -u root --execute 'CREATE DATABASE flipr_test'
```

Now we try it out!

```
$ sqitch status db:mysql://mysql/flipr_test
# On database db:mysql://mysql/flipr_test
No changes deployed

$ sqitch deploy db:mysql://mysql/flipr_test
Unknown database 'sqitch'
```

So, at least I've replicated the issue. Investigating…

**Comment by theory** [comment]
Commented out `try_lock` and it worked:

```
sqitch deploy db:mysql://mysql/flipr_test
Adding registry tables to db:mysql://mysql/sqitch
Deploying changes to db:mysql://mysql/flipr_test
  + first-change .. ok
```

So not sure what the client/path issue is you're having, @ambs, but I can work on trying to track this down at least.

**Comment by theory** [comment]
Okay, the problem is that Sqitch wants to create a lock in the `sqitch` database before it exists. This patch fixes the problem:

``` patch
--- a/lib/App/Sqitch/Engine.pm
+++ b/lib/App/Sqitch/Engine.pm
@@ -188,7 +188,6 @@ sub use_driver {
 
 sub deploy {
     my ( $self, $to, $mode ) = @_;
-    $self->lock_destination;
     my $sqitch   = $self->sqitch;
     my $plan     = $self->_sync_plan;
     my $to_index = $plan->count - 1;
@@ -237,6 +236,8 @@ sub deploy {
         $self->upgrade_registry;
     }
 
+    # Lock the destination and announce what we're about to do.
+    $self->lock_destination;
     $sqitch->info(
         defined $to ? __x(
             'Deploying changes through {change} to {destination}',
@@ -270,11 +271,13 @@ sub deploy {
 
 sub revert {
     my ( $self, $to ) = @_;
-    $self->lock_destination;
+
+    # Check the registry and, once we know it's there, lock the destination.
     $self->_check_registry;
+    $self->lock_destination;
+
     my $sqitch = $self->sqitch;
     my $plan   = $self->plan;
-
     my @changes;
 
     if (defined $to) {
```

You can also downgrade to v1.1.0, which did not have this issue, but does not take a lock before deploying to MySQL, either. Or you can manually create the `sqitch` database (or however it is named if you've changed it).

**Comment by ambs** [comment]
Hi, Thanks for that. Still not sure what is happening with the authentication, but will try to keep looking.
