### ISSUE TITLE
Deploying to production

### ISSUE THREAD

**Issue by bcb** [sqitchers/sqitch#603]
How should I deploy to a remote server?

Should I deploy from my local machine to the remote target?

I guess my only concern is having to expose a port to the database server, is this a valid concern?

**Comment by theory** [comment]
Good questions, but please post them to the [mail list](https://sqitch.org/community/), as issues are for problems and features with the source code. Thanks

**Comment by bcb** [comment]
Is it worth opening the Discussions tab here on GitHub?

**Comment by theory** [comment]
Yeah, I've been wondering about that but haven't broached it with the community, yet. Certainly not opposed, and would probably help.

**Comment by bcb** [comment]
Particularly for those who are still deciding if Sqitch is right for them, joining the mailing list is a commitment.
