### ISSUE TITLE
How to set Sqitch to build CI/DC pipeline for deploying Snowflake objects?

### ISSUE THREAD

**Issue by bhawnatyagi** [sqitchers/sqitch#606]
We are using sqitch framework for version control in our Snowflake environment. And while it works, it is not as smooth. Has anyone used Sqitch for deploying snowflake objects in dev and prod environment? If so, please share your ideas on how one can set up CI/CD pipeline and deploy objects in different environments.

Any help would be highly appreciated.

**Comment by theory** [comment]
Or perhaps post in the [GitHub discussions](/sqitchers/sqitch/discussions), which we've just opened up.
