### ISSUE TITLE
Create a Decent Site

### ISSUE THREAD

**Issue by theory** [sqitchers/sqitch#61]
Need an up-to-date site that includes:
- Intro
- Documentation
- Links to presentations, etc.
- Community links (mail lists, IRC, etc.)
- FAQ

Can perhaps make better use of GitHub pages…

**Comment by theory** [comment]
Nearly done with a new site now; preview at https://sqitchers.github.io. @stefansbv do you have a link for Sqitch GUI?

**Comment by stefansbv** [comment]
Just an old article on my personal site at http://stefansuciu.ro/2015/07/sqitch-gui-development/

**Comment by theory** [comment]
I'm gearing up to release v1.0.0 soon (and the new site). Do you think you'll have any TUITs to return to Sqitch-GUI and updated it?

**Comment by stefansbv** [comment]
I'm willing to continue developing the program, but I need some feedback on if/how it works on other computers and what are the potential users expect it to do. Obviously not all the commands and options can be implemented in a GUI.

Another problem is with the error messages, I did not find a way to disable the stack trace on database errors.

Another issue is with the error message output by sqitch when is run from a dir which is not a Sqitch project:
```
$ sqitch status
No engine specified; specify via target or core.engine
```
It should be something like: "You are not in a Sqitch project". for this I think it will need to define what a Sqitch project is, for example it has a `sqitch.plan` file and/or `deploy`, `verify` and `revert` dirs, but it has to be something that is there in the same place for every Sqitch project, regardless of the configuration.

**Comment by stefansbv** [comment]
@theory anyone who wants to test the app must be careful, it's early alpha state. I have found a nasty bug and disabled the Deploy button.

I will write a short guide of what and how to test.

**Comment by theory** [comment]
Closing, because the new site is about ready to launch. The project is [sqitch.org](/sqitchers/sqitch.org). Hope to get it started and delete the gh-pages branch soon.
