### ISSUE TITLE
Tutorial is wrong about the MySQL client location inside docker

### ISSUE THREAD

**Issue by juliusliunz** [sqitchers/sqitch#629]
The [Sqitch-MySQL Tutorial](https://github.com/sqitchers/sqitch/blob/develop/lib/sqitchtutorial-mysql.pod) states that the MySQL client location inside docker would be `/usr/local/mysql/bin/mysql`, however, when I peeked into the docker container (based on image `sqitch/sqitch:1.2.1`), I got these:
```ShellSession
I have no name!@matrix:~$ ls -la /usr/local
total 40
drwxr-xr-x 1 root root 4096 Apr 18 00:00 .
drwxr-xr-x 1 root root 4096 Apr 18 00:00 ..
drwxr-xr-x 2 root root 4096 Apr 18 00:00 bin
drwxr-xr-x 2 root root 4096 Apr 18 00:00 etc
drwxr-xr-x 2 root root 4096 Apr 18 00:00 games
drwxr-xr-x 2 root root 4096 Apr 18 00:00 include
drwxr-xr-x 2 root root 4096 Apr 18 00:00 lib
lrwxrwxrwx 1 root root    9 Apr 18 00:00 man -> share/man
drwxr-xr-x 2 root root 4096 Apr 18 00:00 sbin
drwxr-xr-x 1 root root 4096 May  3 01:32 share
drwxr-xr-x 2 root root 4096 Apr 18 00:00 src
I have no name!@matrix:~$ mysql --version
mysql  Ver 15.1 Distrib 10.5.15-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
I have no name!@matrix:~$ which mysql
/usr/bin/mysql
I have no name!@matrix:~$ 
```
For SQITCH_IMAGE from `0.9999` to `1.1.0` the first `sqitch deploy` would fail with the error message:
```ShellSession
"/usr/local/mysql/bin/mysql" failed to start: "No such file or directory"
```
The deploy succeeded only after I had changed `~/.sqitch/sqitch.conf` with the correct location:
```ini
[engine "mysql"]
	client = /usr/bin/mysql
```
The new conf won't help SQITCH_IMAGE `1.2.0` and up, the first deploy still fails with the message
`Unknown database 'sqitch'`, which I believe it's due to the issue #601.
I did not try other docker images before `0.9998 (inclusive)`. My host is Fedora 35, the MySQL server instance `v5.7.34` is living in another docker container and the full DBA access has been granted.

**Comment by theory** [comment]
The tutorial says:

> (don't bother if you're using the L<Docker image|https://hub.docker.com/r/sqitch/sqitch/> because it uses the client inside the container, not on your host machine)

Meaning you don't need to set the path when using the Docker image, because it's in the path inside the container.
