### ISSUE TITLE
Unknown MySQL server host 'xinwang' (-3)

### ISSUE THREAD

**Issue by oldman1991** [sqitchers/sqitch#642]
### Discussed in https://github.com/sqitchers/sqitch/discussions/641

<div type='discussions-op-text'>

<sup>Originally posted by **oldman1991** June 18, 2022</sup>
sqitch status db:mysql://xiwang:aqpthyYQ7EaUj#asa^UkFXy%^@database-dev.awas.us-east-5.rds.amazonaws.com:3306/test
return error ，Unknown MySQL server host 'xinwang' (-3)
Is there something wrong with my configuration?
</div>

**Comment by theory** [comment]
See #641 for the answer.
