### ISSUE TITLE
change requirements causing "duplicate key value violates unique constraint "dependencies_pkey"" on reapply

### ISSUE THREAD

**Issue by trycycler** [sqitchers/sqitch#671]
I used to add a requirement to one of my changes (ex `change2 [change1] 2022-08-17T17:30:00Z User Name <user@example.com> # Making change 2 which depends on change 1`) it works fine when I first apply it, but if I revert and reapply the changes (with no additional changes to the sqitch plan or sqitch change files), I get an error: duplicate key value violates unique constraint "dependencies_pkey". It's suggesting that the dependency is already there and can't be added again.

I am using sqitch 1.1

**Comment by theory** [comment]
Works in v1.3.0:

```
$ mkdir tmp
$ cd tmp
$ sqitch init issue-671 --engine pg
Created sqitch.conf
Created sqitch.plan
Created deploy/
Created revert/
Created verify/
$ sqitch add change1 -m 'First change'
Created deploy/change1.sql
Created revert/change1.sql
Created verify/change1.sql
Added "change1" to sqitch.plan
$ createdb issue671
$ sqitch deploy db:pg:issue671
Adding registry tables to db:pg:issue671
Deploying changes to db:pg:issue671
  + change1 .. ok
$ sqitch add change2 --requires change1 -m 'Change 2'
Created deploy/change2.sql
Created revert/change2.sql
Created verify/change2.sql
Added "change2 [change1]" to sqitch.plan
$ sqitch deploy db:pg:issue671
Deploying changes to db:pg:issue671
  + change2 .. ok
$ sqitch revert -y --to change1 db:pg:issue671
Reverting changes to change1 from db:pg:issue671
  - change2 .. ok
$ sqitch deploy db:pg:issue671
Deploying changes to db:pg:issue671
  + change2 .. ok
```

Switched to v1.1.0 and it still works:

```
$ sqitch deploy db:pg:issue671                  
Deploying changes to db:pg:issue671
  + change2 .. ok
$ sqitch revert -y --to change1 db:pg:issue671
Reverting changes to change1 from db:pg:issue671
  - change2 .. ok
$ sqitch deploy db:pg:issue671                
Deploying changes to db:pg:issue671
  + change2 .. ok
```

What version, exactly, are you using, with what database engine, and how was it installed?

**Comment by trycycler** [comment]
Version: sqitch (App::Sqitch) v1.1.0
It would have been installed with brew (`brew install sqitch --with-postgres-support`)
The db is up-to-date (ie `sqitch upgrade dev` returns `Registry dev is up-to-date at version 1.1`)

**Comment by theory** [comment]
What are the contents of the dependencies table after the revert?

**Comment by trycycler** [comment]
I can see the new record is still there after I revert the change:
"bae5e75b952f5adaaffcb909ef813936a547a567"	"require"	"@R5.0.4"	"bda00476bba2f64e08dc5cbebb5818f2f83968eb"

I can also see a lot of the other records for requiring @R5.0.4, even though I have removed all of those requirements from the plan, due to this bug.

**Comment by trycycler** [comment]
That example is via a tag, but I see the same behaviour if I reference the change name (instead of the tag)

**Comment by theory** [comment]
Well that's just odd. This is what I see:

```
$ sqitch revert -y --to change1 db:pg:issue671
Reverting changes to change1 from db:pg:issue671
  - change2 .. ok
$ psql issue671 -c 'select * from sqitch.dependencies'
 change_id | type | dependency | dependency_id 
-----------+------+------------+---------------
(0 rows)
```

Might you have some sort of rule or trigger defined to prevent the records from being deleted? In particular, there should be an `ON CASCADE DELETE` in the foreign key column, as in the `dependencies_change_id_fkey` declaration here:

```
psql issue671 -c '\d+ sqitch.dependencies'    
                                                      Table "sqitch.dependencies"
    Column     | Type | Collation | Nullable | Default | Storage  | Compression | Stats target |              Description              
---------------+------+-----------+----------+---------+----------+-------------+--------------+---------------------------------------
 change_id     | text |           | not null |         | extended |             |              | ID of the depending change.
 type          | text |           | not null |         | extended |             |              | Type of dependency.
 dependency    | text |           | not null |         | extended |             |              | Dependency name.
 dependency_id | text |           |          |         | extended |             |              | Change ID the dependency resolves to.
Indexes:
    "dependencies_pkey" PRIMARY KEY, btree (change_id, dependency)
Check constraints:
    "dependencies_check" CHECK (type = 'require'::text AND dependency_id IS NOT NULL OR type = 'conflict'::text AND dependency_id IS NULL)
Foreign-key constraints:
    "dependencies_change_id_fkey" FOREIGN KEY (change_id) REFERENCES sqitch.changes(change_id) ON UPDATE CASCADE ON DELETE CASCADE
    "dependencies_dependency_id_fkey" FOREIGN KEY (dependency_id) REFERENCES sqitch.changes(change_id) ON UPDATE CASCADE
Access method: heap
```

**Comment by trycycler** [comment]
That was it!
I was missing all my foreign key constraints. They must have been lost during a db migration.

I've replaced them and it is working normally again! Thank you for helping me find this issue.
