### ISSUE TITLE
Embedded comments in SQL statements with ampersands raise "Variable  is not defined" error 

### ISSUE THREAD

**Issue by rfmauri** [sqitchers/sqitch#679]
Hello,
When deploying a snowflake view with an ampersand embedded in the SQL statement Sqitch returned the following error:

**Variable  is not defined**

The SQL code was something like:

``` sql
create or replace view MYDB.MYSCHEMA.MYVIEW(
 column1
) as
(
  SELECT column1,
                -- dummy comment & more dummy here
                column2
FROM ....
);
```

I understand this is not critical at all once you identify what the problem is. We had a very very long view :-)

**Comment by theory** [comment]
Sqitch always passes the `--option variable_substitution=true` to enable [SnowSQL variables](https://docs.snowflake.com/en/user-guide/snowsql-use.html#using-variables), which Sqitch uses itself, and you can use in your change scripts. The docs say:

> To use an ampersand sign without using substitution, escape the ampersand sign with a second ampersand sign:
>
>     &&variable

So try `dummy comment && more dummy here`.
