### ISSUE TITLE
Rework broken by tag name containing slash

### ISSUE THREAD

**Issue by ewie** [sqitchers/sqitch#680]
Slashes in tag names are [not explicitly disallowed](https://sqitch.org/docs/manual/sqitchchanges/) but break `sqitch rework` because of the additional directory introduced by the tag name.

Steps to reproduce:

    sqitch --version
    sqitch init test --engine pg
    sqitch add first -n 'Add first'
    sqitch tag 0.1.0/rc -n 'Release 0.1.0/rc'
    sqitch rework first -n 'Fix first'

Output:

    sqitch (App::Sqitch) v1.3.0
    Created sqitch.conf
    Created sqitch.plan
    Created deploy/
    Created revert/
    Created verify/
    Created deploy/first.sql
    Created revert/first.sql
    Created verify/first.sql
    Added "first" to sqitch.plan
    Tagged "first" with @0.1.0/rc in sqitch.plan
    Cannot copy deploy/first.sql to deploy/first@0.1.0/rc.sql: No such file or directory

Out of curiosity, I also checked tag name `0.1.0/../rc` for which `sqitch rework` fails as well. I was thinking if it's actually a good idea to allow directory separators in tag names. This could lead to directory traversal attacks if fixed the naive way by just creating the missing directory.

**Comment by theory** [comment]
Great find, thank you! Slashes are allowed in change names so they can be organized in directories; I guess I forgot about the implications for tags when I designed them. Agree they should not be allowed in tag names. Will have to think about how to change/enforce it, though.
