### ISSUE TITLE
Running `rework` with a subdirectory that has not been manually created fails

### ISSUE THREAD

**Issue by jfeaver** [sqitchers/sqitch#686]
While using Sqitch version 1.3.1, I have a plan that has added `tables/users` in a previous tag. There have been no reworks in this project. When I run `sqitch rework -m "Add stuff to users" tables/users` then I get an error and no files are generated. The error is this:

```
Cannot copy sql/revert/tables/users.sql to sql/_reworked/revert/tables/users@1.0.0.sql: No such file or directory
```

Expected behaviour: Sqitch should create directories and files that it needs to make the rework command succeed.

Workaround: I can create the directories manually: `mkdir -p sql/_reworked/deploy/tables sql/_reworked/revert/tables sql/_reworked/verify/tables`

**Comment by theory** [comment]
Hav you set `reworked_dir` to `_reworked`?

**Comment by theory** [comment]
Apparently so, replicated the issue.

**Comment by jfeaver** [comment]
Thank you!
