### ISSUE TITLE
`rework` alters the existing `revert` script into the existing deploy script when it should not 

### ISSUE THREAD

**Issue by jfeaver** [sqitchers/sqitch#687]
When I run `sqitch rework tables/users -m "message"` then the existing `revert/tables/users.sql` file is modified when I want it to remain unmodified. Specifically, sqitch is copying `deploy/tables/users.sql` to `revert/tables/users.sql` so that my `DROP TABLE users;` is changed into the `CREATE TABLE` command.

**Comment by jfeaver** [comment]
I think I'm mistaken here. This is intentional behaviour so that the `revert` script can restore the previously deployed behaviour with its deploy script. A little confusing though.

**Comment by theory** [comment]
Yeah, a little unintuitive at first glance, but it does ultimately make sense!
