### ISSUE TITLE
Wishlist: Print the list of changes that would be deployed or reverted

### ISSUE THREAD

**Issue by vectro** [sqitchers/sqitch#701]
Currently sqitch will print something like "Deploying changes through <change>" but it would be good to see a list of the actual changes that would be deployed. This is especially powerful when combined with the revert.prompt_accept functionality.

@theory If there is buy-in for this idea I am happy to write a patch.

**Comment by theory** [comment]
I like it!

**Comment by vectro** [comment]
Thanks @theory, I created a pull request #702 for this.
