### ISSUE TITLE
.pgpass not picked up when database is connected to via ssh

### ISSUE THREAD

**Issue by plrtn** [sqitchers/sqitch#770]
I am running into an issue where I am unable to provide password via `.pgpass`. This is the message I ran into when executing `sqitch status`:

```
fe_sendauth: no password supplied
```

The following is the `sqitch.conf` file:
```
[core]
	engine = pg
	plan_file = sqitch.plan
	top_dir = .
[engine "pg"]
	target = db:pg://postgres@ip:port/dbname
	registry = sqitch
	client = psql
```
To ensure that I am able to get a connection altogether, I tried the method of last resort of putting the password into the URI. It worked.

I did the following to ensure that the `.pgpass` was correct:
- Establish a connection to the database in Datagrip using the same URI while providing password via `.pgpass`,
- loosening the matching rule to `*:*:*:*:pass`

However I am still not able to create a connection. I searched the mailing list and did not find anything that would help. Any assistance is appreciated.

**Comment by theory** [comment]
Can you connect via `psql`? If you’re connecting over `ssh`, your `.pgpass` file must be on the remote host.

**Comment by plrtn** [comment]
> Can you connect via `psql`? 

Yes via password authentication.

> If you’re connecting over ssh, your .pgpass file must be on the remote host.

That would not be ideal. What is your recommendation to using Sqitch with passwords? Due to organizational issues I am don't have the ability to switch to password-less auth?

Thanks for the help.

**Comment by theory** [comment]
What was the fix, @plrtn?
