### ISSUE TITLE
Custom SnowSQL variables

### ISSUE THREAD

**Issue by adamchen** [sqitchers/sqitch#789]
Hi!

I noticed that Sqitch under the hood uses SnowSQL to communicate with Snowflake. I see that some `--variable` args are passed to allow for the use of `&warehouse` etc. in scripts. Is there a way, or if not, is it something that you'd consider to be able to pass arbitrary variables through Sqitch to be evaluated by SnowSQL at runtime? Apologies in advance if I've missed something that already exists in the docs.

It'd help us out with a few use cases where we want to deploy similar (but not the same) versions of databases to different environments and therefore would need to parameterise our scripts.

Thanks in advance,
Adam

**Comment by theory** [comment]
If you use `&somevar` in your change scripts, you can pass them via the `--set` option or set them for specific targets or commands in the configuration. See [Other Options](https://sqitch.org/docs/manual/sqitch-configuration/#other-options) and scroll down to the "variables" item in the list.

**Comment by adamchen** [comment]
Perfect, thank you - apologies for missing that!

**Comment by adamchen** [comment]
(question answered)
