### ISSUE TITLE
Sqitch no longer detects Yugabyte

### ISSUE THREAD

**Issue by theory** [sqitchers/sqitch#841]
From comments on #635, with debugging by @stefanoric, it appears that Sqitch is failing to recognize Yugabyte for some reason. Most likely something has changed such that the detection code no longer works:

https://github.com/sqitchers/sqitch/blob/a7dfdb3b16979bf9cdd414af10eb1a7236a36066/lib/App/Sqitch/Engine/pg.pm#L147-L152

**Comment by stefanoric** [comment]
My sqitch version is 1.4.1

```
 ✗ sqitch --version
sqitch (App::Sqitch) v1.4.1
```

**Comment by theory** [comment]
Fix released in [v1.5.0](https://github.com/sqitchers/sqitch/releases/tag/v1.5.0).
